### ISSUE TITLE
[QUESTION] Does WHOOGLE_CONFIG_BLOCK_URL work in a systemd service file?

### ISSUE THREAD

**Issue by DeltaTangoLima** [benbusby/whoogle-search#1023]
I'm using local install with a few vars configured in the systemd service file. The `WHOOGLE_CONFIG_NEW_TAB` and `WHOOGLE_CONFIG_DISABLE` vars work just fine, but `WHOOGLE_CONFIG_BLOCK_URL` doesn't.

Is there a trick to quoting the regex or something? I've tried all manner of things, and it just doesn't work for me.

**Comment by benbusby** [comment]
It does work, I was able to test with:

```
WHOOGLE_CONFIG_BLOCK_URL="https?://(?:w{3}\.)?pinterest\.[a-zA-Z]{2,3}"
```

and could confirm that all "pinterest.com" sites were blocked from appearing in search results.

When you open your config on the home page, is the "Block by URL" field populated with the contents from `WHOOGLE_CONFIG_BLOCK_URL`? If not, there may have been a point where you saved a user-level config that included a blank entry for that field, which overrode your instance-level environment variable. 

Another option would be to pass a comma separated list of sites to block to `WHOOGLE_CONFIG_BLOCK` to see if that works better and/or is easier for you.

**Comment by DeltaTangoLima** [comment]
No worries - thanks for the tips.
