### ISSUE TITLE
[BUG] How to go back to search session after clicking a link

### ISSUE THREAD

**Issue by herbzhao** [benbusby/whoogle-search#1026]
Use both the self-hosted docker version of the https://[w.ftw.lol](https://w.ftw.lol/search)/search, whenever you search something and go into the link and "go back" on browser, the chrome or edge will both compalin about "Confirm Form Resubmission" and "ERR_CACHE_MISS" 

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome and edge

**Comment by benbusby** [comment]
This happens due to Whoogle using POST requests for search by default. You can get around this by enabling "GET Requests Only" in your config on the homepage.
