### ISSUE TITLE
[FEATURE] Replace "!4" bang with 4plebs archive search

### ISSUE THREAD

**Issue by MayaKitten** [benbusby/whoogle-search#1031]
Hi, the "!4" bang is some fitness website that isn't up anymore, it just 404s. I think it would be extremely useful if you replaced it with 4plebs all board search as this has very many posts archived, like over 10TB of millions and millions of posts and images.

To do this all you would need to do is use this URL:
https://archive.4plebs.org/_/search/text/Ubuntu%20Linux/

And replace **"Ubuntu%20Linux"** with the search query

Thanks

**Comment by Moist-Cat** [comment]
Bangs are a DDG feature whoogle downloads [a JS file](https://duckduckgo.com/bang.v255.js) with them, parses the links and uses them. I don't think we can change them.
That said I  4plebs, and a few other 4chan archives are already included.
Try !4plebs or !4cvg .

**Comment by benbusby** [comment]
Yeah the bangs can't be manually changed, but sounds like there's already support with the bangs that @Moist-Cat mentioned.
