### ISSUE TITLE
[QUESTION] Could you please list my whoogle instance on the repository ? (https://whoogle.datura.network)

### ISSUE THREAD

**Issue by nihilist001** [benbusby/whoogle-search#1034]
[QUESTION] Could you please list my whoogle instance on the repository ? (https://whoogle.datura.network)

onion link: http://whoogle.daturab6drmkhyeia4ch5gvfc2f3wgo6bhjrv3pz6n7kxmvoznlkq4yd.onion

let me know if there's anything i need to fix to get it listed here.

**Comment by benbusby** [comment]
Added, thanks!
