### ISSUE TITLE
[FEATURE] Option to use privacy-respecting services

### ISSUE THREAD

**Issue by hialvaro** [benbusby/whoogle-search#104]
**Describe the feature you'd like to see added**
It would be nice if we could activate an option to transform all "*twitter.com*" links to "*nitter.net*", "*youtube.com*" to "*invidio.us*", "*maps.google.com*" to "*openstreetmaps.org*" and "*instagram.com*" to "*bibliogram.art*" (or any instance of preference from users).

**Describe which parts of the project this would modify (/app/filter.py)**
I think "filter.py" should be modified (I may be wrong as I'm not very familiarized with the project). Maybe a string.replace("service.bad", "service.good") would do as (at least invidious and nitter) share the exact same links with their respective pairs (eg. twitter.com/Snowden/status/... == nitter.net/Snowden/status/... and same for invidio.us)

**Additional context**
Those services fully respect the privacy from users and allow them to navigate through those privative networks.

**Comment by benbusby** [comment]
This is a great idea. I'll work to implement this in the next release. Thanks for the suggestion!
