### ISSUE TITLE
[BUG] HTML not being sanitized

### ISSUE THREAD

**Issue by BetaPictoris** [benbusby/whoogle-search#1040]
**Describe the bug**
HTML within the descriptions and title of webpages is not being sanitized correctly. 

**To Reproduce**
1. Search for some HTML documentation (ie. "HTML color picker")
2. Find a title or description which contains HTML (in this example `<input type="color">`)
3. See the actual HTML color picker

**Deployment Method**
Other: https://s.tokhmi.xyz/

**Version of Whoogle Search**
v0.8.0

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 115.0.2

**Comment by BetaPictoris** [comment]
Here's a screenshot:
![image](https://github.com/benbusby/whoogle-search/assets/65696362/a9402a7e-a86b-4cfa-a2a0-973f7d03ce37)

**Comment by Moist-Cat** [comment]
Have you tried updating whoogle? Because I'm sure this issue was already mentioned and solved and I can't reproduce it on my machine.
version v0.8.1

**Comment by BetaPictoris** [comment]
Alright, I tried Whoogle 8.1 (didn't work), but after using 8.2 it does.
