### ISSUE TITLE
[QUESTION] Is it possible to show longer snippets/previews?

### ISSUE THREAD

**Issue by Potajito** [benbusby/whoogle-search#1046]
Hi! Is it possible to get longer previews/snippets (sorry I'm not sure of their proper name) in the search results, so they show more characters?
As in here:
![image](https://github.com/benbusby/whoogle-search/assets/39760810/77b205ff-ceb8-4d5a-b049-9b243a19d41c)
Thanks!

**Comment by benbusby** [comment]
It's possible, but would likely add noticeable additional processing time to return the results. The preview text isn't shortened by Whoogle, it's returned that way in the original query to Google, so to get longer preview snippets there would need to be an additional call per result to fetch the "description" metadata field from the site and then update the result view.
