### ISSUE TITLE
[BUG] Site block option breaks maps search results

### ISSUE THREAD

**Issue by FetaCini** [benbusby/whoogle-search#1048]
**Describe the bug**
Block site option is affecting 'maps' as well which leads to no search results in maps 
_Google Maps can't find toronto, on -site:pinterest.*_

**To Reproduce**
1. Turn on site blocking facebook.*,pinterest.*
2. do a search 'toronto'
3. click maps

**Deployment Method**
- [X ] Docker

**Version of Whoogle Search**
- [x] Latest build from Docker Hub 
- [x] Version 0.8.2

**Desktop (please complete the following information):**
 Firefox OSX/IOS

**Additional context**
This bug was marked as fixed in the below issue but it is still occuring for me.
https://github.com/benbusby/whoogle-search/issues/329

**Comment by benbusby** [comment]
Sorry for the delay, this should be fixed now and will be available in the `latest` docker image in a little while.

**Comment by FetaCini** [comment]
> Sorry for the delay, this should be fixed now and will be available in the `latest` docker image in a little while.

Don’t be sorry. Thanks for the fix 👍
