### ISSUE TITLE
[BUG] <Cannot Use whoogle.click>

### ISSUE THREAD

**Issue by Taratect** [benbusby/whoogle-search#1051]
**Describe the bug**
Is it just me or anyone else facung this problem?
I cannot use https://whoogle.click . It asks for sign in info. A sign in window appears when i ho to the site. It doesn't even let me create an account either

**To Reproduce**
Just click the link https://whoogle.click

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [Web Browser]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [x] Not sure

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Redmi 8]
 - OS: [MIUI 12]
 - Browser [Tried multiple]
 - Version [idk]

**Additional context**
Why do we need to sign in lol. I think it would have better privacy if we search anonymously without an account.

**Comment by nadesco** [comment]
Same thing happening on my desktop since yesterday. I enter my search term in the Search bar, hit enter and a sign-in window drops down . Am unable to get any search results. I've tried it with 2 different browsers (Librewolf and Brave). Have also tried disabling my vpn and rebooting.

**Comment by ahmad-alkadri** [comment]
Just tried to ping it and got 100% packet lost:

```
--- whoogle.click ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

Honestly looks like a problem on server-side. Anybody knows who host it can try to send them a message.

**Comment by benbusby** [comment]
Closing since the instance seems to still be down, and it's no longer referenced in the readme or instances file
