### ISSUE TITLE
[FEATURE] Config option to disable daily phone home to github.com

### ISSUE THREAD

**Issue by milksteakjellybeans** [benbusby/whoogle-search#1059]
I've got whoogle's docker version installed and every 24 hours it makes an https request to github, regardless of any usage.   I'm assuming this is a version check most likely, but I'm not certain.

It would be great if there was a config option to disable this.  In our closed network we'll only open access to google and will otherwise have to suppress alerts from blocked attempts to github.  Not a dealbreaker, but would be nice.

Assuming this is a version check, we manage our version upgrades centrally anyhow.

Thanks for considering

**Comment by Moist-Cat** [comment]
Yes, whoogle checks if there are updates available [here](https://github.com/benbusby/whoogle-search/blob/main/app/routes.py#L132). I don't see a way to disable it without modifying the code.

**Comment by benbusby** [comment]
This can now be disabled using `WHOOGLE_UPDATE_CHECK`. For example: `WHOOGLE_UPDATE_CHECK=0` will prevent Whoogle from checking for updates.
