### ISSUE TITLE
[BUG] systemd launch script does not work

### ISSUE THREAD

**Issue by bibimagic** [benbusby/whoogle-search#1063]
The systemd launch script does not work. Unable to launch whoogle from command prompt.

I did the manual installation and whoogle launches from the python virtual environment just after copying the repository.

> git clone https://github.com/benbusby/whoogle-search.git
> cd whoogle-search
> python3 -m venv venv
> source venv/bin/activate
> pip install -r requirements.txt
> ./run

However, I can't launch it from the root using <whoogle_repo_dir>/run (in my case /opt/whoogle-search/run) and the systemd launch script does not work.

> root:/# /opt/whoogle-search/run
> /opt/whoogle-search/venv/bin/python3: No module named app

**Deployment Method**
- manual

**Version of Whoogle Search**
- [ ] Latest build from source (GitHub)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Firefox 117

**Comment by un99known99** [comment]
I prepared a systemd service file, main call:

 ExecStart=/usr/bin/python3 /home/pi/.local/bin/whoogle-search --host <local ip> --port <portno>

**Comment by Moist-Cat** [comment]
You need to put `app` in the PYTHONPATH.
`PYTHONPATH=<whoogle_repo_dir> <whoogle_repo_dir>/run`

**Comment by pudding1111** [comment]
[Unit]
Description=Whoogle

[Service]
Type=simple
User=root
WorkingDirectory= /www/wwwroot/XXXX/whoogle-search/
ExecStart= /www/wwwroot/XXXX/whoogle-search/venv/bin/python3 -um app --host 127.0.0.1 --port 8786
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
SyslogIdentifier=whoogle

[Install]
WantedBy=multi-user.target

**Comment by benbusby** [comment]
@bibimagic one of the mentioned fixes should resolve your issue, feel free to reopen if you're still having issues.

**Comment by Moist-Cat** [comment]
[Unit]
Description=whoogle

[Service]
Environment="PYTHONPATH=<whoogle_repo_dir>"
ExecStart=<whoogle_repo_dir>/run

[Install]
WantedBy=default.target
