### ISSUE TITLE
[BUG] Double Quotes get removed from search after clicking to page 2

### ISSUE THREAD

**Issue by 2zzly** [benbusby/whoogle-search#1070]
**Describe the bug**
Certain Double Quotes phrases get double quotes "" removed from search after clicking to page 2 at bottom of results

**To Reproduce**
1. Search "No interface method getPackageInfo" android
2. Click on Next
3. Quotes are removed

**Deployment Method**
- [X] Other: repl.co

**Version of Whoogle Search**
- [X] Version 0.8.3

**Comment by abhishekmj303** [comment]
This happens when Google does not give results for that search term with quotes.

![IMG_20231010_110017.jpg](https://github.com/benbusby/whoogle-search/assets/85760664/53ad504c-ceda-4c0b-8700-d7db2a787a3c)

I'm not sure how exactly this is handled in whoogle

**Comment by benbusby** [comment]
This indeed seems to be expected behavior. If there aren't any further results with quotes included, then it follows Google's behavior in removing them
