### ISSUE TITLE
[QUESTION] Lack of site icons next to the link.

### ISSUE THREAD

**Issue by farline99** [benbusby/whoogle-search#1078]
Why are there no site icons in search? Google has them, but they don’t exist here. I gave search to a friend to try, but due to the lack of these icons, it was too difficult for him to choose between links and he returned to Google 🙁

**Comment by benbusby** [comment]
The icon data isn't returned from the endpoint Whoogle uses to fetch results, so it's not possible to include site icons.

**Comment by farline99** [comment]
Maybe we can get them from sites directly, rather than taking them from Google? These icons would really make the search much easier.

**Comment by benbusby** [comment]
Sure, I'll work on adding that in the near future.

**Comment by farline99** [comment]
wow! thank you very much! my friend will be a little more private thanks to this ❤️

**Comment by benbusby** [comment]
I pushed an update that now displays site icons next to each site, if a result website contains a valid image at `/favicon.ico`. The majority of sites do contain this image, but some don't and would require a bit more effort to figure out how to fetch them. Hopefully this helps in the meantime!

**Comment by farline99** [comment]
Thank you very much! ❤️
As soon as this version appears on Docker Hub, I will try it right away.

**Comment by farline99** [comment]
They are awesome. But why did you decide to place icons to the right of the link? It seems like the goal of the project is to make the interface as similar to Google as possible, but this point may confuse new users.

**Comment by benbusby** [comment]
There's blank space on the right side and it was easier to place them in that location. I might change it later if I get some more free time, but for now I'm not terribly concerned about this feature being 100% identical to Google.

**Comment by benbusby** [comment]
I actually changed my mind and just pushed an update that moves them to the left and shifts the result link over to make room for it.

**Comment by farline99** [comment]
You are the best ❤️❤️❤️🤟
