### ISSUE TITLE
[BUG] Helm chart deployment fails

### ISSUE THREAD

**Issue by Circenn5130** [benbusby/whoogle-search#1079]
**Describe the bug**

**To Reproduce**
1. Per instructions to install via Helm chart (no values or additional parameters used)

- Ensure you have [Helm](https://helm.sh/docs/intro/install/) >=3.0.0 installed
- Clone this repository
- Update [charts/whoogle/values.yaml](https://github.com/benbusby/whoogle-search/blob/v0.8.2/charts/whoogle/values.yaml) as desired
- Run helm install whoogle ./charts/whoogle

![2023-10-08_18-44-07](https://github.com/benbusby/whoogle-search/assets/20010643/0c29feb9-097d-4208-96b7-6908098d44ca)
. See error
`Error: INSTALLATION FAILED: template: whoogle/templates/serviceaccount.yaml:1:14: executing "whoogle/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create`

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [describe setup] Helm chart via git repo

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian 11

**Comment by Mawarii** [comment]
Hmm weird... I am able to deploy the chart. What kind of cluster are you using?

**Comment by Circenn5130** [comment]
Bare metal cluster (3 control planes) (3 nodes). 
I tried it again (cloned the repo and ran **helm install whoogle ./charts/whoogle**) just now and it came up with no issues. I got nothing >_<. Thank you for replying.
