### ISSUE TITLE
validators package is missing from dependencies

### ISSUE THREAD

**Issue by LeXofLeviafan** [benbusby/whoogle-search#1086]
**Describe the bug**
When installing the app into a dedicated venv (e.g. using `pipx`), it fails to start up, producing an error instead.

**To Reproduce**
1. [Install the app using `pipx`](https://github.com/benbusby/whoogle-search/#pipx)
2. Run `whoogle-search` in a terminal
3. See error
```
Traceback (most recent call last):
  File "/home/lex/.local/bin/whoogle-search", line 5, in <module>
    from app.routes import run_app
  File "/home/lex/.local/pipx/venvs/whoogle-search/lib/python3.11/site-packages/app/__init__.py", line 182, in <module>
    from app import routes  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lex/.local/pipx/venvs/whoogle-search/lib/python3.11/site-packages/app/routes.py", line 10, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'
```
(Also happens when running directly from a temporary install using `pipx run`)

**Deployment Method**
pipx

**Version of Whoogle Search**
Latest build from GitHub

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser N/A
 - Version N/A

**Additional context**
[Installing missing dependency into the venv](https://pypa.github.io/pipx/docs/#pipx-inject) fixes the error (though this method doesn't seem to be applicable to `pipx run`).

**Comment by zydou** [comment]
I also encountered this, and solved by the following commands:

```sh
pipx install whoogle-search
pipx inject whoogle-search validators
```

**Comment by LeXofLeviafan** [comment]
This workaround does work indeed, but it shouldn't be required in the first place :sweat_smile:

**Comment by zydou** [comment]
I've created a PR to fix it.
