### ISSUE TITLE
[QUESTION] Persistency of custom theme when using Docker(-compose)

### ISSUE THREAD

**Issue by SHU-red** [benbusby/whoogle-search#1089]
Hi,
since a few days now im using this awesome application.

I had a look at the documentation and was wondering why there is no volume-mount in the docker-compose file to keep all settings persistent

I understand that it is possible to set 90% of all settings as env-var, but i could not figure out how to make e.g. a custom theme persistent

After each server-reboot, the default settings/theme is present again

Is there a single file holding all of these settings to be able to mount this file/folder to a docker-volume?

Thanks in advance

**Comment by JoshuaMoeckelmann** [comment]
Hey, 

you can also set the Theme via an env-variable :) 

According to the Doc you can set the WHOOGLE_CONFIG_STYLE to the custom CSS you want to apply. Only pitfall is that this needs to be a single line...

For me, i set it to 
```
WHOOGLE_CONFIG_STYLE=:root{--whoogle-logo:#685e79;--whoogle-page-bg:#ffffff;--whoogle-element-bg:#4285f4;--whoogle-text:#000000;--whoogle-contrast-text:#ffffff;--whoogle-secondary-text:#70757a;--whoogle-result-bg:#ffffff;--whoogle-result-title:#1967d2;--whoogle-result-url:#0d652d;--whoogle-result-visited:#4b11a8;--whoogle-dark-logo:#ffffff;--whoogle-dark-page-bg:#111111;--whoogle-dark-element-bg:#303134;--whoogle-dark-text:#dddddd;--whoogle-dark-contrast-text:#e8eaed;--whoogle-dark-secondary-text:#bdc1c6;--whoogle-dark-result-bg:#222222;--whoogle-dark-result-title:#8ab4f8;--whoogle-dark-result-url:#34a853;--whoogle-dark-result-visited:#c58af9}#whoogle-w{fill:#eb6f92}#whoogle-h{fill:#f6c177}#whoogle-o-1{fill:#ebbcba}#whoogle-o-2{fill:#31748f}#whoogle-g{fill:#9ccfd8}#whoogle-l{fill:#c4a7e7}#whoogle-e{fill:#908caa}
```


And it works without any issues :) 

Have fun with Whoogle

**Comment by SHU-red** [comment]
Done!
Thank you!
