### ISSUE TITLE
[QUESTION] How do I set Whoogle as my primary search engine on chromium based browsers?

### ISSUE THREAD

**Issue by botnet88** [benbusby/whoogle-search#109]
I recently tried Whoogle on ungoogled-chromium. Search works as expected, but autocomplete is not working properly.

![search-settings](https://user-images.githubusercontent.com/61393492/88110275-8ae18580-cb71-11ea-9592-f047a3a11abd.png)

(Firefox)
![firefox-search](https://user-images.githubusercontent.com/61393492/88109418-178b4400-cb70-11ea-941e-44a350ad244c.png)

(ungoogled-chromium) (no suggestions)
![chromium-search](https://user-images.githubusercontent.com/61393492/88110289-903ed000-cb71-11ea-8dbb-b495417a9dbe.png)

**Comment by botnet88** [comment]
Finally figured it out. It's an extremely simple fix. By default, ungoogled-chromium disables autocomplete.

Going to chrome://settings/syncSetup, and enabling "Autocomplete searches and URLs" will fix the issue.

![fix](https://user-images.githubusercontent.com/61393492/88112659-f88fb080-cb75-11ea-87e3-6545cf500307.png)

The search engine settings I posted earlier should work for all chromium based browsers.

https://\<your whoogle url\>/search?q=%s
https://\<your whoogle url\>/autocomplete?q=%s

![chromium-search-fixed](https://user-images.githubusercontent.com/61393492/88113095-c2066580-cb76-11ea-8e06-65eb9e8c642c.png)

**Comment by FoxxMD** [comment]
There doesn't seem to be a way to use suggestions (autocomplete) with regular chrome. 
![image](https://user-images.githubusercontent.com/4663766/90159759-d9440780-dd5e-11ea-8949-a473c189cd3c.png)

Am I missing something? How do I set up chrome to use suggestions with whoogle @benbusby ?

**Comment by benbusby** [comment]
> Going to chrome://settings/syncSetup, and enabling "Autocomplete searches and URLs" will fix the issue.

@FoxxMD does that solution not work for you? I haven't tested it yet, but enabling that feature seems to reveal a new field for adding the autocomplete url (which is `https://<your whoogle url>/autocomplete?q=%s`).

Let me know if you tried that already and I'll look into it some more tonight.

**Comment by FoxxMD** [comment]
Yeah I tried that before posting, wanted to make sure I wasn't missing anything 😬 It doesn't make a difference. I'm wondering if its related to #112

**Comment by benbusby** [comment]
Maybe. I guess it's possible that chromium based browsers have their own criteria for what is considered "opensearch compatible", which is a bit frustrating since it's already compatible with non-chromium browsers. Aside from the `method` tag used for both search and suggestions, everything else in the opensearch template follows the [official OpenSearch specification](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md).
