### ISSUE TITLE
[QUESTION] GET vs POST

### ISSUE THREAD

**Issue by BumbleCast** [benbusby/whoogle-search#1094]
Thanks for the amazing work!
Whoogle runs great. I use it as a replacement for all my standard search engines. Only in Firefox the issue that Firefox Containers do not currently pass through POST requests is a little annoying. I was wondering, if there are any drawbacks to the suggest switch to GET requests (https://github.com/benbusby/whoogle-search#using-with-firefox-containers)?
If there are any privavcy or security drawbacks, I don't mind the annoyance. Thanks for the clarification.

**Comment by newtoallofthis123** [comment]
I mean regarding privacy and security, I don't think get and post makes that much of a difference. 

I cannot speak to how Whoogle handles the input internally, but atleast externally, the only benefit I sort of see is that the post requests most of the time do not include the actual search text in the url parameter, which might obfuscate your browser history. 

But other than that, I cannot attest to any advantages. Ig finally boils down to preference and necessity. Hope this helps :)

**Comment by BumbleCast** [comment]
Thank you so much for the clarification!

**Comment by newtoallofthis123** [comment]
You're welcome! Happy whoogling :)
