### ISSUE TITLE
[FEATURE] Option to disable retrieval of favicons

### ISSUE THREAD

**Issue by milksteakjellybeans** [benbusby/whoogle-search#1098]
With 0.8.4 the search page will include the favicons of the results. With my use case we have a central search service that has access to google via whoogle, but only out to google.  The new favicon feature pulls the icons direct from the various sites.

I would love to have an option to disable that fetching for use cases like ours where we expect and allow this service to communicate with google only.

As a hack, I've made a change to short circuit out of favicon fetching on our local instance.

```
246,248 filter.py
<        # Skip empty, parentless, or internal links
<        if not link or not link.parent or not link['href'].startswith('http'):
<            return
---
>        # Skip empty, parentless, or internal links
>        if 1 or not link or not link.parent or not link['href'].startswith('http'):
>            return
```

**Comment by newtoallofthis123** [comment]
Actually a good idea! Might also boost the search results delay

**Comment by benbusby** [comment]
Favicons can now be hidden/disabled using `WHOOGLE_SHOW_FAVICONS`. For example: `WHOOGLE_SHOW_FAVICONS=0` will prevent Whoogle from displaying favicons (and skips the process of fetching them in the first place).
