### ISSUE TITLE
[FEATURE] Add any language option.

### ISSUE THREAD

**Issue by Pusnow** [benbusby/whoogle-search#110]
**Describe the feature you'd like to see added**

Please, add "any language" option to main configuration

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**

Configuration.

**Additional context**

<img width="679" alt="스크린샷 2020-07-27 오전 11 50 44" src="https://user-images.githubusercontent.com/6031017/88499050-b942e300-cfff-11ea-9867-cd2953a1b4d9.png">

**Comment by KizunaH** [comment]
@Pusnow i sent you email asking about certain local providers. reply me if you are not uncomfortable to see such mails.
(unrelated comment for whoogle project but for users)

**Comment by gpopesc** [comment]
yes, I want also that as default option.

**Comment by kophi** [comment]
Yes me too. Please add this feature.

**Comment by benbusby** [comment]
This is available in the `develop` branch (and for Docker, the `beta` tag) of the project, with a pending merge into the main branch / new release sometime this week. Under the new config menu, all language options come with a "Default" setting, which will allow for any language.

**Comment by Aikatsui** [comment]
@Pusnow https://github.com/benbusby/whoogle-search#translating
