### ISSUE TITLE
[QUESTION] starting flask starts whoogle at local port 

### ISSUE THREAD

**Issue by betternoname** [benbusby/whoogle-search#1106]
When I try to work on my app locally and I would run flask run -p nnnn always whoogle appears not my flask app. Why this happens and how to stop it?

127.0.0.1 - - [29/Dec/2023 14:13:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Dec/2023 14:13:29] "GET /static/build/autocomplete.1661f315.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:30] "GET /static/build/main.68be5054.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:30] "GET /static/build/logo.72c3bd56.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:30] "GET /static/build/dark-theme.b0749774.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:30] "GET /static/build/light-theme.32a6b8fd.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:30] "GET /static/build/controller.d5f7f262.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:32] "GET /static%0Buildlight-theme.32a6b8fd.css HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:13:32] "GET /static%0BuildÚrk-theme.b0749774.css HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:13:34] "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:34] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:37] "GET /about HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:13:39] "GET /static/build/light-theme.32a6b8fd.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:39] "GET /static/build/main.68be5054.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:39] "GET /static/build/error.3d20eccf.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Dec/2023 14:13:42] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:13:53] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:13:53] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:13:53] "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:14:20] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:14:21] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [29/Dec/2023 14:14:21] "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1" 200 -
127.0.0.1 - - [29/Dec/2023 14:14:37] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Dec/2023 14:14:37] "GET /static/img/favicon/android-icon-192x192.png HTTP/1.1" 304 -
127.0.0.1 - - [29/Dec/2023 14:14:37] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 304 -

**Comment by benbusby** [comment]
I'm not sure how this could be happening, my only guess is that `FLASK_APP` might be set to the app.py file in your Whoogle directory. Either way this sounds like a flask configuration issue.
