### ISSUE TITLE
Open a new webpage after clicking

### ISSUE THREAD

**Issue by buyfakett** [benbusby/whoogle-search#1109]
**Describe the feature you'd like to see added**
I hope to open a new webpage after clicking on the search results

**Comment by Sailboat265** [comment]
Hi @buyfakett, there's actually an environment variable that you can set to enable the behaviour you wanted.
Just set `WHOOGLE_CONFIG_NEW_TAB` to `1`.

By the way, you can also enable this feature at the Whoogle homepage.
![image](https://github.com/benbusby/whoogle-search/assets/67184263/3bc4a519-1822-40ba-8289-918da91aa1a5)
