### ISSUE TITLE
[FEATURE] Open in freetube for youtube videos 

### ISSUE THREAD

**Issue by temporallyaccount** [benbusby/whoogle-search#111]
This is the ever mad feature request opened in this repository. 😂
@benbusby is it possible? whoogle project UI side only need display special symbol end of youtube URL in search result. when user click then open the video on freetube (something similar in telegram eg: when user click "open in telegram" https://t.me/fedora)

Freetube current repository. (freetube also use invidious).
https://github.com/FreeTubeApp/FreeTube
freetube vue rewrite repository (still not finished)
https://github.com/FreeTubeApp/FreeTube-Vue 

You already replaced search results with Nitter/Invidious/Bibliogram. https://github.com/benbusby/whoogle-search/pull/106

**Comment by Rru247** [comment]
🏋️#111🔥

**Comment by Rru247** [comment]
https://github.com/FreeTubeApp/FreeTube#browser-extension (freetube's dev) and if search engine call to the app then extension doesn't require. https://github.com/FreeTubeApp/freetube-redirect - freetube://

**Comment by federicotorrielli** [comment]
Tried with the extension on, and it works already. There is no need to really implement this.

**Comment by benbusby** [comment]
Thanks for looking into that @federicotorrielli, I'll go ahead and close this.
