### ISSUE TITLE
[QUESTION] I have a question about upgrading

### ISSUE THREAD

**Issue by kabaga** [benbusby/whoogle-search#1118]
I installed Whoogle on an LXC via the manual method. I followed this guide https://github.com/benbusby/whoogle-search?tab=readme-ov-file#manual. The question that I have now is, how do I upgrade this instance when the 0.8.5 get release?

**Comment by benbusby** [comment]
If you do the manual deployment and are on the `main` branch, you should just `git pull` when a new version is released. Otherwise you could check out the `0.8.5` tag via `git checkout v0.8.5` (or whichever specific version, once it's released).
