### ISSUE TITLE
'WHOOGLE_ALT_YT=youtube.mynet.home' mount path must be absolute

### ISSUE THREAD

**Issue by cgmastertecnology** [benbusby/whoogle-search#1120]
why? how can i redirect youtube link to my invidious instance at youtube.mynet.home ??

**Comment by joel-hamilton** [comment]
@cgmastertecnology have you uncommented this?

https://github.com/benbusby/whoogle-search/blob/aaf90b52bb919fa3c6146c807a6419f676301ca6/docker-compose.yml#L23

**Comment by benbusby** [comment]
You can redirect youtube links to your invidious instance by setting `WHOOGLE_ALT_YT=youtube.mynet.home` and enablign the "redirect social links" option on the home page config menu.

**Comment by cgmastertecnology** [comment]
i got:

Container whoogle-search Creating Error response from daemon: invalid mount path: 'WHOOGLE_ALT_YT=youtube.mynet.home' mount path must be absolute

**Comment by cgmastertecnology** [comment]
it works, thank you!

> @cgmastertecnology have you uncommented this?
> 
> https://github.com/benbusby/whoogle-search/blob/aaf90b52bb919fa3c6146c807a6419f676301ca6/docker-compose.yml#L23
