### ISSUE TITLE
[BUG] search bar doesn't show long query.

### ISSUE THREAD

**Issue by patienttruth** [benbusby/whoogle-search#1133]
**Describe the bug**
When I'm typing into the search bar, I can continue to type past the width of the bar, but it always displays the text starting at the beginning of the query.

**To Reproduce**

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version - v0.8.4
- [ ] Not sure

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device - pixel 6
 - OS: graphene OS, Android 14
 - Browser Firefox and Vanadium (hardened chrome)
 - Version
 - Vanadium 123.0.6312.40
 - Firefox Android - 123.1.0 (Build #2016007175), cb7c807e0f+

https://github.com/benbusby/whoogle-search/assets/105557996/378c3ed8-7073-4075-a6f5-8cfda2a4b66b

**Additional context**

**Comment by patienttruth** [comment]
Tested "desktop version" from Vanadium and it works as it should, no cutoff.

**Comment by adamantike** [comment]
@benbusby, are you planning to tag a new version, to release this and all other fixes added since `v0.8.4`?
