### ISSUE TITLE
Auto insert search suggestions to typing field when move by arrow keys

### ISSUE THREAD

**Issue by KizunaH** [benbusby/whoogle-search#115]
Sometimes whoogle shows search suggestions when type certain thing. For save time, we prefer get required suggestion into the typing field by pressing down arrow key and keep type the rest of sentence. Dad has this feature built-in.

Currently only possible to move to required suggestion by down arrow key and need press enter but then it also search the displayed suggestion.

**Comment by benbusby** [comment]
I'll work on adding this in soon. Thanks for the suggestion!

**Comment by benbusby** [comment]
Added in b2ecd8dc789299a26c7809c4931bb88fae06510e.

The fix is available in the `develop` branch and will be available in the beta Docker Hub build shortly.
