### ISSUE TITLE
[BUG] Webpage broken due to wrong MIME types

### ISSUE THREAD

**Issue by malte-v** [benbusby/whoogle-search#1187]
**Describe the bug**
Not sure if this is specific to my setup, but when running locally the webpage is broken (no css, js etc) and the following errors appear in the browser console:
```
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
localhost/:1 Refused to execute script from 'http://localhost:7890/tmp/whoogle-static/build/autocomplete.41fca461.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
10Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
controller.d5f7f262.js:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
localhost/:1 Refused to execute script from 'http://localhost:7890/tmp/whoogle-static/build/controller.d5f7f262.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
Apparently the responses have incorrect MIME types?

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: local deployment from nix package: https://github.com/NixOS/nixpkgs/blob/134e0e212e4ed74c03a80d67368ae5cef446b45d/pkgs/by-name/wh/whoogle-search/package.nix

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.9.0 from pypi
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux
 - Browser [e.g. chrome, safari] chromium
 - Version [e.g. 22] Version 129.0.6668.89 (Official Build, ungoogled-chromium) (64-bit)

**Comment by malte-v** [comment]
nvm my bad

**Comment by ArjonBu** [comment]
How did you fix this? I am seeing this using Caddy

**Comment by malte-v** [comment]
hey sry i can't remember😭
