### ISSUE TITLE
[QUESTION] Search String for Updated Firefox for Android (Adding Custom Search Engines)

### ISSUE THREAD

**Issue by ilovepancakes95** [benbusby/whoogle-search#120]
Firefox for Android updated and of course, they had to go changing things that worked perfectly fine in past.... So, it seems you can no longer hold down on search box in Whoogle and add search engine to Firefox that way. If I go into Settings>Search there is an option to add custom search engine to list but it asks for URL search string. It gives an example like "https://www.google.com/search?q=%s" where "%s" is the query.

It says under help to look at URL on your search engine after running a search for an idea of the string to use but Whoogle shows the URL as "https://whoogle.mydomain.com/search" with the query I just searched not displayed in the URL anywhere.

So, does Whoogle have a search string that can be used like the above example to make it work with the now updated Firefox for Android?

EDIT: I realized the above example string can be used with Whoogle, tested on desktop, but when I try to add Whoogle now to Firefox Android, and I put in that string it won't add and says: Error connecting to "Whoogle".

**Comment by xaabi6** [comment]
Please, check [this commit](https://github.com/benbusby/whoogle-search/pull/119/commits/473655bce361ba52565bd899ca0564791da339c8) from @DjLogozzo and see if it works.

**Comment by ilovepancakes95** [comment]
> Please, check [this commit](https://github.com/benbusby/whoogle-search/pull/119/commits/473655bce361ba52565bd899ca0564791da339c8) from @DjLogozzo and see if it works.

That was the search string I was trying yesterday mentioned in post above and it produced an error saying it couldn't connect to Whoogle, but today it worked.
