### ISSUE TITLE
[BUG] Internal Server Error

### ISSUE THREAD

**Issue by stanpen** [benbusby/whoogle-search#122]
**Describe the bug**
I can open Whoogle with no issues however when i try to search something i get an:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Please advise!

**To Reproduce**

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [*] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [* ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

*Smartphone (please complete the following information):**
 - Device: [iPad Pro]
 - OS: [ iOS 13.6]
 - Browser [Safari]
 - Version [latest]

**Additional context**

**Comment by stanpen** [comment]
It’s a firewall issue.

**Comment by 144358** [comment]
> 这是防火墙问题。
Thanks, now I'll try it

**Comment by 144358** [comment]
Unfortunately, my firewall is turned off by default, and I need to look for the cause of the problem
