### ISSUE TITLE
[FEATURE] Password protected search engine

### ISSUE THREAD

**Issue by joan-carles** [benbusby/whoogle-search#124]
Hi,

I think would be a good option to add a password protection to use the search engineer. I would like to use Whoogle in a VPS and only allow to use Whoogle to the people that knows the password.

Thanks

**Comment by FoxxMD** [comment]
You can do this already (on the docker at least) by specifying `WHOOGLE_USER` and `WHOOGLE_PASS` environmental variables. On first page load it'll do basic auth.

**Comment by benbusby** [comment]
@FoxxMD is correct, you can do this with Docker using the environment variables mentioned, or with pip/python using the `--userpass <username:password>` argument.

**Comment by joan-carles** [comment]
Thanks. I checked environmental variables and works

**Comment by Stoppedwumm** [comment]
I tried the --userpass <username:password>, but it doesn't ask me for a single password
