### ISSUE TITLE
Installation failed - pytest

### ISSUE THREAD

**Issue by timi35** [benbusby/whoogle-search#127]
Hello,

I get the following message if I try to install whoogle unsing pip install whoogle-search:

Collecting pytest==5.4.1 (from whoogle-search)
  Could not find a version that satisfies the requirement pytest==5.4.1 (from whoogle-search) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0, 2.9.1, 2.9.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 3.9.1, 3.9.2, 3.9.3, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.6.10, 4.6.11)
No matching distribution found for pytest==5.4.1 (from whoogle-search)

The installed version is:

rma@pi:~ $ pytest --version
This is pytest version 5.4.1, imported from /usr/local/lib/python3.7/dist-packages/pytest/__init__.py
rma@pi:~ $ 

How can I solve it?

Thanks a lot.
Best regards
Tim

**Comment by timi35** [comment]
Second question: is it possible to set the default search to all languages?
If yes, how?

Thanks!

**Comment by benbusby** [comment]
Hi Tim, thanks for reaching out. Can you post the output of `pip show pip`? 

> Second question: is it possible to set the default search to all languages? If yes, how?

Yes, but I believe it's only possible in the latest build (`develop` branch) of the project. I'm hoping to merge that into the main branch sometime this week, and then you'll be able to select "default" for search language (which would just omit language specificity from your search).

**Comment by timi35** [comment]
Hi benbusy,

the message is:

rma@pi:~ $ pip show pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Name: pip
Version: 20.2.3
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Required-by:

Thanks.
Tim

**Comment by benbusby** [comment]
Hi Tim, looks like your default pip points to python2.7 rather than python3.7 (which seems to have the correct version of pytest in your original comment). Can you try installing with `pip3 install whoogle-search` to enforce python3?

**Comment by benbusby** [comment]
Hi Tim, I'm going to close this issue for now since I'm assuming this (hopefully?) worked out for you. Feel free to comment or reopen if you've run into other issues.
