### ISSUE TITLE
Privacy respecting alternatives in results view seems doesn't work

### ISSUE THREAD

**Issue by temporallyaccount** [benbusby/whoogle-search#130]
Search a instagram username. whoogle will show instagram link for search result either about youtube
i'm not sure how does that work

**Comment by benbusby** [comment]
Not sure why you're seeing that, it's working fine for me. You're on version 0.2.1 and can see the "privacy respecting alternatives" option in the config checked?
____

![image](https://user-images.githubusercontent.com/33362396/95079582-d45b5e80-06e4-11eb-8687-fab2a8f682d5.png)
____
![image](https://user-images.githubusercontent.com/33362396/95079643-e937f200-06e4-11eb-9012-b4701addadd5.png)
____
![image](https://user-images.githubusercontent.com/33362396/95079731-07055700-06e5-11eb-911d-6e37601a95c8.png)

**Comment by temporallyaccount** [comment]
>You're on version 0.2.1 and can see the "privacy respecting alternatives" option in the config checked?

Now i understood. thanks.
