### ISSUE TITLE
[BUG] Search result pagination stops after page 3

### ISSUE THREAD

**Issue by steviez-uk** [benbusby/whoogle-search#131]
When doing any search (any search query) and you click next page at the bottom, you can only do it twice before it does not show. its as if there are no more results yet google has lots of results for each query.

**Comment by steviez-uk** [comment]
Any fix for this yet? Just downloaded the latest additions and it still acts the same.

**Comment by benbusby** [comment]
Fixed on `develop`/`beta` tag with e6db3112f780d113fc120a914c059a7d8b4f4695.
