### ISSUE TITLE
[QUESTION] Installation instructions vanilla/plain Ubuntu?

### ISSUE THREAD

**Issue by Panja0** [benbusby/whoogle-search#133]
Are there any installations instructions for installing Whoogle Search on an Ubuntu server with docker, just plain Ubuntu?

**Comment by FoxxMD** [comment]
The [docker instructions](https://github.com/benbusby/whoogle-search#f-manual-docker) will work regardless of operating system you are on

**Comment by Panja0** [comment]
I understand. But I do not want to use Docker. I would like to install it on a plain Ubuntu server.

**Comment by gripped** [comment]
E) Manual
There no package you can just install afaik.

**Comment by benbusby** [comment]
Right, if you don't want to use Docker, following the directions @gripped mentioned ([here](https://github.com/benbusby/whoogle-search#e-manual)) should work.

Closing for now, feel free to comment again if I misunderstood the question.
