### ISSUE TITLE
[FEATURE] ARM Docker build

### ISSUE THREAD

**Issue by ethancedwards8** [benbusby/whoogle-search#134]
**Describe the feature you'd like to see added**
I'd like to know if we could get an ARM build for Docker, I run all my stuff on Raspberry Pi's with Docker so I sadly can't try this out unless I build the image myself.

**Additional context**
N/A

**Comment by benbusby** [comment]
There actually is an ARM specific Dockerfile on the `feature/docker-updates` branch, but I haven't tried it out yet and don't have a spare Pi at the moment. Could you try out that branch on your setup? If all goes well I can push a new Docker Hub tag specifically for ARM builds.

**Comment by Zusier** [comment]
I can confirm whoogle is working on Rasberry Pi4b
[https://files.catbox.moe/m1mwkw.png](https://files.catbox.moe/m1mwkw.png)

**Comment by benbusby** [comment]
Quick update -- the new `buildx-experimental` tag on Docker Hub provides support for ARM builds. I'll be adding a CI build to automatically push updates to the multiarch image once I've tested it out a bit more.

**Comment by benbusby** [comment]
Closing this, as ARM is now supported via the `buildx-experimental` tag (and is being deployed automatically with pushes to the `develop` branch). The README has been updated to indicate which tag to use for ARM machines as well.

**Comment by xaabi6** [comment]
I know the issue has been closed but I would like to say that it's working flawlessly on my oDroid C2, thank you all who made this possible 👍
