### ISSUE TITLE
[QUESTION] TOR

### ISSUE THREAD

**Issue by Dudu514** [benbusby/whoogle-search#140]
Hi, i cloned the latest git of whoogle today, i see the option for TOR but it's "Unavailable".

I already have debian-tor bind to my local interface running on port 9050.

I tried to dig on that for a little bit and i found that "tor-prompt" from of absolute path to bin dir is giving me: 

"Unable to connect to tor. Maybe it's running without a ControlPort?".

Am i correct that whoogle is calling tor-prompt to pass search info. to tor?

I'm trying to figure the source of the problem. Thanks :)

**Comment by benbusby** [comment]
You probably need to update your `torrc` file to include the parameters seen [here](https://github.com/benbusby/whoogle-search/blob/develop/misc/tor/torrc). I'll do a full wiki page on setting up tor to be compatible with whoogle search once the feature is out of beta, but for now that's probably the only thing you're missing.

**Comment by Dudu514** [comment]
All right, thanks it's working fine now. 

I just got an error from : Unknown option 'CacheDirectoryGroupReadable'

I uncommented it for test purpose.

**Comment by benbusby** [comment]
Glad it's working now. I'll close this issue for now and reevaluate if CacheDirectoryGroupReadable is a required property or not. My guess is that it isn't.
