### ISSUE TITLE
[FEATURE] Tag docker images with specific version

### ISSUE THREAD

**Issue by ondrejmo** [benbusby/whoogle-search#141]
**Describe the feature you'd like to see added**
Would it be possible to tag docker images with specific version of whoogle instead of vague "latest" or "beta", i.e. `benbusby/whoogle-search:latest` -> `benbusby/whoogle-search:0.2.1`? I know that older versions are tagged a such, however the newer ones aren't. Thanks

**Additional context**
N/A

**Comment by benbusby** [comment]
Sure. Just updated the builds on Docker Hub -- starting with the next release, there will be images for each version.
