### ISSUE TITLE
[QUESTION] Is there a tool or a way to justify the features are indeed workable?

### ISSUE THREAD

**Issue by saltven** [benbusby/whoogle-search#142]
Just to prove to someone that the features such as, no IP address tracking or no cookies, etc are working perfectly fine.

**Comment by benbusby** [comment]
I'm not aware of a tool that would do that. You could launch a browser session with javascript and cookies disabled to verify that a Whoogle instance doesn't perform any differently, but beyond that you'd likely just need to audit the code yourself. I'm happy to help with that however I can, but I can't necessarily point to an absence of code. In `filter.py` though, there is a step that explicitly ensures that [scripts aren't passed through](https://github.com/benbusby/whoogle-search/blob/a97e837b098882508d3a8a0454539f6739e37f00/app/filter.py#L70-L72) to the user as well.

None of the requests made in the app forward any information (user agent, IP, etc) from the user to Google in the process of retrieving search results, or for fetching remote content (images, audio files, etc included in the results). You can verify that [here](https://github.com/benbusby/whoogle-search/blob/develop/app/request.py).

IP tracking itself is a more muddy topic though. The IP address Google will see is the address the search originates from. If you're using a VPN/Tor/proxy, then it will be that address. Likewise, if the Whoogle instance is remotely deployed, it will show that address. The only instance where your home IP is still being sent to Google is if you're running an instance at home with no VPN/Tor/proxy setup, which is noted in the readme. 

Hopefully this helps! Let me know if you want me to clarify anything.

**Comment by benbusby** [comment]
Closing for now, feel free to comment again if you need any further clarification.

**Comment by saltven** [comment]
Thanks for the explantion Ben. 

However, do you happen to have/know few research papers/journals/articles that you refer to before you made Whoogle? It would be great if you have your own paper that i can refer to. The reason why im asking this is because i'd like to do a research on comparing Whoogle to other search engines. Your immediate reply is highly appreciated. Thank you Ben.
