### ISSUE TITLE
[BUG] conversion of youtube url to Invidious url - wrong domain

### ISSUE THREAD

**Issue by github-ronk** [benbusby/whoogle-search#148]
**Describe the bug**
URL's for Invidious are using the www.invidiou.site domain, which leads to a dead end because it has a bad certificate.
Perhaps they should be translated to invidiou.site (without the www part) which works.
Not sure if this is a Whoogle issue or one in Invidious (they may fix their certificate), but might be worth considering.

**To Reproduce**
1. Configure your Whoogle to translate social links
2. Search for **Ariana Grande Thundercat “Them Changes” Adult Swim**
3. Scroll a bit down to find the Invidious link for that clip
4. Click the link, you get a certificate error.

**Deployment Method**
- [ x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x ] Version [0.2.1]
- [ ] Not sure

**Comment by benbusby** [comment]
Thanks for letting me know, the www subdomain issue has been fixed with 2ecde8386090dd36b69e82a264ebd3a96b0ac739. The invidious instance has also been updated to use the one from snopyta.org, since the health of that instance seems to be [a lot better](https://instances.invidio.us/).
