### ISSUE TITLE
[QUESTION] Followed the link in wiki to deploy the app via heroku and got an welcome page

### ISSUE THREAD

**Issue by fakeid30** [benbusby/whoogle-search#149]
I have tried deploying this app via my linux machine (so I can auto update) but after the whole process I see a welcome page and not the app. 
![Screenshot_2020-11-21 Heroku Welcome to your new app ](https://user-images.githubusercontent.com/26362832/99879786-3b9f8480-2c39-11eb-8220-a746cbcff1b3.png)

![Screenshot-20201121203702-782x442](https://user-images.githubusercontent.com/26362832/99879797-54a83580-2c39-11eb-863b-9957371a35ff.png)

What should I do so that I can see the app ?

**Comment by fakeid30** [comment]
I have figured out a solution : 

- Fork this repository on your own profile
- [Enable github integration in Heroku](https://devcenter.heroku.com/articles/github-integration#enabling-github-integration)
- Deploy from your fork
- Occasionally update your fork with the changes upstream to quickly deploy all changes.

**Comment by fakeid30** [comment]
@benbusby can you please let me know if the info I provided up is correct. 

If it is, can you please update the wiki ? If not, can you help me with figuring out why did I get a welcome page only?

Thank you.

**Comment by benbusby** [comment]
Yeah that seems to be a much better way of keeping personal Heroku deployments up to date. I've updated the wiki, thanks for bringing that to my attention.
