### ISSUE TITLE
YunoHost App

### ISSUE THREAD

**Issue by johnbrz** [benbusby/whoogle-search#15]
Any chance of creating an app for yunohost?
Since the intention of the whoogle-search that each user has their own instance, yunohost is a perfect marriage.
https://yunohost.org/#/packaging_apps_start

btw, the searx is already available there.
https://github.com/YunoHost-Apps/searx_ynh

**Comment by benbusby** [comment]
Seems easy enough, I'll add it when I get a sec

**Comment by benbusby** [comment]
Merged in with #62 (still higher priority than the others listed in that issue though).
