### ISSUE TITLE
[BUG] Google Ads present on results

### ISSUE THREAD

**Issue by tiagofreire-pt** [benbusby/whoogle-search#150]
**Describe the bug**
Google Ads present on results

**To Reproduce**
1. Go to 'whoogle'
2. Click on 'search bar'
3. Scroll down to top or bottom
4. See error (Google Ads showing)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version [83.0 64 bit]

**Additional context**

At the top:
![image](https://user-images.githubusercontent.com/41837236/99915096-6c46f300-2cf9-11eb-94ab-d9f59ae6ee22.png)

**Comment by tiagofreire-pt** [comment]
Sometimes, the ads shows at the bottom:

![image](https://user-images.githubusercontent.com/41837236/99915140-b92ac980-2cf9-11eb-9bfa-6c6698d8d214.png)

**Comment by benbusby** [comment]
Thanks for reporting! Fixed in f898a8e7a7e45fe34109a766352dda0d26590123.
