### ISSUE TITLE
Alternative Social media redirect URL gives Security/Timeout Errors

### ISSUE THREAD

**Issue by johntron8** [benbusby/whoogle-search#151]
I found that when user enabled "Replace social media links" from settings, redirect links for youtube breaks due to auto embedding of prefix "www" in urls for example https://www.invidiou.site/ is broken. Without "www" prefix it works without any issues. Also this instance might have some frequent downtime issues, i can't access it mostly or maybe their server side load issue.

I think adding "www" as prefix in all redirect urls might break their functionality someday, so pls remove "www" prefix & use https:// as prefix only.

Also my suggestion is to use Snopyta Org Instance for Youtube redirecting if possible.
Take a look at this https://snopyta.org/

Thanks for doing an awesome work on whoogle.

**Comment by benbusby** [comment]
Thanks for bringing this to my attention! I've updated the invidious instance to invidious.snopyta.org, and there shouldn't be any issues with supporting www subdomains now. (2ecde8386090dd36b69e82a264ebd3a96b0ac739)

**Comment by johntron8** [comment]
Thanks @benbusby for quickfix

Unfortunately there is one more issue with invidious redirection which totally breaks its working.
When user accessing whoogle from an mobile device all youtube links starts with mobile format i.e https://m.youtube.com.
Now When user enabled "Replace Social media links" & access whoogle from mobile phone the invidious links also contains "m" word as prefix same on mobile youtube version which breaks invidious redirection.
Currently it redirects to https://m.invidious.snopyta.org/ which is invalid URL. 
Valid one is https://invidious.snopyta.org/

**Comment by benbusby** [comment]
Gotcha -- I should've thought of that. Should be fixed now.
