### ISSUE TITLE
[BUG] no succesful enforcing of HTTPS on Heroku

### ISSUE THREAD

**Issue by pred2k** [benbusby/whoogle-search#153]
**Describe the bug**
I would like to have a all search requests and reponses to go though HTTPS.  
HTTP requests should be upgrade to HTTPS.

**To Reproduce**
1. Open new private window in Firefox (also open network analytics from web developer tools to see detailed behaviour)
2. Go go `g00gl3.herokuapp.com` (no https!)
3. Open **Configuration** and see that the **Root URL** begins with `https://...`
4. Now search for anything and see that everything is transfered unencrypted

![Bildschirmfoto 2020-12-05 um 12 03 34](https://user-images.githubusercontent.com/1071020/101240928-b9ac6280-36f2-11eb-8f88-59e6923c68c8.png)

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc) - **commit 54109874fb312f174eb5c65795c62760f65f87de**
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: **MacOS Catalina 10.15.5**
 - Browser: **Firefox**
 - Version: **82.0.2 (64bit)**

**Additional context**
I've tried to have the **ROOT URL** (and search language) to be constant in the heroku dyno with having this cronjob:
```
curl -d "ctry=&lang_interface=&lang_search=lang_de&near=&alts=on&url=https%3A%2F%2Fg00gl3.herokuapp.com%2F" https://g00gl3.herokuapp.com/config
```

**Comment by benbusby** [comment]
Thanks for reporting! HTTPS enforcement on Heroku has been an issue in the past. The commit referenced above should fix this once and for all. I tested it on my end to confirm that it's always upgrading now, but let me know if you see this happen again.

**Comment by pred2k** [comment]
Yeah! Looks great now, thanks mate

**Comment by pred2k** [comment]
i dont know why, but g00gl3.herokuapp.com behaves again like in my initial post. stays on unencrypted http.
its on 6e7ec9918a7bb04b8d78358ea5dd2315a1b9a3eb now

**Comment by benbusby** [comment]
Hmm, I just launched a new herokuapp instance of my own, and it seems to working fine and upgrading automatically. Also http://g00gl3.herokuapp.com is upgrading to https for me. You could try the latest commit on the `heroku-app-beta` branch, but it shouldn't be any different.
