### ISSUE TITLE
Heroku deploy Failed for "Develop" branch

### ISSUE THREAD

**Issue by johntron8** [benbusby/whoogle-search#156]
I am trying to deploy the Develop branch of whoogle on heroku  using this [URL](https://heroku.com/deploy?template=https://github.com/benbusby/whoogle-search/tree/develop). But it gives some error saying:

The content of app.json is not valid; please see app.json Schema for more information. The file does not contain a valid JSON entity.

I used always same branch to deploy whoogle, none of same error faced until some last commits. I hope it got fixed soon @benbusby.
Thanks

**Comment by benbusby** [comment]
Should be fixed now with 51e69b579ba30305ddd08d9ff284d182209ecb64.
