### ISSUE TITLE
[QUESTION] Nginx Configuration To Proxy Whoogle as A Subdirectory Cannot Find /config. How to handle this?

### ISSUE THREAD

**Issue by Saroufim** [benbusby/whoogle-search#158]
Hello, 
I'm running Whoogle as a subfolder on my site under /search/. At first, Whoogle wouldn't find its static files but then I explicitly used sub_filter to redirect it to the right path. Now Whoogle won't read its own configs from the same path and reverts back to looking for them on the main site, ignoring the sub_filter rule. What is the proper way to handle this with nginx?

Here's my conf:
```

location /search/   {
    include /config/nginx/proxy.conf
    sub_filter_once off;
    sub_filter '/static/' '/search/static/';
    sub_filter_types *;
    sub_filter "/config" "/search/config";
    proxy_pass http://0.0.0.0:5000/;
}

```

**Comment by alexw1982** [comment]
Not running on a subfolder but have you to add a rewrite like this to the location block:

`    rewrite ^/search/(.*)$ /$1 break;`

**Comment by maaAnandsheela** [comment]
location /search {
               rewrite /search/(.*) /$1 break;
               proxy_pass http://0.0.0.0:5000/;
               proxy_redirect     off;
                proxy_set_header Host $host;
               proxy_http_version 1.1;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    
}

**Comment by alexw1982** [comment]
it tried this just for fun and it given (at least) me a white, empty page

**Comment by maaAnandsheela** [comment]
maybe there should be some error.

**Comment by looi-wh** [comment]
hi. tho its abit late, but I have solved this issue somehow as i was setting up whoogle for myself

```
location /google {
    return 302 $scheme://$host/google/;
}
location /google/ {
    sub_filter_once off;
    sub_filter 'https://domain.com' 'https://domain.com/google/';
    proxy_pass http://0.0.0.0:5000/;
}
```

**Comment by cs01** [comment]
> hi. tho its abit late, but I have solved this issue somehow as i was setting up whoogle for myself
> 
> ```
> location /google {
>     return 302 $scheme://$host/google/;
> }
> location /google/ {
>     sub_filter_once off;
>     sub_filter 'https://domain.com' 'https://domain.com/google/';
>     proxy_pass http://0.0.0.0:5000/;
> }
> ```

I spent more time than I want to admit trying to solve this. I thought `WHOOGLE_CONFIG_URL` might work but it didn't. 

It might be helpful to others to add the above config to the README since it's probably a fairly common setup.

**Comment by caio1007** [comment]
> hi. tho its abit late, but I have solved this issue somehow as i was setting up whoogle for myself
> 
> ```
> location /google {
>     return 302 $scheme://$host/google/;
> }
> location /google/ {
>     sub_filter_once off;
>     sub_filter 'https://domain.com' 'https://domain.com/google/';
>     proxy_pass http://0.0.0.0:5000/;
> }
> ```

this code is giving me an error in nginx
