### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by OlivierVerhoek** [benbusby/whoogle-search#162]
**Describe the bug**
2020-12-29T15:11:43.966179075Z standard_init_linux.go:207: exec user process caused "exec format error"

**To Reproduce**
Go to RPI and execute the deployment in terminal

**Deployment Method**
docker pull benbusby/whoogle-search
docker run --publish 5000:5000 --detach --name whoogle-search benbusby/whoogle-search:latest

**Desktop (please complete the following information):**
 - OS: RPI Raspberry pi OS64 bit

**Comment by benbusby** [comment]
I just pushed a new tag (`buildx-experimental`) to Docker Hub with support for ARM builds. Could you try that one out rather than the `latest` tag?

**Comment by fabriciopirini** [comment]
Not OP but I had the same problem and the new `buildx-experimental` tag solved! Thanks!

**Comment by benbusby** [comment]
Closing this, as ARM is now supported via the `buildx-experimental` tag. The README has been updated to indicate which tag to use for ARM machines as well.
