### ISSUE TITLE
Ability to copy search result URL

### ISSUE THREAD

**Issue by Aikatsui** [benbusby/whoogle-search#166]
**Describe the feature you'd like to see added**
Search: Ben Busby

Current: https://sub.domain.com/search
Expect: https://sub.domain.com/search/ben+busby

**Comment by benbusby** [comment]
This is already implemented, you just need to enable `GET Requests Only` in your config. Once that is enabled, search URLs will appear like so: https://sub.domain.com/search?q=ben+busby

**Comment by Aikatsui** [comment]
@benbusby may be you can enable this in pre-defined config, usually we share search results and bookmark tabs etc. normally we fork the repo and deploy so ;)
