### ISSUE TITLE
[BUG] In consistent dark mode.

### ISSUE THREAD

**Issue by doloresjose** [benbusby/whoogle-search#167]
**Describe the bug**
Dark mode is inconsistent.

**To Reproduce**
Just deployed the latest container from docker hub and found it.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [*] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [* ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser -Vivaldi(Based on chromium)

**Smartphone (please complete the following information):**
None

**Additional context**
Screenshot
https://telegra.ph/file/70bf1f8ab3dd3e1efde7f.png

**Comment by benbusby** [comment]
Not seeing this on my end. Are you using any browser extensions for dark mode (i.e. darkreader)?

**Comment by cybernats** [comment]
it's possible to reproduce, chrome://flags then force dark mode to web contents but i guess that's not a real issue because every instances dont have that trouble.

**Comment by benbusby** [comment]
Enabling that flag doesn't reproduce it for me, and I'm not seeing the issue on any of my instances or any known public instances. If someone figures it out and knows a solution, submit a PR.
