### ISSUE TITLE
[QUESTION] How can I allocate more threads to Whoogle?

### ISSUE THREAD

**Issue by maxdesalle** [benbusby/whoogle-search#170]
I'm using Ubuntu Server based on a Raspberry Pi 4, and unfortunately, Whoogle is incredibly (really!) slow. It works, but it's very slow.

When executing the following command: ```sudo systemctl status whoogle.service```, I get the following status:

```
● whoogle.service - Whoogle
     Loaded: loaded (/lib/systemd/system/whoogle.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-01-18 16:12:11 UTC; 1min 17s ago
   Main PID: 39068 (python3)
      Tasks: 5 (limit: 9255)
     CGroup: /system.slice/whoogle.service
             └─39068 /home/ubuntu/whoogle-search/venv/bin/python3 -um app --host 0.0.0.0 --port 5000

Jan 18 16:12:11 ubuntu systemd[1]: Started Whoogle.
Jan 18 16:12:13 ubuntu whoogle[39068]: Serving on http://0.0.0.0:5000
Jan 18 16:12:13 ubuntu whoogle[39068]: WARNING:waitress.queue:Task queue depth is 1
Jan 18 16:12:13 ubuntu whoogle[39068]: WARNING:waitress.queue:Task queue depth is 2
Jan 18 16:12:18 ubuntu whoogle[39068]: WARNING:waitress.queue:Task queue depth is 3
Jan 18 16:12:23 ubuntu whoogle[39068]: WARNING:waitress.queue:Task queue depth is 4
Jan 18 16:13:19 ubuntu whoogle[39068]: WARNING:waitress.queue:Task queue depth is 5
```

I have looked this up online, and apparently, it's linked to the fact that there aren't enough "threads" available for Whoogle to use (source: [1](https://github.com/Pylons/waitress/issues/235), [2](https://github.com/Pylons/waitress/issues/309), [3](https://stackoverflow.com/questions/55857058/how-to-find-the-cause-of-task-queue-depth-warnings-from-waitress)).

How can I fix this issue?

**Comment by benbusby** [comment]
It's in [the Waitress documentation](https://docs.pylonsproject.org/projects/waitress/en/stable/arguments.html). Can't link directly to it, but there's a `threads` argument you can pass to `waitress.serve` in [routes.py](https://github.com/benbusby/whoogle-search/blob/406e2366664c9e99de586e67c28f21470413f06c/app/routes.py#L402).

It's a bit curious that it's slow for you though...I have Whoogle running on a Raspberry Pi 2b, plus a few remote instances, and each one is nearly as fast as running the server locally.

**Comment by maxdesalle** [comment]
Thanks Ben, appreciate it.

Indeed! Me too. I had previously tried Whoogle on a basic 5$ droplet instance on DigitalOcean, and it worked flawlessly. Weirdly enough, on a Raspberry Pi with 8GB of RAM, it doesn't.
