### ISSUE TITLE
[Reddit Alternative URL redirection]

### ISSUE THREAD

**Issue by johntron8** [benbusby/whoogle-search#172]
@benbusby There is an new reddit access frontend available same as Invidious for youtube.
It will be an good option to add it in alternative redirections feature.
Here is the link https://libredd.it/
Thanks

**Comment by benbusby** [comment]
Oh nice, and it's from @spikecodes too. I'll work on adding that soon.

**Comment by cybernats** [comment]
is there anything for fb?

**Comment by johntron8** [comment]
> is there anything for fb?

There is earlier an frontend service for FB, but now it seems shut down.
https://nofb.pw/

**Comment by johntron8** [comment]
> Oh nice, and it's from @spikecodes too. I'll work on adding that soon.

Thanks sir.
Also if possible, can you add OpenStreetMap.org support redirection in Google maps section when Alternative urls button is Active.

**Comment by benbusby** [comment]
> Also if possible, can you add https://OpenStreetMap.org support redirection in Google maps section when Alternative urls button is Active.

Unfortunately that's a bit more complicated, since open street map doesn't use the same link format as Google maps. It'll require a bit more effort to come up with a link "translator", so I won't include that for this effort.

**Comment by johntron8** [comment]
@benbusby thanks for adding.

But heroku deployment failed after the new commits.
As shown in picture below:
![Screenshot_20210124-130613_1](https://user-images.githubusercontent.com/74888172/105624180-8e531380-5e17-11eb-8a07-4e431c776f80.jpg)

**Comment by benbusby** [comment]
That's not a Whoogle issue, it's an error from Docker Hub.
