### ISSUE TITLE
Instruction for enable features before deploy

### ISSUE THREAD

**Issue by cybernats** [benbusby/whoogle-search#177]
Where should i modify to enable below feature before deploy? (i dont want re-enable again and again)
1. Dark mode
2. Replace social media links
3. Get requests only
4. Safe search
5. Open Links in new Tab

**Comment by benbusby** [comment]
I assume you're using Heroku? Follow the [instructions here](https://github.com/benbusby/whoogle-search#prevent-downtime-heroku-only). You'll need to set up a cron job on one of your devices to persist those config settings between Heroku downtime periods. For your settings it'd be something like `*/20 7-23 * * * curl -d "dark=1&alts=1&safe=1&new_tab=1&get_only=1" -X POST https://<your heroku app name>.herokuapp.com/config > /tmp/whoogle-refresh`

**Comment by cybernats** [comment]
@benbusby so i propose this as enhancement (feature request) and expect this applicable for all deployment methods in one way.
we need this as list of config somewhere in whoogle codebase to set-up before deploy then app operate according to it everytime.

You mentioned about heroku. i tested, it doesn't need to down. as i see GUI config changes only apply to that browser window and if i visit through incognito or other browser then previous config doesn't apply to them (if i have saved config via GUI then i can tap the load button and write the name of config to get it)

**Comment by cybernats** [comment]
@benbusby any update about this? i mean something similar below,
```
# dark_mode=true
# social_media_links=false
# get_requests=true
# safe_search=true
# open_links_new_tab=true
```

I see you've something your own implementation on whoogle that i am lazy to read source code so i am not telling to change or remove it. (it might be beneficial for some users to save custom config under names and load when necessary)

But if you add config list as above, admin comment-out # to set them to true before deploy then that settings become default to instance also ignore manual changes and later even if user set custom settings via GUI then those only will remain for that window cookies as i mentioned on previous comment

**Comment by cybernats** [comment]
https://github.com/benbusby/whoogle-search/issues/186
