### ISSUE TITLE
[BUG] autocomplete on iOS Firefox not working

### ISSUE THREAD

**Issue by alexw1982** [benbusby/whoogle-search#181]
Autocomplete fails after setting up whoogle on Firefox on iOS via (http[s]://\<your whoogle url\>/search?q=%s). It works via the desktop browser (also firefox though).

Device: iPhone Xr
iOS: 14.3 (18C66)
Firefox: Daylight 30.0 (3279)
Whoogle: latest docker version with beta tag

**Comment by benbusby** [comment]
Unfortunately this is actually a limitation of mobile browsers themselves, since they don't provide any way of setting a custom autocomplete url (i.e. `<whoogle_url>/autocomplete?q=%s`).
