### ISSUE TITLE
[FEATURE] OpenStreetMaps

### ISSUE THREAD

**Issue by andyrufasto** [benbusby/whoogle-search#182]
Please replace google maps search with openstreetmaps.

https://www.openstreetmap.org/

**Comment by alexw1982** [comment]
Please only make this an option as OSM is not even comparable in terms of POIs and other data sources integrated into GMaps. Ideally I would love to rather have google maps results in a more privacy friendly form - however I assume that this would be a major undertaking...

**Comment by benbusby** [comment]
I don't think this really fits in the scope of the project, unfortunately. There would need to be a fairly large amount of effort put in to translate even simple Google Maps URIs into the OpenStreetMaps equivalent, and even then it would still be lacking a lot of other features (as alexw1982 mentioned). 

If at some point someone develops a library for easily converting between the two (could be me, but it wouldn't be under Whoogle), I'd definitely consider it, but as it stands I don't think it makes much sense to focus on this.
