### ISSUE TITLE
[FEATURE] add healthcheck or curl to docker container

### ISSUE THREAD

**Issue by alexw1982** [benbusby/whoogle-search#184]
would like to make use of docker healthchecks in order to restart the container in case it crashes. It would be great if either a healthcheck is directly integrated into the container or curl is installed into the container so that people can setup their own healthcheck. Right now I am building an [image](https://hub.docker.com/repository/docker/alexw1982/whoogle) ontop of the original one to run `apt update && apt install curl` as a workaround.
FYI: I am using `https://hub.docker.com/r/willfarrell/autoheal/` to make the restart happen.

**Comment by alexw1982** [comment]
Please ignore the curl part of the request as there are other tools (wget) already included in the container that allow for basic health checks ...

**Comment by pred2k** [comment]
I think this would do it.
```diff
diff --git a/Dockerfile b/Dockerfile
index a62bcee..66cf054 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,7 +8,8 @@ RUN apt-get update && apt-get install -y \
     libxml2-dev \
     libxslt-dev \
     libffi-dev \
-    tor
+    tor \
+    curl

 COPY config/tor/torrc /etc/tor/torrc
 COPY requirements.txt .
@@ -52,4 +53,7 @@ COPY . .

 EXPOSE $EXPOSE_PORT

+HEALTHCHECK --interval=3m --timeout=5s \
+  CMD curl --fail http://localhost:${EXPOSE_PORT}/ || exit 1
+
 CMD config/tor/start-tor.sh & ./run
```

**Comment by benbusby** [comment]
Apologies for the delay on this! I've added a (wget) healthcheck now, which should be available shortly for all `develop` images.
