### ISSUE TITLE
[BUG] `misc` folder missed with `pip install whoogle-search`

### ISSUE THREAD

**Issue by spex66** [benbusby/whoogle-search#185]
**Describe the bug**
* First upgraded with `pip` from 0.1.0 to 0.3.0
* next uninstalled and reinstalled with `pip`
* issue starting `whoogle-search`  cannot find `site-packages\\app\\../misc/languages.json`

**To Reproduce**
1. `pip install whoogle-search`
2. missing `misc` folder in `site-packages`
3. which causes the `whoogle-search.exe` start to fail with:
```
Traceback (most recent call last):
  File "c:\tools\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\tools\miniconda3\Scripts\whoogle-search.exe\__main__.py", line 4, in <module>
  File "c:\tools\miniconda3\lib\site-packages\app\__init__.py", line 22, in <module>
    os.path.join(app.config['APP_ROOT'], '../misc/languages.json')))
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\tools\\miniconda3\\lib\\site-packages\\app\\../misc/languages.json'
```

**Deployment Method**
- pip/pipx

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [0.3.0]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows
 - Python: Python 3.7.4 (Miniconda)
 - pip 20.1.1
 - Browser : not relevant

**Comment by benbusby** [comment]
Thanks for reporting -- this should now be fixed in `v0.3.1`.
