### ISSUE TITLE
[FEATURE] Config file for preset Configuration 

### ISSUE THREAD

**Issue by mizzunet** [benbusby/whoogle-search#186]
**Describe the feature you'd like to see added**
Well, it would be wonderful if there's a config file in the repo where Whoogle default Configuration is defined before and can be set before deploying.

**Additional context**
Like, variables, Country, City, IsDarkModeOn etc. I know there is a Load function for loading the previously saved settings. Still, this also be helpful IMO

**Comment by alexw1982** [comment]
If implemented, ideally all settings can also be set via environment variables (for the docker folks)

**Comment by mizzunet** [comment]
Thanks

**Comment by pred2k** [comment]
I've deployed whoogle to a cheap VPS in Hetzner Datacenter in Germany and for some reason the search result are presented in arabic, right-to-left output, when i leave Interface & Search Language at default.
![Bildschirmfoto 2021-02-28 um 16 11 30](https://user-images.githubusercontent.com/1071020/109423441-b79b2c80-79df-11eb-83fe-f6ad974ba6dc.png)
I want to do regular container updates/restarts with `docker-compose pull && docker-compose up --detach --force-recreate --remove-orphans` and would like to prefer that settings can be made with the start of the application.

**Comment by benbusby** [comment]
All config settings can now be set via environment variables, and/or included in `whoogle.env` before deployment. Please [see the updated documentation](https://github.com/benbusby/whoogle-search#config-environment-variables) for more info.
