### ISSUE TITLE
[QUESTION] How do I set Whoogle as default SE in Chromium based android browser?

### ISSUE THREAD

**Issue by mizzunet** [benbusby/whoogle-search#187]
Isn't it possible?

**Comment by maaAnandsheela** [comment]
i use ungoogled chromium extensions verion.
use chrome://settings in address to add new search engine. 
https://uc.droidware.info/extension.html

I guess it might work on yandex browser too.

**Comment by mizzunet** [comment]
> i use ungoogled chromium extensions verion.
> use chrome://settings in address to add new search engine.
> https://uc.droidware.info/extension.html
> 
> I guess it might work on yandex browser too.

Thanks never know that this existed
