### ISSUE TITLE
[FEATURE] Please add "ROOT_URL" variable

### ISSUE THREAD

**Issue by maxlinux2000** [benbusby/whoogle-search#195]
scenario:
installation via docker on a VPS with public ip, with apache (ispconfig) and the proxy module actived

```
ProxyPass / http://209.97.191.124:5000/
ProxyPassReverse / http://209.97.191.124:5000/
```
If I go directly to the domain: https://whoogle.tormentasolar.win/
it works perfectly.

But when we put whoogle as the preferred search engine in firefox, if in the Root URL field there is http://209.97.191.124:5000/ this will be the url that the browser re-sends you

It would be nice if it can be controlled with a variable from docker and docker-compose

So please add the ROOT_URL variable

thanks
MAX

**Comment by benbusby** [comment]
Now configurable with environment variables, [see the updated documentation](https://github.com/benbusby/whoogle-search#config-environment-variables) (in this case, `WHOOGLE_CONFIG_URL` should be set).
