### ISSUE TITLE
[BUG] !bang-operators only work as prefix

### ISSUE THREAD

**Issue by Wever1985** [benbusby/whoogle-search#196]
**Describe the bug**
The !bang-operators adopted from DuckDuckGo only seem to be identified correctly when typed _in front of_ other search terms. On DDG they can be placed anywhere in the search e.g. "hello world !reddit" or even "hello !reddit world". Both would search the website reddit.com for "hello world".

**To Reproduce**
1. Search for something using a !bang-operator _at the end_
2. !bang-operator is ignored and no redirection to target website occurs

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker (with "buildx-experimental" Docker tag)
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Brave
 - Version: 1.19.92

**Comment by benbusby** [comment]
Fixed -- thanks!
