### ISSUE TITLE
Add config option to enable ads

### ISSUE THREAD

**Issue by benbusby** [benbusby/whoogle-search#2]
~~Probably~~ Definitely leave as false, but should offer the option to still see ads if desired.

**Comment by RainmakerRaw** [comment]
'Probably'? _Please_ don't implement this.

**Comment by benbusby** [comment]
Yeah that was just me thinking aloud, should've said "definitely". This came up in this discussion: https://www.reddit.com/r/selfhosted/comments/ggronz/whoogle_search_a_selfhosted/fq47w9e/?context=3

If it's an optional feature I personally don't see the problem, even though I'd never use the feature myself.

**Comment by benbusby** [comment]
Going to close this one for now, I've gotten a fair amount of private and public pushback for this -- though again, I don't see the problem personally if it's hidden behind a config setting. Other features/bugs are higher priority at the moment, but I'd welcome a pull request implementing this in a reasonable manner.
