### ISSUE TITLE
[BUG] Firefox autofocus not working properly

### ISSUE THREAD

**Issue by benbusby** [benbusby/whoogle-search#20]
**Describe the bug**
Autofocus of the search field on the main page was added in #16, but didn't seem to be working properly on Firefox (version 76, macOS).

**To Reproduce**
1. Go to the main page
2. Check to see if typing in the search bar is instantly accessible

**Expected behavior**
Search field should be focused on page load

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version 76

**Comment by raonetwo** [comment]
can confirm, doesn't work on Ubuntu 20.04 either.

**Comment by benbusby** [comment]
Closing this for now -- I can't get anything to work for autofocus. Adding `autofocus` to the input field doesn't work, adding focus scripting to the js controller, and manually triggering focus through js all don't work. At this point I'm inclined to think that this might be a weird Firefox issue, since it works fine on every other browser + OS combination I've tried. 

If someone comes across this and notices that it's something I've overlooked, please feel free to reopen.
