### ISSUE TITLE
[Bug] [Firefox] Selecting a text and dragging it to a new tab redirects to the homepage of whoogle-search

### ISSUE THREAD

**Issue by Flame-0** [benbusby/whoogle-search#203]
**Bug**
When selecting a text, and dragging it to a new tab, it will just be directed to the home page of whoogle-search instead of showing the results.

**Reproduce**
1. Select a text
2. Drag a selected text to a new tab

**Deployment Method**
- [Repl.it](https://repl.it/) ([one-click deploy](https://github.com/benbusby/whoogle-search#b-replit))

**Version of Whoogle Search**
- Latest build from [GitHub](https://github.com/benbusby/whoogle-search)
- Version [0.3.1](https://github.com/benbusby/whoogle-search/releases/tag/v0.3.1)

**Desktop Specifications**
 - OS: Windows 10 Pro | 20H2
 - Browser: [Firefox](https://www.mozilla.org/en-US/firefox/)
 - Version 85.02 and 87.0a1 [(Nightly)](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)

**Comment by benbusby** [comment]
This is actually a pretty weird bug. I can't tell what Firefox is trying to do, but as far as I can tell, no data is forwarded to the server (not even data with an unrecognized mimetype) when dragging text to a new tab. I'll keep looking into it, but just wanted to make that note in case anyone else stumbles across this issue.

**Comment by Flame-0** [comment]
Alternatively solution: The addon, [Add custom search engine](https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/), fixed my problem.

**Comment by benbusby** [comment]
It looks like the addon you recommended is probably the only solution at the moment. I haven't tracked down what exactly Firefox does behind the scenes when text is dragged to a new tab, but it isn't sending anything to the Whoogle server, so I assume it's something I can't fix on my end.
