### ISSUE TITLE
[BUG] [Firefox] cannot download search plugin from ... error 

### ISSUE THREAD

**Issue by lwndp** [benbusby/whoogle-search#207]
**Describe the bug**
I deployed Whoogle via heroku and now get the following error in FF: Firefox could not download the search plugin from: [my heroku url]

Is this a known issue? How can it be resolved?

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [0.3.1]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 85.0.2

**Comment by benbusby** [comment]
Hmmm, no I haven't seen this yet. Are you able to access `<your whoogle url>/opensearch.xml`? 

I just deployed the heroku beta version without any issues, could you try that? You can use [this link](https://heroku.com/deploy?template=https://github.com/benbusby/whoogle-search/tree/heroku-app-beta) to deploy the beta version.

**Comment by lwndp** [comment]
Hi Ben, thanks for the reply! I can indeed access the xml, also in Firefox. I deployed the beta you've linked, but the issue's still there.

However I guess I've found the issue: After deploying without user/pw authentication, it works. Is that a bug on my end or on application level?

**Comment by benbusby** [comment]
Ah, yeah that's on my end. I'm requiring authentication to reach the opensearch file (maybe I had a reason for that at some point, I can't think of one now though).

I'll push a fix shortly.

**Comment by benbusby** [comment]
Alright should be fixed now -- try redeploying the beta version and let me know if you encounter any issues (I validated the fix on my end, but just want to double check).

**Comment by lwndp** [comment]
@benbusby can confirm that it works now. Thanks for the quick fix, that's incredible!
