### ISSUE TITLE
[BUG] Adding Whoogle to Firefox Doesn't Work

### ISSUE THREAD

**Issue by Spearmintle** [benbusby/whoogle-search#212]
Description: When attempting to add Whoogle to Firefox, Firefox will respond with the message "Firefox could not download the search plugin from: https://whoogle.sdf.org/opensearch.xml". 

Reproduction: 
1. Use Firefox.
2. Go to whoogle.sdf.org
3. Attempt to add Whoogle as a search engine with the green plus sign next to the search bar.
4. Bug appears. 

- OS: Windows
- Browser: Firefox
- Version: 86 (latest)

**Comment by benbusby** [comment]
Someone set the root URL on their end to "httos" instead of "https". I just updated the configs for them since it's an easy enough fix (that anyone can do), but I don't typically get involved with issues on public instances.
