### ISSUE TITLE
[BUG] Inconsistent Semver docker tag format

### ISSUE THREAD

**Issue by FlipEnergy** [benbusby/whoogle-search#213]
**Describe the bug**
Please push docker images with consistent format of semver. The older ones don't have a `v` prefix, i.e. `0.1.2` but the newer ones do, i.e. `v0.3.1`.

Please either drop the `v` prefix, or have both tags available, i.e. `v0.3.1` and `0.3.1` for the same image.

Thanks!

**To Reproduce**
N/A

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by benbusby** [comment]
The `v` has been removed for current and future version builds. The only webhook I can easily retrigger is the one for `0.3.1` (latest tag), so that one is fixed on docker hub, but `0.3.0` should be the only one with the prefix now.
