### ISSUE TITLE
[FEATURE] Autocomplete in browser address bar

### ISSUE THREAD

**Issue by timsayshey** [benbusby/whoogle-search#214]
I'm using my Whoogle instance as my default search engine in Brave. However I no longer get autocomplete suggestions when quering via the address bar like I did with Google. Is it possible to add this type of functionality for Whoogle? Would be amazing! 

Example:
![image](https://user-images.githubusercontent.com/1148940/109831224-d7f80080-7c04-11eb-9282-863ea36256f0.png)

**Comment by benbusby** [comment]
This is already supported via the `/autocomplete` API route (see resultbelow). Are you able to pull logs from your server to see if queries are reaching that endpoint properly? 

![image](https://user-images.githubusercontent.com/33362396/109877829-7dc96080-7c41-11eb-8f76-51f843f98aa7.png)

**Comment by timsayshey** [comment]
Hi Ben,

I think the autocomplete endpoint is fine. 

I have the default search engine setup in Brave (see image). Am I missing something that needs to be configured in the browser?

![image](https://user-images.githubusercontent.com/1148940/109878550-09d78a00-7c3a-11eb-832a-a6a70b1a4b95.png)

**Comment by benbusby** [comment]
Ah I see. For any browsers -- mobile included -- where an opensearch template is not accepted (and the only option is to add a search query template for an engine) autocomplete/search suggestions cannot be supported. Unfortunately this is a problem on the browser's side, since it's on them to allow customizing engine resources beyond just basic search.

I can look into testing a few things out and see if there's a way to force Brave to download the opensearch file, but it may just be a limitation of the browser.

**Comment by almottier** [comment]
@timsayshey just found this option in Brave's advanced parameters. It was disabled by default. I now have autocomplete with Whoogle.

<img width="701" alt="Screenshot 2021-04-05 at 00 28 09" src="https://user-images.githubusercontent.com/5426740/113523102-23a41e00-95a6-11eb-9e15-b0bfa41c4a96.png">

**Comment by benbusby** [comment]
@timsayshey let me know if @almottier's solution doesn't work for you. I finally got around to installing Whoogle in Brave and can confirm that the above solution works for me as well, so I'm going to close for now (but please reopen if you have issues).

**Comment by timsayshey** [comment]
@benbusby @almottier - Yeah, so I already had that option enabled but it didn't help. I see autocomplete suggestions based off of my search history but I'm not seeing Whoogle Search auto complete suggestions, like if I type "how do I ..." it's not making any suggestions. @almottier Can you post a screenshot of search suggestions showing up? I didn't see that in your post.

**Comment by almottier** [comment]
here it is @timsayshey 

<img width="460" alt="Screenshot 2021-04-07 at 09 28 25" src="https://user-images.githubusercontent.com/5426740/113827537-b64de400-9783-11eb-88be-21cb833ea7c9.png">
