### ISSUE TITLE
[QUESTION] how to use Tor for Whoogle?

### ISSUE THREAD

**Issue by LorisTecnology** [benbusby/whoogle-search#215]
Use Tor: Unavailable

how to use Tor for Whoogle?

**Comment by benbusby** [comment]
Tor is marked as "Unavailable" if Whoogle is unable to connect to the Tor control port (9051) on the host machine. If you're running it on a machine you have access to, make sure Tor is working as expected apart from Whoogle first. If you're using a Docker version of the app, it should automatically start Tor within the container. 

That being said, there are currently lots of issues with exit nodes being blocked, so unless Tor is an absolute necessity I'd recommend using a proxy instead.

**Comment by LorisTecnology** [comment]
thanks for the answer
So i have to install tor?

**Comment by benbusby** [comment]
Yes

**Comment by LorisTecnology** [comment]
is there any guide to configure tor?
