### ISSUE TITLE
[FEATURE] Ability to specify Nitter/Invidious/Bibliogram instance to be used in configuration

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#219]
**Describe the feature you'd like to see added**
A short description of the feature, and what it would accomplish.

The "Replace Social Media Links" uses the instances of the above mentioned projects, which are sometimes rate limited or not working. So it would be useful if there is an option to change instances of above mentioned services from the configuration .

**Additional context**
![Screenshot_20210309-005239_Bromite_1](https://user-images.githubusercontent.com/37732050/110371060-7a373e80-8072-11eb-9df0-bcc23b64edfd.png)
![Screenshot_20210309-004907_Bromite](https://user-images.githubusercontent.com/37732050/110371073-7e635c00-8072-11eb-8d3f-72198eef96dc.png)

**Comment by benbusby** [comment]
These are already configurable as environment variables -- please see [the Environment Variables section of the readme](https://github.com/benbusby/whoogle-search#environment-variables).
