### ISSUE TITLE
[FEATURE] Add Libreddit to "Replace Social Media Links" for replacing Reddit links

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#220]
**Describe the feature you'd like to see added**
Libreddit is an alternative private front-end to Reddit, like Invidious is for YouTube and Nitter is for Twitter. More information about it can be found [here](https://github.com/spikecodes/libreddit).

**Comment by benbusby** [comment]
Duplicate of https://github.com/benbusby/whoogle-search/issues/172 -- libreddit is already available on the `develop` branch (and related Docker images).
