### ISSUE TITLE
[FEATURE] A bit more Google-like GUI

### ISSUE THREAD

**Issue by Bounty780** [benbusby/whoogle-search#221]
**Google-like GUI**
Seeing as this search engine is intended to be the CLOSEST to Google without all the tracking and privacy, I would suggest making it more Google-like, at least on desktop. The current theme appears to be a lot more mobile than it should be - everything is too centered. Maybe make the layout wider?

**Comment by benbusby** [comment]
Thanks for the recommendation. As I've mentioned a few other places now, the UI is not something I designed. The styling of the page is just what Google returns when performing a search query without Javascript. I'm not a UI designer (plus I like the current UI anyways, so I'm probably not the right person for this undertaking) but I'm happy to accept PRs from anyone who can figure out a better solution. 

Ultimately it should be customizable per user, so I'm closing this as an extension of #60.
