### ISSUE TITLE
[QUESTION] Getting past captcha

### ISSUE THREAD

**Issue by wazlecracker** [benbusby/whoogle-search#222]
I use whoogle on Arch Linux via the whoogle-git AUR package through a VPN and I am getting the 
> Our systems have detected unusual traffic from your computer network. This page checks to see if it's really you sending the requests, and not a robot.

If I manually go to google I can solve the captcha, but it does not resolve the block going through my whoogle since the captcha itself doesn't appear. How do i fix this?

**Comment by benbusby** [comment]
Unfortunately there's not an easy way to get past this at the moment, and VPNs are particularly susceptible to getting blocked by Google.

This has been brought up in #211, but that would apply more to public instances only. I'll keep that issue updated with solutions moving forward.

**Comment by wazlecracker** [comment]
Gotcha, thanks for the info!
