### ISSUE TITLE
feature request: output http error code if searching has been ratelimited.  

### ISSUE THREAD

**Issue by fres7h** [benbusby/whoogle-search#226]
basically, since i run a public instance, i'd love to be able to check if the instance is ratelimited by checking http status using curl or something like that. it's not very important, but it'd be nice.

**Comment by benbusby** [comment]
Just to clarify, would an endpoint like `<whoogle instance>/test` returning a 4XX code if searches are blocked work for you? That should be pretty easy to do, I'll try to add that in soon.

**Comment by fres7h** [comment]
yeah, it would work perfectly. i whipped up a tiny shell script that achieves the same goal, but http codes would be much nicer. 
`#!/bin/bash
if curl -L https://whoogle.himiko.cloud/search?q=test | grep "Our systems have detected" > /dev/null; then
	sed -i '/instance has been ratelimited, come back later./d' /opt/whoogle/whoogle-search/app/templates/index.html &&
	sed -i '//a<h3>instance has been ratelimited, come back later.</h3>' /opt/whoogle/whoogle-search/app/templates/index.html && systemctl restart whoogle &&
	exit
else
	sed -i '/instance has been ratelimited, come back later./d' /opt/whoogle/whoogle-search/app/templates/index.html && systemctl restart whoogle &&
	exit
fi`

**Comment by benbusby** [comment]
So searches that are blocked by captcha now return a `503` error. It uses the same `/search` endpoint since a search is required to test for captcha anyways, but should be straightforward to use still.

i.e. `<blocked whoogle url>/search?q=test -> 503` vs `<not blocked whoogle url>/search?q=test -> 200`.

**Comment by fres7h** [comment]
sweet, thanks man. i wish i knew python better so i could actually help do some stuff lol
