### ISSUE TITLE
[QUESTION] Setup language, Dark

### ISSUE THREAD

**Issue by shimuldn** [benbusby/whoogle-search#228]
My Docker own build instance is showing wired language.
Is there any way I can set Language, Dark and near by default? or maybe system args?
I am using systems to autorun on startup.

Thanks

<img width="951" alt="Screenshot 2021-03-20 at 3 34 34 AM" src="https://user-images.githubusercontent.com/12117121/111847440-cade4f80-892e-11eb-940a-56c81fada470.png">

**Comment by benbusby** [comment]
There's not currently a way to set the config settings through environment variables, but I'll look into adding that.

**Comment by benbusby** [comment]
Now configurable with environment variables, [see the updated documentation](https://github.com/benbusby/whoogle-search#config-environment-variables).
