### ISSUE TITLE
Firebase Deploy

### ISSUE THREAD

**Issue by ivankazzzz** [benbusby/whoogle-search#23]
Thanks sir for you great project ! 
i really love it !

can you provide a way to deploy to firebase sir ? 

and also when i searching gmail and click it it nothing happen

thanks

**Comment by benbusby** [comment]
Thanks for your kind words! I'll look into Firebase support, although that might not be implemented for a while. 

Regarding your gmail issue, it looks like for some reason Google returns the gmail link as "google.com/gmail", which is rewritten to "<your whoogle search url>/gmail" on the results page. I'll make a note of that and try to address it soon.

**Comment by benbusby** [comment]
Merged into #62, I'd rather not keep track of everyone's preferred deployment methods on an issue-by-issue basis.
