### ISSUE TITLE
[BUG] Running with Docker VPN stack & Proxy fail

### ISSUE THREAD

**Issue by hakarune** [benbusby/whoogle-search#240]
**Describe the bug**
added this to my Docker VPN stack (NordVPN VPN network) and it doesn't load, says doesn't exist on port 5000. Looking at logs says deployed on 0.0.0.0:50000 (same as running outside stack).  All other containers inside stack work as normal with concealed VPN IPs.

Tried running with NordVPN socks5 proxy and it gives a bunch of errors. [NordVPN Settings](https://support.nordvpn.com/Connectivity/Proxy/1049258992/Proxy-setup-on-Deluge.htm)

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/local/lib/python3.8/site-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/usr/local/lib/python3.8/site-packages/socks.py", line 496, in _SOCKS5_request
    auth_status = self._readall(reader, 2)
  File "/usr/local/lib/python3.8/site-packages/socks.py", line 276, in _readall
    d = file.read(count - len(data))
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer`

**To Reproduce**
Steps to reproduce the behavior (PROXY):
 whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle
    ports:
        - 5000:5000
    volumes:
        - /home/user/.config/whoogle:/config
    environment:
        - WHOOGLE_PROXY_USER=XXXXX
        - WHOOGLE_PROXY_PASS=XXXXX
        - WHOOGLE_PROXY_TYPE=socks5
        - WHOOGLE_PROXY_LOC=us.socks.nordhold.net
    restart: unless-stopped

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Debian]
 - Browser [Brave]
 - Version [newest]

**Additional context**
I can connect to Whoogle docker terminal and it's running and giving same ip ping info back as all other containers in the stack and has internet connection.

**Comment by benbusby** [comment]
I'm not sure what the problem could be here. Your exact set up is working fine for me (including the NordVPN proxy to the same address), so I'm not sure I have a good or useful recommendation without seeing everything else about your container. 

Could you clarify what you mean when saying it "doesn't exist on port 5000"? Do you just mean that the browser is giving an "Unable to connect" error or something?

**Comment by benbusby** [comment]
Closing for now since I'm not sure how to move forward with debugging (and am going through issues trying to clean everything up), but please feel free to reopen if you are still encountering this issue. I'd still like to help!
