### ISSUE TITLE
Whoogle in Firefox omnibox as a search engine

### ISSUE THREAD

**Issue by EmTeeAge** [benbusby/whoogle-search#244]
**Describe the bug**
Not sure whether my question doesn't make sense or is irrelevant, in that case, feel free to close it.
How is Whoogle supposed to work like as an engine in Firefox Desktop? 

I would imagine that it would work like other search engines - You start typing query into the address bar at the top and once you press enter, it takes you to the result page of the search engine. However, what happens in my case is that it only takes me to the main Whoogle page and I have to type in the search query again into the Whoogle site - is this how that's supposed to be? If not, is there anything I could try to fix it? Thank you very much.

**To Reproduce**

1. Add Whoogle as a default search engine in Firefox.
![image](https://user-images.githubusercontent.com/67438185/112991894-f0a5f880-9167-11eb-8d71-72380d51298a.png)
2. Try searching for something from the top bar and press enter 
![image](https://user-images.githubusercontent.com/67438185/112992466-7aee5c80-9168-11eb-8312-de0ede437797.png)
3. After submitting the query, briefly flashes [mydomain]/search, which then changes immediatelly to [mydomain] only
4. You get taken to the main page, without the query you submitted.
![image](https://user-images.githubusercontent.com/67438185/112992560-8f325980-9168-11eb-834b-1593b4b13253.png)

**Deployment Method**
- [X] Other: [describe setup]
- Installed using manual method, behind Nginx proxy server with the following configuration:
```
server {
    listen 80 default_server;
    server_name [mydomain];
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name [mydomain];

    location / {
        include /etc/nginx/proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }

    ssl_dhparam /etc/nginx/dhparam.pem;
    ssl_certificate /etc/letsencrypt/live/[mydomain]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[mydomain]/privkey.pem;
    ssl_session_timeout 10m;
    ssl_session_cache shared:SSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # modern configuration
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;
}
```
proxy_params are following:
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Version of Whoogle Search**
- [X ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)

**Desktop:**
 - OS: Windows 10 20H2
 - Browser: Firefox
 - Version: 87.0

**Additional context**
I suppose it may have somthing to do with my Nginx configuration to the upstream Whoogle server. Can someone who doesn't use Nginx perhaps try this out on their end or suggest what should I try?

Thank you very much.

**Comment by benbusby** [comment]
I vaguely recall this issue coming up in the past someone else's reverse proxy. Could you let me know if `Root URL` in your config is set to your domain name or localhost? If it's set to localhost, could you try updating that to your full domain name and see if that changes anything with your issue?

**Comment by EmTeeAge** [comment]
Thanks for the tip, however I'm not sure exactly what to change where (for some reason I can't even remember setting my domain anywhere in Whoogle). When I open up the site in a different browser or a private windows and check "Configuration" on the main page, my domain is there, however with http instead of https. Perhaps that could be the issue, since I have a permanent redirect from http to https set in Nginx? The Whoogle service is started using systemd unit file like this:
![image](https://user-images.githubusercontent.com/67438185/113634181-9d9fda00-966e-11eb-8117-f55a49d73509.png)

Should I just uncomment Environment=WHOOGLE_DOTENV=1 and edit the whoogle.env file like this?
![image](https://user-images.githubusercontent.com/67438185/113634306-d344c300-966e-11eb-96c1-599457bf7418.png)

**Comment by benbusby** [comment]
> What I assume could have happened is that I added Whoogle to Firefox before putting Nginx in front of it and after I installed Nginx, I only re-added Whoogle to Firefox, but haven't cleaned the site data and cookies

Yes, the situation you're describing could definitely cause the buggy state that you were initially seeing. The whole opensearch template dance with Whoogle is a little clunky, but thankfully once it's working, it doesn't need reconfiguring again. 

> Also, thanks for this project as a whole, incredible piece of software :)

Thank you for the kind words! I really appreciate it.
