### ISSUE TITLE
[BUG] <whoogle not Opening in Tor Browser>

### ISSUE THREAD

**Issue by iamkishorekumar-git** [benbusby/whoogle-search#245]
**Describe the bug**
I'm trying to open Whoogle Search Engine in chrome, it works fine but when i tried to run in TOR browser show like "Unable to connect"

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the TOR Browser
2. Enter the URL then click Enter

![Tor_Browser](https://user-images.githubusercontent.com/55937175/113004432-39be7280-9191-11eb-9324-a31f30839965.png)

3. But It Work in chrome browser
![chrom_browser](https://user-images.githubusercontent.com/55937175/113005068-c10be600-9191-11eb-933d-49fabda302ed.png)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser TOR
 - Version 10.0.15

**Comment by benbusby** [comment]
I'm pretty sure Tor browser restricts access to localhost as a security measure. You should set up an externally accessible host if you want to access Whoogle from within Tor browser.

**Comment by iamkishorekumar-git** [comment]
Okay thanks , How can we do that ? any Documentation ? If there please share
