### ISSUE TITLE
[BUG] "The page isn’t redirecting properly" after heroku quick deploy

### ISSUE THREAD

**Issue by trumad** [benbusby/whoogle-search#252]
**Describe the bug**
Firefox shows "The page isn’t redirecting properly", and Chrome shows "mackfindus.herokuapp.com redirected you too many times." when using my heroku instance (https://mackfindus.herokuapp.com/)

**To Reproduce**
1. Go to https://mackfindus.herokuapp.com/
2. Note the browser error

**Deployment Method**
- [ X ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ X ] Not sure (the beta version)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox & Chrome
 - Latest

**Smartphone (please complete the following information):**
 - Device: Motorola G9
 - OS: Android 10
 - Browser: Iceraven (firefox fork for Android)
 - Version: Latest

**Additional context**

I deleted my original heroku app to deploy the beta version from scratch on the same appname/subdomain, to try to fix https://github.com/benbusby/whoogle-search/issues/249. I just left the default options as they were, and it deployed successfully, but now it's redirecting in a loop. I also installed two brand new instances using the heroku quick deploy button on https://github.com/benbusby/whoogle-search/tree/heroku-app-beta and they are behaving the same way. I installed an EU and a US version. I tried clearing cookies, and I tried adding the CONSENT cookie manually, but neither helped. I'm pretty sure the CONSENT cookie doesn't need to be added client-side on the heroku webpage, but I was desperate!

**Comment by Hunam6** [comment]
https://github.com/benbusby/whoogle-search/issues/243#issuecomment-811773944

**Comment by trumad** [comment]
My workaround for this is to deploy an old version on a US heroku instance, using this quick deploy link: https://heroku.com/deploy?template=https://github.com/benbusby/whoogle-search/tree/heroku-app

**Comment by benbusby** [comment]
Fixed now on `heroku-app-beta`
