### ISSUE TITLE
[QUESTION] Separate "search language" from "interface language" in "WHOOGLE_CONFIG_LANGUAGE" ?

### ISSUE THREAD

**Issue by askabaz22** [benbusby/whoogle-search#260]
Is it possible to have two divided variable, one for _Search language_ and the other for _Interface language_?

**Comment by benbusby** [comment]
Fixed now -- search language is `WHOOGLE_CONFIG_SEARCH_LANGUAGE`, interface language is still `WHOOGLE_CONFIG_LANGUAGE`.
