### ISSUE TITLE
[BUG] Heroku EU cookie fix not abvailable for Heroku(?)

### ISSUE THREAD

**Issue by github-ronk** [benbusby/whoogle-search#261]
Hi,

Thanks for the fix.

It seems both of the Heroku branches are still on [version 0.3.1](https://github.com/benbusby/whoogle-search/blob/heroku-app-beta/app/__init__.py), so the fix cannot be click-deployed to Heroku?

**Comment by IniUe** [comment]
Tap that button https://github.com/benbusby/whoogle-search#a-heroku-quick-deploy

**Comment by github-ronk** [comment]
> Tap that button https://github.com/benbusby/whoogle-search#a-heroku-quick-deploy

Thanks, but that button points to the heroku-app-beta branch, which is apparently still on 0.3.1 .

**Comment by IniUe** [comment]
> Thanks, but that button points to the heroku-app-beta branch, which is apparently still on 0.3.1 .

But you'll not regret for now :smile:

**Comment by benbusby** [comment]
`heroku-app-beta` was just missing the update to the actual version number, `heroku-app` was missing 0.3.2 entirely. Both are fixed now.

**Comment by github-ronk** [comment]
Great, thanks Ben :)
