### ISSUE TITLE
[QUESTION] Autocomplete on Chrome

### ISSUE THREAD

**Issue by almottier** [benbusby/whoogle-search#263]
Hello, I am setting up Whoogle on Chrome. I added the search engine successfully but I noticed I lost autosuggestions from the Chrome search bar. Is it possible to get it working ?
Thanks

<img width="589" alt="Screenshot 2021-04-05 at 00 08 34" src="https://user-images.githubusercontent.com/5426740/113522739-66182b80-95a3-11eb-9e1a-4fa28aca7139.png">

**Comment by benbusby** [comment]
I haven't tried with stock Chrome, but with Chromium the search suggestions are working alright

![image](https://user-images.githubusercontent.com/33362396/113636695-ffe1e600-9640-11eb-9b63-75dbb699fa00.png)

When you added Whoogle to Chrome, did you manually add the search engine (i.e. entering `<your whoogle url>/search?q=%s`? Or was the engine automatically added to your list of search engines when visiting your Whoogle URL for the first time?

**Comment by maaAnandsheela** [comment]
can confirm the same issue i use ungoogled chromium and added the search engine manually.

**Comment by benbusby** [comment]
For adding the search engine manually, there isn't a way to get autocomplete to work. Essentially by adding the search engine by hand, the browser doesn't bother looking for any other relevant endpoints in whoogle's `opensearch.xml` file (which contains the search suggestion/autocomplete endpoint). 

Unfortunately there isn't a confirmed way to get Chromium based browsers to automatically add the engine itself, including the autocomplete feature. About half the time it works just by visiting the Whoogle instance's home page, and then it will just appear in the list of search engines without any indication. It's an annoying quirk of Chromium browsers that seemingly isn't well documented, and is out of my control. 

@almottier I'm going to close this for now unless the engine was in fact added automatically by your browser, in which case that could be an issue with the whoogle opensearch template.
