### ISSUE TITLE
[BUG] "/bin/sh: 1: ./run: not found" and Whoogle won't start in docker

### ISSUE THREAD

**Issue by ilovepancakes95** [benbusby/whoogle-search#265]
**Describe the bug**
Was running beta tag docker image for the past few weeks just fine. I downloaded the newest beta image from docker hub and restarted the container using the newest image download and Whoogle won't start and I get the following in docker logs:

`/bin/sh: 1: ./run: not found`

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest BETA build from Docker Hub
- [ ] Version [version number]
- [ ] Not sure

**Comment by benbusby** [comment]
Testing with:

```bash
docker pull benbusby/whoogle-search:beta
docker run --publish 5000:5000 --name whoogle-search benbusby/whoogle-search:beta
```

doesn't seem to cause any issues. Can you give me the exact commands you're using to update/launch/etc so that I can try to replicate it some other way?

**Comment by ilovepancakes95** [comment]
Thanks for the quick reply. I am running it via Portainer and the only change I made was to download the beta tag image from DockerHub and restart the container that was working with previous beta image with the latest beta image.

**Comment by benbusby** [comment]
Hmmm, running via Portainer isn't causing any problems for me either. Are you able to run using any of the other image tags? The `latest` and `beta` images should be equivalent as of the latest release.

**Comment by ilovepancakes95** [comment]
If I use `latest` and start a fresh container, whoogle loads finally (must have been something bad in config of old container that conflicted with new version of whoogle). BUT, I still get a bunch of the below in the logs.

```

INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"


DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)


DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0004)


INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"


DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0002)


INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"


DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0002)


INFO:stem:Error while receiving a control message (SocketClosed): received exception "[Errno 9] Bad file descriptor"
```

**Comment by eddydc** [comment]
Hi,
I'm having the same issue on my synology. Tried to start via SynDocker and Portainer. Always getting
/bin/sh: 1: ./run: not found
/bin/sh: 1: config/tor/start-tor.sh: not found
Any suggestion on how to fix this?
Cheers,
Eddy

**Comment by ilovepancakes95** [comment]
> Any suggestion on how to fix this?

By chance, did you try to make a fresh container? My issue was resolved by creating a new container for the latest whoogle image I pulled from DockerHub.

**Comment by eddydc** [comment]
> 
> By chance, did you try to make a fresh container? My issue was resolved by creating a new container for the latest whoogle image I pulled from DockerHub.

I tried the recreate option from portainer with the pull latest image option selected, which didn't make any difference

**Comment by eddydc** [comment]
> By chance, did you try to make a fresh container? My issue was resolved by creating a new container for the latest whoogle image I pulled from DockerHub.

It seems that deleting and reinstalling the latest image does the tick indeed. I hope that I don't have to do this each time a new version is available. All my images are auto updated with Ouroboros

**Comment by ilovepancakes95** [comment]
> I hope that I don't have to do this each time a new version is available.

I have been using Whoogle since the week it was released and this is the first time I couldn't simply reload the container for an update to latest image. There must be something not compatible with the original container config the way it is created, when using the latest image.

With that being said, now that your Whoogle loads, do you get the same log errors I posted above (read of closed file errors)?

**Comment by eddydc** [comment]
> With that being said, now that your Whoogle loads, do you get the same log errors I posted above (read of closed file errors)?

Yes, the same for me. A multitude of:
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): empty socket content
...
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"

**Comment by benbusby** [comment]
The "INFO/DEBUG:stem" errors can be ignored. They seem to be mostly benign warnings from the Python library that I'm using to communicate with the Tor socket. I don't know why it's so verbose by default -- I'll look into disabling logging for that library. 

Regarding the Docker issues, the one major change that might've affected the builds was switching to a multi-stage container build, but that should've been caught a long time ago (originally pushed to `develop` back in February), so I'm skeptical that this could've been the issue unless it was a fairly stale image.

**Comment by ilovepancakes95** [comment]
> unless it was a fairly stale image

This could be it for me then, since I believe last time I had the image pulled before the update yesterday was in early February.

**Comment by benbusby** [comment]
Ah okay, yeah that could've been the issue. Although I do find it strange that it took until now for anyone else to report it. In any case, I don't foresee any major changes to the Dockerfile moving forward, so I'm going to assume this was just a one time setback. I'll close the issue for now, and I apologize for any inconvenience this may have caused!

**Comment by ilovepancakes95** [comment]
> Ah okay, yeah that could've been the issue. Although I do find it strange that it took until now for anyone else to report it. In any case, I don't foresee any major changes to the Dockerfile moving forward, so I'm going to assume this was just a one time setback. I'll close the issue for now, and I apologize for any inconvenience this may have caused!

Not a problem at all, thanks. Didn't even think to try a fresh container because was trying to imagine what would even cause that in first place.
