### ISSUE TITLE
[BUG] Captcha request on every page

### ISSUE THREAD

**Issue by federicotorrielli** [benbusby/whoogle-search#277]
**Describe the bug**
This page is now showing every time.
![image](https://user-images.githubusercontent.com/31370059/114263262-c6183300-99e4-11eb-8ae1-9c55665ca12c.png)

**Deployment Method**
- [X] Heroku (one-click deploy) --> Europe server
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by guneydoganer** [comment]
I can confirm I'm seeing this now as well. Also deployed to Heroku and with the latest build.

**Comment by guneydoganer** [comment]
@federicotorrielli you might want to edit your/server IP address out of the image ;).

**Comment by federicotorrielli** [comment]
> @federicotorrielli you might want to edit your/server IP address out of the image ;).

It's heroku, it's a public one ;)

**Comment by github-ronk** [comment]
Yes, same behavior here.
Until this is resolved, we can try the other Heroku zone (EU vs US) or maybe Repl.it .

**Comment by benbusby** [comment]
This isn’t a Whoogle bug. Whoogle isn’t guaranteed to always circumvent Google’s captcha flag. For Heroku, there’s [this script](https://github.com/benbusby/whoogle-search/blob/cb80c181a6129459a6aeae61e882580c0f7ac084/misc/heroku-regen.sh) to quickly regenerate your Heroku instance. I run that in a cronjob that checks for a captcha and rebuilds the image, and that’s always worked for me. 

There’s #211 for adding support for anti-captcha services, but I believe that would only apply to public instances.
