### ISSUE TITLE
[BUG] WHOOGLE_CONFIG_STYLE & WHOOGLE_CONFIG_SAFE doesn't work

### ISSUE THREAD

**Issue by randomnameforgithub** [benbusby/whoogle-search#279]
**Describe the bug**
Docker's WHOOGLE_CONFIG_STYLE and WHOOGLE_CONFIG_SAFE doesn't work. Doesn't change the css and safe search settings.

**To Reproduce**
1. Using the default docker compose but changed the css. I used my own cusom css but for simplicity sake, the following also didn't work:

```
    environment:
      - PUID=102
      - PGID=102
      - WHOOGLE_DOTENV=0
      - WHOOGLE_CONFIG_URL=*secret*
      - WHOOGLE_CONFIG_COUNTRY=*secret*
      - WHOOGLE_CONFIG_LANGUAGE=*secret*
      - WHOOGLE_CONFIG_SAFE=0
      - WHOOGLE_CONFIG_DARK=1 
      - WHOOGLE_CONFIG_STYLE=":root{--whoogle-dark-logo:#fff;}"
```

2. Go to whoogle and the css doesn't change. Safe search is on.

**Deployment Method**
- Docker

**Version of Whoogle Search**
- Latest from docker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, chrome

**Smartphone (please complete the following information):**
 - Tested also on iphone safari

**Additional context**

Not really any error in the docker logs, maybe this:
```
I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6649, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
```

I can set the css using the  "Custom CSS" field on the home page, which only persist for the particular browser that I'm using.

Maybe it'd be easier if there is a way to mount config.json?

**Comment by benbusby** [comment]
Thanks for pointing this out -- I just pushed a fix (baa7a87efb970a5db277c9905f2e4b881912c514), which will be available in `latest` and `beta` images once the build finishes. 

Mounting config.json is possible (see discussion on #31). I'll update the readme with info on how to do that.
