### ISSUE TITLE
[QUESTION] How to update herokuapp to new whoogle version via web?

### ISSUE THREAD

**Issue by itsnotsaved** [benbusby/whoogle-search#280]
See the title so i am asking how to do it via herokuweb without delete the app

**Comment by benbusby** [comment]
Other users have had luck with [the steps here (under Alternative Solution)](https://github.com/benbusby/whoogle-search/wiki/Updating-a-Heroku-Quick-Deploy-Instance#alternative-solution). I haven't tried it myself. I delete and regenerate heroku apps using the [heroku-regen.sh](https://github.com/benbusby/whoogle-search/blob/cb80c181a6129459a6aeae61e882580c0f7ac084/misc/heroku-regen.sh) script.
