### ISSUE TITLE
[QUESTION] Can we add custom replacement url for instagram/youtube links ?

### ISSUE THREAD

**Issue by AngeloFrangione** [benbusby/whoogle-search#282]
Hi, i'm self-hosting whoogle-search, and also want to self host bibliogram and invidious, but how could I change the replacement hosts urls ? maybe there is a setting ? I'm using the docker.

**Comment by gripped** [comment]
https://github.com/benbusby/whoogle-search#environment-variables

**Comment by gripped** [comment]
And if you want to self host Bibliogram it will have to be on a residential IP address, does not work well at all in the cloud, vps etc. Instagram block them.

**Comment by AngeloFrangione** [comment]
Thank you for your help !
