### ISSUE TITLE
[FEATURE] Autocomplete in a web browser

### ISSUE THREAD

**Issue by David-Nahorniak** [benbusby/whoogle-search#283]
Hi, I don't know if this feature exists or not.

Can I set suggest in the browser?

I see this option in the firefox plugin "Add custom search engine", but I couldn't run it with the default "suggestions?q={searchTerms}".
![obrazek](https://user-images.githubusercontent.com/44706421/114319032-fd373300-9b0f-11eb-9b37-68c3d81b05f8.png)

Is this feature available or not?
Could you please give instructions on how to set everything up in this plugin so that everyone can fully integrate whoogle and firefox search?

**Comment by benbusby** [comment]
The suggestion endpoint is `/autocomplete?q={searchTerms}`, not `/suggestions...`. I'll update the readme.
