### ISSUE TITLE
[BUG] Google flags Heroku instance as bot

### ISSUE THREAD

**Issue by lwndp** [benbusby/whoogle-search#285]
**Describe the bug**
Google flags Heroku instance as bot and captcha does not show in Whoogle interface.

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [0.4.0]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.22.71

**Comment by benbusby** [comment]
Not a bug, just an unfortunate limitation of Whoogle (and pretty much any Google proxy apps). There's an issue open for supporting anti-captcha tools (#211), but that would mostly only apply to public instances. In the meantime you can try destroying and rebuilding heroku apps to get a new IP address, either manually or using the [heroku-regen.sh script](https://github.com/benbusby/whoogle-search/blob/main/misc/heroku-regen.sh).
