### ISSUE TITLE
[FEATURE] Let the iBangs !i, !v, and !n go to Whoogle's own image, video and news search

### ISSUE THREAD

**Issue by alkarkhi** [benbusby/whoogle-search#289]
**Describe the feature you'd like to see added**
Right now the iBangs !i, !v, and !n goes to duckduckgo. This is not bad but i think it should be better to integrate them with whoogle instead. And besides, image, video and news search isn't available with duckduckgo when javascript is off.

**Comment by DUOLabs333** [comment]
The bangs come directly from DDG, so it's going to point to them. We would have to do some `.replace`, once downloaded.

**Comment by Starmann** [comment]
A potential better solution might be just having multiple bang files. One for DDG, one for Whoogle's own modifications, and one for user configs or something.

**Comment by luv2code** [comment]
I would like to define custom bangs. Specifically, I'd like a bang for kagi
