### ISSUE TITLE
[FEATURE] Clear contents of search box

### ISSUE THREAD

**Issue by milachevalier** [benbusby/whoogle-search#291]
**Describe the feature you'd like to see added**
Would it be possible to add a x button to clear the contents of the search box so it would be easier to do a fresh search on mobile? 

**Additional context**
<img width="730" alt="screenshot-whoogle" src="https://user-images.githubusercontent.com/82845078/115326131-67a04100-a1aa-11eb-9770-9c0760f12bcf.png">

**Comment by benbusby** [comment]
Thanks, I've been meaning to add this for a while. Fixed in https://github.com/benbusby/whoogle-search/commit/01fe0c02a50b2fddd3bbdb03f5ef88019b413d2a.

**Comment by milachevalier** [comment]
Is it possible to tweak the code so that the text field is in focus after clicking the x? Saves the extra click for a new search.

Nevertheless amazing work so far, you've really gone above and beyond.

**Comment by benbusby** [comment]
Good thinking, I just added that as well. Thanks for the kind words!
