### ISSUE TITLE
[QUESTION] Hosting next to pihole instance

### ISSUE THREAD

**Issue by MGThePro** [benbusby/whoogle-search#296]
So I'm hosting a pihole instance on my pi4 which I intend to host whoogle on, so I already have one webinterface running at all times. I'm assuming that's why whoogle defaults to port 5000 rather than port 80. If I manually set port 80 I get a permission denied error. The site isn't accessible from port 5000 either, I'm just getting a connection refused error. Optimally I would have whoogle accessible from its own path (like 127.0.0.1/whoogle), but I'm not exactly sure how I would set that up.

**Comment by benbusby** [comment]
> The site isn't accessible from port 5000 either,

How are you accessing the site? On my pihole I'm able to access the Whoogle using the local IP directly (i.e. `192.168.0.XX:5000`) or updating `/etc/hosts` to add a shortcut for that device. You could also set up a reverse proxy, such as nginx, on the pi to achieve something similar to what you're looking for, but there are better resources online than what I could provide in a brief rundown here. 

If it's inaccessible through the `<Pi IP>:5000` method, then the next step of debugging would be to ensure the service is actually running as expected. You could run `curl 0.0.0.0:5000` from the Pi to make sure the web page is coming back correctly.

**Comment by MGThePro** [comment]
Thanks for the reply!
> How are you accessing the site?

I got the connection refused error using curl with the pi's ip and port from my machine (both on a local network)

> You could run curl 0.0.0.0:5000 from the Pi

strangely, this is actually working. 
This seems to me like some sort of firewall thing, but I just told iptables on the pi to allow any incoming connections (since I don't have any open ports in my router anyways) and it still doesn't work on my machine

**Comment by benbusby** [comment]
I'm going through and clearing out older issues, so I'm going to close this one as it sounded like a firewall config issue. Let me know if I can help further with anything else!
