### ISSUE TITLE
[QUESTION] whoogle.env on Synology

### ISSUE THREAD

**Issue by Chris122AT** [benbusby/whoogle-search#302]
Hi there, 

how can I use the file whoogle.env persistant on a Synology NAS?

I tried to set -v [volumeX/path_to/]whoogle.env:/whoogle.env and set -e WHOOGLE_DOTENV=1.
So the file should be mounted. But after _docker start whoogle_ it doesn't affects whoogle's configuration. 

Thank you for your help!

Chris

**Comment by benbusby** [comment]
It's probably better to just use [`--env-file ./whoogle.env`](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) (or `-e ./whoogle.env`) to load the `whoogle.env` file. 

That should work better than mounting directly, but let me know if you are still encountering any problems with that approach!
