### ISSUE TITLE
[BUG] Last letter of search query gets removed from search box

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#306]
**Describe the bug**
Last letter of search query gets removed in result page textbox.

**To Reproduce**
1. Enter search query
2. Check result
3. See error

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Smartphone (please complete the following information):**
 - Device: Lenovo X304L
 - OS: Android
 - Browser: Bromite
 - Version: 90.0.4430.204

**Additional context**
![Screenshot_20210508-012137_Bromite_1](https://user-images.githubusercontent.com/37732050/117502261-e2d06800-af9c-11eb-8cea-beb8151a8612.png)
![Screenshot_20210508-012151_Bromite_1](https://user-images.githubusercontent.com/37732050/117502264-e49a2b80-af9c-11eb-99a3-541130bec756.png)

Query appearing correct in result but in search box last letter of query is missing.

**Comment by LivingWithHippos** [comment]
I have this issue this with the docker version. The post call to search has the correct words. I've noticed there's a new release on dockerhub from 18 hours ago. Manually setting the tag to 0.4.1 fixed it in the meanwhile. I took a quick look at the commits after 0.4.1 but I'm not familiar with the codebase

**Comment by eddydc** [comment]
It seems that I have the same issue, having the lastest docker image (seems to be 0.4.1).

**Comment by LivingWithHippos** [comment]
> It seems that I have the same issue, having the lastest docker image (seems to be 0.4.1).

The issue is with the latest tag, it points  to a newer release than 0.4.1. Change the tag to 0.4.1 to fix it while it gets fixed. You can check the releases [here](https://hub.docker.com/r/benbusby/whoogle-search/tags?page=1&ordering=last_updated)
