### ISSUE TITLE
[FEATURE] Option to remove related searches from result

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#307]
**Describe the feature you'd like to see added**
An option in config to remove related searches from result page.

**Additional context**
![Screenshot_20210508-022047_Bromite_1](https://user-images.githubusercontent.com/37732050/117507333-7d807500-afa4-11eb-98ef-903b29a2e4a3.png)

**Comment by benbusby** [comment]
Thanks for the recommendation -- fixed with afd01820bbb859d86938abb0b55ac7df96278d8a. Available on `main` and `develop` branches, as well as `latest` and `beta` images on Docker Hub shortly.

The section should now be collapsed by default (no config changes needed).
