### ISSUE TITLE
Configurable config.json location

### ISSUE THREAD

**Issue by FoxxMD** [benbusby/whoogle-search#31]
**Describe the feature you'd like to see added**
`static/config.json` is used to set the main configuration settings for whoogle. However when the docker container is rebuilt these settings are lost.

Please modify the location of `config.json` so that it is easier for docker users to provide a volume-mounted copy to the container so we can persist our settings between rebuilds.

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**

### Minimal changes to achieve this

Move `config.json` into its own folder **outside** of static, preferably to a location that does not need other files to be written to it. Additionally make sure whoogle does not overwrite this directory/file if it already exists at setup.

With a hardcoded, but separate, directory a docker user can easily volume-mount a folder to that location and provide their own `config.json`.

### Optionally 

Expose the configuration directory string as an environmental variable in the Dockerfile so users can set their own directory.

**Comment by benbusby** [comment]
Mind trying out the feature/config-volume branch in #39 and see if I'm missing anything missing? I believe that update will satisfy this request. Seemed to be working pretty well for me, if it looks good to you then I'll merge.

**Comment by FoxxMD** [comment]
Looks good to me too! Could you possibly publish the branch as a tag on dockerhub? That's how I'm running it (in unraid) right now and would make it like 10 seconds to test it for me 😅

**Comment by benbusby** [comment]
Available under the `config-volume` tag on dockerhub now. Let me know if it works for you!

**Comment by r0arkin** [comment]
I just pulled this container and the config saves to the directory that I specified.

**Comment by FoxxMD** [comment]
@benbusby it works! thank you!!

@r0arkin that would be the case regardless of this change though.

**Comment by r0arkin** [comment]
> @benbusby it works! thank you!!
> 
> 
> 
> @r0arkin that would be the case regardless of this change though.

That is very true!  I just thought about it.

**Comment by xnaas** [comment]
Any plans to push this to `:latest` on Docker Hub or will this be the branch to permanently follow for this change?

**Comment by FoxxMD** [comment]
p.s. ben you can setup automated builds based on branch in dockerhub 
![image](https://user-images.githubusercontent.com/4663766/81953433-a6f70280-95d5-11ea-8c51-ed5a6cd7746c.png)
