### ISSUE TITLE
[FEATURE] display the URL needed to add Whoogle as a browsers default search engine in the configuration section..

### ISSUE THREAD

**Issue by r4dian** [benbusby/whoogle-search#312]
**Describe the feature you'd like to see added**
To use a search engine by default in a Chromium based browser you need the be able to enter the `URL with %s in place of query`

**Additional context**
The required URL is `https://domain.tld/search?q=%s` but this is only discoverable by viewing the page source.

**Comment by benbusby** [comment]
I've updated the README to be a bit more clear about how to add the search engine to Chromium based browsers. Thanks for bringing this to my attention!

**Comment by mizzunet** [comment]
> I've updated the README to be a bit more clear about how to add the search engine to Chromium based browsers. Thanks for bringing this to my attention!

But Android Chromium based browser still need the requirement @r4dian mentioned. Cannot add custom search engine and all.
