### ISSUE TITLE
[BUG] /whoogle path constantly grows in size, also something pings google every 10 seconds

### ISSUE THREAD

**Issue by Suika** [benbusby/whoogle-search#313]
**Describe the bug**
Something performs checks every 10 seconds or less, calling out to google.
That something doesn't seem to be able to parse the respons properly and leaves files in the directory as is. Filling up the volume on which the container runs.

```
-rw-r--r-- 1 root root  46271 May 13 21:53 index.html
-rw-r--r-- 1 root root  46271 May 13 21:53 index.html.1
-rw-r--r-- 1 root root  46271 May 13 21:53 index.html.2
-rw-r--r-- 1 root root  46271 May 13 21:53 index.html.3
-rw-r--r-- 1 root root  46271 May 13 21:54 index.html.4
-rw-r--r-- 1 root root  46271 May 13 21:54 index.html.5
...
-rw-r--r-- 1 root root  46271 May 14 12:16 index.html.5055
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5056
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5057
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5058
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5059
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5060
-rw-r--r-- 1 root root  46271 May 14 12:17 index.html.5061
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5062
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5063
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5064
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5065
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5066
-rw-r--r-- 1 root root  46271 May 14 12:18 index.html.5067
-rw-r--r-- 1 root root  46271 May 14 12:19 index.html.5068
-rw-r--r-- 1 root root  46271 May 14 12:19 index.html.5069
drwxr-xr-x 1 root root 149882 May 14 12:19 .
root@b0bf921036b3:/whoogle# du -sh .
239M    .

```

**To Reproduce**
1. Probably have #311 problem
2. Start whoogle
4. Check /whoogle path in container

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Additional context**

**Comment by benbusby** [comment]
This looks like it could be an issue with the `wget` healthcheck, as if it's ignoring being told to output to console. I just updated it to use `curl` instead with 1fdf226802d67445f7570b34a3323463e165770d, which I think should fix this issue.
