### ISSUE TITLE
[BUG] No search results showing, only white box/login button

### ISSUE THREAD

**Issue by fillwe** [benbusby/whoogle-search#315]
**Describe the bug**
When searching the only thing you see is a white box and a log in button. It started happening today. Have tried purging configuration, removing and redownload the container and tried removing cache.

[https://i.imgur.com/i6kydQp.png](url)

**To Reproduce**
1. Start page loads perfectly, as soon as you search for something this happens

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- x[ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - iOS Edge/Safari and on Windows Edge/Brave

**Smartphone (please complete the following information):**
 - Both windows and ios devices, latest firmware

**Additional context**

**Comment by milachevalier** [comment]
Possibly due to #311

**Comment by eddydc** [comment]
Confirmation from my side having the white box with login button

**Comment by grubeli** [comment]
It's not a white box, if you scroll a bit you will see this:
![image](https://user-images.githubusercontent.com/74614193/118317265-bada8a80-b4ef-11eb-8f3b-5682bd89c02c.png)

**Comment by eddydc** [comment]
> It's not a white box, if you scroll a bit you will see this:
> ![image](https://user-images.githubusercontent.com/74614193/118317265-bada8a80-b4ef-11eb-8f3b-5682bd89c02c.png)

Indeed. The buttons at the end gives an error or does nothing. Whatever, this screen shouldn't be there. One should see search results.

**Comment by grubeli** [comment]
As already mentioned it's due to https://github.com/benbusby/whoogle-search/issues/311

**Comment by benbusby** [comment]
Should be fixed now with #320. The latest, beta, and buildx-experimental Docker tags will be updated with the fix shortly.
