### ISSUE TITLE
[FEATURE] <iframe-able page for insertion into other sites/startpages>

### ISSUE THREAD

**Issue by haltdev** [benbusby/whoogle-search#319]
**Describe the feature you'd like to see added**
A small HTML page (or something else that would net the same effect as described next) that could be used in an iframe in another webpage/site; for example: https://duckduckgo.com/search.html

**Additional context**
An HTML page with only a search bar a la https://duckduckgo.com/search.html that can be used inside an iframe or other web pages.

**Comment by haltdev** [comment]
Maybe not necessary, looks like I was able to accomplish this without an iframe
`'<form action="https://whoogle.url/search" method="get"><input type="text" name="q" style="width: 100%" spellcheck="false" autofocus="true" /></form>'`

**Comment by benbusby** [comment]
Seems like a good enough idea either way. I just added it in https://github.com/benbusby/whoogle-search/commit/d5eebe9fe5805800cd335f1629cc8276e1224aa3. Thanks for the suggestion!

**Comment by haltdev** [comment]
Thanks for this!  Only issue, and maybe its because I'm not passing the right arguments through on the iframe, is that the iframe'd whoogle page (search.html) displays the search results in the tiny iframe rather than loading a full whoogle page.

I looked at the [source of the duckduckgo search.html file](view-source:https://duckduckgo.com/search.html) and noticed the `<form>` has `target="_top"` - I think this might be needed to display the whoogle search in the full page?
