### ISSUE TITLE
[FEATURE] country/region selection in result instead of configuration

### ISSUE THREAD

**Issue by eddydc** [benbusby/whoogle-search#322]
**Describe the feature you'd like to see added**
Currently a country can only be selected via the configuration. 

I would prefer that one would select the country/region when the results are shown instead of changing the config each time. A good reference for this is startpage.com

**Additional context**

**Comment by bruvv** [comment]
I too think we could improve a lot with dual languages. For example. I am from Germany, speaking English and living in The Netherlands. I use a german VPN and my language search option is set to english. 
When I am searching for `volkswagen` I want to get the dutch site for the car company them selfs: `https://www.volkswagen.nl/` but this is what I am getting:
![afbeelding](https://user-images.githubusercontent.com/3063928/121145519-92b02400-c82e-11eb-8eb3-58ee40288aad.png)

Google:
![afbeelding](https://user-images.githubusercontent.com/3063928/121145564-9e034f80-c82e-11eb-98c0-bead11003a6a.png)

How can we fix this for people that do not only want english results but do speak english :P ?

**Comment by benbusby** [comment]
@bruvv 

> How can we fix this for people that do not only want english results but do speak english :P ?

Can you share the URL for the Google search you performed? The URL parameters would tell me more about how the results were fetched than a screenshot. 

That being said, a simple change of the "Search Language" from English to Dutch returns the same results for Whoogle as the results from your Google search, at least in my quick test. In your Whoogle screenshot you have your Search Language set to English, which is why only English language websites are returned (i.e. `volkswagen.com` instead of `volkswagen.nl`).

**Comment by eddydc** [comment]
I never encountered such an option in Google itself and one needs to choose explicitly the country via the URL eg Google.de or Google.be. Otherwise Google chooses the site based on ip location.
Therefore I was referring to startpage.com which let's you choose the country after the initial search if you don't want the ip location based results. I guess they change the Google URL in the background.

**Comment by bruvv** [comment]
> 
> Can you share the URL for the Google search you performed? The URL parameters would tell me more about how the results were fetched than a screenshot.
```
https://www.google.com/search?q=volkswagen&newwindow=1&sxsrf=ALeKk001tX63ncHeezI_iGucxB8W7cPT2w%3A1623573215598&source=hp&ei=38LFYIPkIceP8gK8_onoCA&iflsig=AINFCbYAAAAAYMXQ758Zor-d16WWq3WF0Cxn47PR3D6T&oq=volkswagen&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAELEDMgUIABCxAzIFCAAQsQMyBQgAELEDMggIABCxAxCDATIFCAAQsQMyBQgAELEDMgUIABCxAzICCAAyBQgAELEDOggILhCxAxCDAToLCAAQsQMQxwEQowI6CwguELEDEIMBEJMCOggIABDHARCvAToOCAAQsQMQgwEQxwEQowI6CwgAELEDEMcBEK8BOgcIABCxAxAKOgoIABCxAxCDARAKOgQIABAKUPQDWNAPYJgRaAFwAHgAgAHIAYgBhAeSAQUzLjcuMZgBAKABAaoBB2d3cy13aXo&sclient=gws-wiz&ved=0ahUKEwjDz57GmZTxAhXHh1wKHTx_Ao0Q4dUDCAY&uact=5
```

> 
> That being said, a simple change of the "Search Language" from English to Dutch returns the same results for Whoogle as the results from your Google search, at least in my quick test. In your Whoogle screenshot you have your Search Language set to English, which is why only English language websites are returned (i.e. `volkswagen.com` instead of `volkswagen.nl`).
True but I do want to have it in english, that is why I am using google.com` instead of `.nl`

**Comment by scgf** [comment]
I can only use search engines which allow me to specify a country at the search results level. I am in the UK and normally international results in English are what I want. Searching for a computer issue, for example, is not usually country dependent. If I am searching for a retail product, however, I want to see results from the UK, not from the US. I can select 'UK' in Google, StartPage, DuckDuckGo and Kagi Search and Brave Search, but not Whoogle. Please add in a toggle.
