### ISSUE TITLE
[BUG] Full screen width body to 100%

### ISSUE THREAD

**Issue by webac** [benbusby/whoogle-search#326]
Hi all,

I don't know why the body width is limited to 736px or 700px (Google Images),
Is it possible to change the body width to 100%?
I tried with this and it looks okay!
`max-width: 100%;`

Whet do you think?

Thank you
L

**Comment by benbusby** [comment]
All custom styling (such as this suggestion) should go in the “Custom CSS” section of the Whoogle instance’s configuration. As much as I’d like to include everyone’s stylistic preferences, they often conflict with one another, so they should be kept unique per instance.
