### ISSUE TITLE
[FEATURE] Clarify about "Content-Security-Policy"

### ISSUE THREAD

**Issue by Myzel394** [benbusby/whoogle-search#336]
**Describe the feature you'd like to see added**
Clarify about the usage of `Content-Security-Policy`. If you add `style-src *` to it, Whoogle won't work (currently).

**Additional context**
I setup my own instance, hardened it using some security headers, one of them was `Content-Security-Policy`. Turned out, I can't use it with Whoogle. I think it would be good to add this to the installation part, to avoid people spending hours finding out why there are no inline styles available ^O^

**Comment by benbusby** [comment]
Sure. Just out of curiosity, which method were you using for deployment/installation? I assume these were headers applied by a reverse proxy?

Whoogle handles the CSP itself, so there shouldn't be any need to modify it externally, but I agree that it should be documented somewhere.

**Comment by Myzel394** [comment]
I used nginx. 

Here's an example config:

```
server {
    server_name whoogle.com;

    location /.well-known { }

    location / {
        proxy_pass http://127.0.0.1:5000;
    }

    # Gzip compression
    gzip on;

    # Browser security
    add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
    add_header Content-Security-Policy "default-src 'self'; font-src *;img-src * data:; script-src *; style-src *";   # <-- Bad guy
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy "strict-origin";
```
}

Just removed it, worked after that :D.
