### ISSUE TITLE
[BUG] when using a dutch browser search results return in german

### ISSUE THREAD

**Issue by bruvv** [benbusby/whoogle-search#344]
**Describe the bug**
When using a dutch browser, the search results return in german. I forced the settings to use english but even then it returns german results.

![image](https://user-images.githubusercontent.com/3063928/120661347-77d55c80-c488-11eb-8481-553001b83fdc.png)
![image](https://user-images.githubusercontent.com/3063928/120661386-815ec480-c488-11eb-916c-a00647b480d0.png)

**To Reproduce**
1. Set browser language to Dutch
2. Browse the Whoogle search
3. Alles ist in German (I cannot speak nor read German)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- Whoogle Search v0.5.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Firefox
 - Version: Latest

I did make a PR to add Dutch translation: https://github.com/benbusby/whoogle-search/pull/343 I am almost 99% sure that it will not help though.

**Comment by benbusby** [comment]
Hmmm, that's odd. How are you hosting your whoogle instance? I'm curious if the specified query language is being ignored by Google and replaced with IP geolocation for some reason.

Can you post the results of `<your whoogle url>/config` (obscuring the `url` val, if private)? Also just to check, are you using the `latest` docker tag -- the one that includes the changes from your PR?

**Comment by bruvv** [comment]
It is hosted with docker with the latest tag it just got updated. Still same issue.
After changing the interface language, trying Dutch and English both fixed the issue by forcing the interface language :) 
So when no interface language is selected it should default to something: English not to "something" 

This is the config:
```
{"url": "https://***.nl/", "lang_search": "lang_en", "lang_interface": "lang_en", "style": "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t:root {\r\n /* LIGHT THEME COLORS */\r\n --whoogle-logo: #685e79;\r\n --whoogle-page-bg: #ffffff;\r\n --whoogle-element-bg: #4285f4;\r\n --whoogle-text: #000000;\r\n --whoogle-contrast-text: #ffffff;\r\n --whoogle-secondary-text: #70757a;\r\n --whoogle-result-bg: #ffffff;\r\n --whoogle-result-title: #1967d2;\r\n --whoogle-result-url: #0d652d;\r\n --whoogle-result-visited: #4b11a8;\r\n\r\n /* DARK THEME COLORS */\r\n --whoogle-dark-logo: #685e79;\r\n --whoogle-dark-page-bg: #000000;\r\n --whoogle-dark-element-bg: #4285f4;\r\n --whoogle-dark-text: #ffffff;\r\n --whoogle-dark-contrast-text: #ffffff;\r\n --whoogle-dark-secondary-text: #bbbbbb;\r\n --whoogle-dark-result-bg: #212131;\r\n --whoogle-dark-result-title: #64a7f6;\r\n --whoogle-dark-result-url: #34a853;\r\n --whoogle-dark-result-visited: #bbbbff;\r\n}\r\n\r\n#whoogle-w {\r\n fill: #4285f4;\r\n}\r\n\r\n#whoogle-h {\r\n fill: #ea4335;\r\n}\r\n\r\n#whoogle-o-1 {\r\n fill: #fbbc05;\r\n}\r\n\r\n#whoogle-o-2 {\r\n fill: #4285f4;\r\n}\r\n\r\n#whoogle-g {\r\n fill: #34a853;\r\n}\r\n\r\n#whoogle-l {\r\n fill: #ea4335;\r\n}\r\n\r\n#whoogle-e {\r\n fill: #fbbc05;\r\n}\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t", "block": "", "ctry": "", "safe": false, "dark": "on", "alts": "on", "nojs": false, "tor": false, "near": "", "new_tab": "on", "view_image": "on", "get_only": "on", "safe_keys": ["lang_search", "lang_interface", "ctry", "dark"]}
```

**Comment by benbusby** [comment]
As of the new `0.5.3` release / 614dceeb7065685b9a39241cb811f86f15fbe92d the interface language defaults to English if nothing is set in the config menu. Hopefully that clears things up moving forward. Thanks for reporting this!

**Comment by bruvv** [comment]
Ah it checks the IP! That could be why I was seeing German. Because I've a VPN via German 😂 could we perhaps use the language of the browser ?

**Comment by benbusby** [comment]
Right. The potential solution of using the browser's language has come up in past discussions, but I'm still not sure of a great way to implement it cleanly. The browser language is accessible with Javascript pretty easily:

```javascript
let userLang = navigator.language || navigator.userLanguage; 
```

but since all configuration is handled server side (including translations), this isn't much help unless loading the initial page load also automatically updates the config by sending the server the current browser language. I guess that's still an option, I just feel like there's probably a better solution that I'm overlooking...
