### ISSUE TITLE
"I'm Feeling Lucky" with shortcut

### ISSUE THREAD

**Issue by icelander** [benbusby/whoogle-search#35]
**Describe the feature you'd like to see added**
If you put an exclamation point at the beginning of your search, Whoogle would get the first result and redirect you to that page securely and privately.

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
When receiving the search query, check the beginning of the string for `! `. If it's there, remove it from the search query and search Google. When processing the results, do a redirect to the first one instead of showing the search results.

**Additional context**
DuckDuckGo has the concept of [Bangs](https://duckduckgo.com/bang) which are shortcuts to specific search results. The most useful is the I'm Feeling Lucky, which is just `! `. In the future Whoogle could have other ones, or the ability to configure your own.

**Comment by benbusby** [comment]
This is a really great idea, thanks for the suggestion! It doesn't sound too hard to add it in either, so I'll try to work this into the next release.

**Comment by icelander** [comment]
[Submitted a PR](https://github.com/benbusby/whoogle-search/pull/46) :)

**Comment by benbusby** [comment]
Merged in #46
