### ISSUE TITLE
[FEATURE] Wide UI

### ISSUE THREAD

**Issue by dimqua** [benbusby/whoogle-search#361]
Could you implement an option to use wider user interface, pretty much like Libreddit allows you to do so in the settings:
![image](https://user-images.githubusercontent.com/540898/122296473-2060d300-cf03-11eb-92a8-4b8bbecb05ac.png)

**Comment by Albonycal** [comment]
Yea wide Ui would be nice

**Comment by benbusby** [comment]
Looks like that feature is just adjusting the width of the main div in libreddit. You can do the same in Whoogle using the custom CSS config:

```
body {
    max-width: 100% !important; /* or whatever width you want */
}
```

**Comment by Albonycal** [comment]
But still, a button will help normal users

**Comment by Albonycal** [comment]
Is this being considered?
Also using that CSS the results look oddly stretched.. & I'm not very good at CSS 
![image](https://user-images.githubusercontent.com/67057319/123792523-55572780-d8fe-11eb-883f-81ee49e673a0.png)
How to solve that?
Thank You
