### ISSUE TITLE
[FEATURE] shadowsocks support

### ISSUE THREAD

**Issue by specter78** [benbusby/whoogle-search#362]
**Describe the feature you'd like to see added**
Shadowsocks proxy support

**Additional context**
Since many vpns offer shadowsocks support. And to view results from my country.

**Comment by DUOLabs333** [comment]
Do you want `shadowsocks` specifically (specifying the `shadowsocks` server), or are you OK with `SOCKS` support (specifying the `shadowsocks` client)? The latter should already be in there (`WHOOGLE_PROXY_LOC` should be `socks5h`, though it probably should be renamed to `WHOOGLE_PROXY_TYPE`). What do you think @benbusby?

**Comment by benbusby** [comment]
`WHOOGLE_PROXY_TYPE` already exists for that purpose, `WHOOGLE_PROXY_LOC` is for specifying the connection details. To add `socks5h` support, we'd need to update `app/request.py` to differentiate between that and regular `socks5` connection strings though.

**Comment by DUOLabs333** [comment]
Now I'm confused -- what is LOC for?

**Comment by DUOLabs333** [comment]
Aren't `socks5h` paths the same as `socks5` paths?

**Comment by benbusby** [comment]
I assumed `socks5h` needed to be defined in the connection string (i.e. `socks5h://...` versus `socks5://`). I haven't actually looked into it too much yet though, so I could be wrong.

**Comment by DUOLabs333** [comment]
Shouldn't the type be the first part of the connection string, so it doesn't have to be in LOC (it could be just address and port)?

**Comment by benbusby** [comment]
Currently type isn't included in `LOC`, but the type is hardcoded to `socks5` if it isn't a regular http/https proxy type. But yeah we need to just remove the hardcoded `socks5://` part of the current connection string and just use whatever type the user specified.

**Comment by DUOLabs333** [comment]
What do you mean, it looks right to me.

**Comment by benbusby** [comment]
Forgot to actually close this. This should supported by the existing socks proxy support in Whoogle. The shadowsocks server location just has to be defined using the `WHOOGLE_PROXY_LOC` and `WHOOGLE_PROXY_TYPE` environment variables.
