### ISSUE TITLE
[FEATURE] Option "People also ask" sections in results

### ISSUE THREAD

**Issue by baek-sang** [benbusby/whoogle-search#365]
**Describe the feature you'd like to see added**
Add Configuration option : disable "People also ask" section.
If disabled section, show more search results.
Add +, - button and default collapse

**Additional context**
![wg](https://user-images.githubusercontent.com/69100154/122665625-41ffda00-d1e3-11eb-9252-130b0c572d60.png)

**Comment by benbusby** [comment]
Thanks for the recommendation -- fixed with afd01820bbb859d86938abb0b55ac7df96278d8a. Available on `main` and `develop` branches, as well as `latest` and `beta` images on Docker Hub shortly.
