### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#366]
Is this a bug (or possible vulnerability) 
Dunno...
But searching the root url of whoogle (5.4 ver) causes Too many redirect error
`POST` method does not give any error and works as intended
Maybe it's a `HTTP` protocol thing?
Dunno
I just thought this's weird 
![image](https://user-images.githubusercontent.com/67057319/122676659-9f545500-d1fc-11eb-9044-68211a874679.png)

**Comment by benbusby** [comment]
This seems to only happen on Heroku instances, so I don't actually think it's a Whoogle specific bug. I can't think of why this would happen for Heroku instances, but there isn't any redirect behavior based on a user's search unless a bang query has been performed, and even then it doesn't rely on a user searching a domain directly. 

It is weird, but seems like a fairly innocuous bug. Thanks for bringing it to my attention, I'll keep it mind and revisit this issue if I think of a possible cause.

**Comment by Albonycal** [comment]
[https://help.heroku.com/VKLSBMJS/why-am-i-getting-a-message-too-many-redirects](https://help.heroku.com/VKLSBMJS/why-am-i-getting-a-message-too-many-redirects)
Maybe this's causing it?
![image](https://user-images.githubusercontent.com/67057319/123368031-a7afe580-d598-11eb-8a46-0b4b92fe70ba.png)
