### ISSUE TITLE
[DMCA] <Search Results are removed in google (DMCA Takedown) >

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#367]
Search results are ***censored*** by google
(DMCA) Is there a way to show the results that are blocked?
(I don't think so, This can't be done without doing crawling) 
Is there a way to implement this by looking at the urls that google's blocking?

**Comment by federicotorrielli** [comment]
Hi. If they are censored by Google, we can do nothing about that. The thing that Whoogle does is just take the "light" version of Google's result page and show it to you changing a lil' bit of things. So no, we can't show that.

**Comment by Albonycal** [comment]
I know..
But I thought if there was some way in which google leaks the urls that were blocked..
nvm
