### ISSUE TITLE
Unable to deploy it on docker manually 

### ISSUE THREAD

**Issue by pranjal-b** [benbusby/whoogle-search#372]
bin/sh: /misc/tor/start-tor.sh not found
bin/sh: ./run not found

**Comment by bruvv** [comment]
This is a useless bug report and you should use the template provided...

**Comment by pranjal-b** [comment]
@bruvv can you help me resolve this issue.

**Comment by alefvanoon** [comment]
Do you still have this problem?
If yes, you are using [docker-compose.yml]( https://github.com/benbusby/whoogle-search/blob/main/docker-compose.yml)?
