### ISSUE TITLE
[FEATURE] Anti-support for JavaScript

### ISSUE THREAD

**Issue by Hund** [benbusby/whoogle-search#376]
It would be nice to see anti-support for JavaScript. As we all know, JavaScript is the devil and should always be avoided at all costs.

Thank you!

**Comment by federicotorrielli** [comment]
How can you search or interact with the site without JS? This seems one of the extremist ideas I see everyday from Luke Smith's videos but here I can tell you that JS is not the real dealbreaker for bottlenecks, it's the interaction with Google as the middleman.

But, of course, if you have good ideas on how to get rid of JS, enlighten us.

**Comment by Hund** [comment]
Did you just compare me to Luke Smith?
