### ISSUE TITLE
URL to Google preferences when search query is in English 

### ISSUE THREAD

**Issue by demostanis** [benbusby/whoogle-search#386]
I'm using flawcra.cc public instance.
When I search something in English, the results are being displayed in German,
despite having my default browser language set to English. Whoogle shows me the same
message as Google:
![image](https://user-images.githubusercontent.com/40673815/129456125-2b07b7f9-ec66-4659-844a-b856eb9a633d.png)
Which tells me to change my language preferences... on google.com.
![image](https://user-images.githubusercontent.com/40673815/129456156-631f9664-b8cd-4da6-a2b5-2aa79769f8c1.png)
This is not what a Whoogle user wants.

**Comment by Albonycal** [comment]
Probably, the language of that particular instance is set to that?

**Comment by demostanis** [comment]
Probably, but that's not the issue.
A whoogle user might get tricked into thinking the link redirects him to *Whoogle* preferences,
while it will actually lead him to *Google*.

**Comment by VerstreuteSeele** [comment]
I think you misunderstood whoogle.

Whoogle is not a custom webcrawler that gives you custom results. all it does it ask google whatever you asked whoogle and return it to you without any of the bs google adds to it like ads, cookies and ofc tracking.

**Comment by demostanis** [comment]
I totally understand what Whoogle is.
I just think that Whoogle should also filter out this popup which leads to a page to change **Google**'s settings (even though Whoogle uses Google, your preferences won't have any effects, damn), just like they do for ads, cookies and tracking.

**Comment by Aikatsui** [comment]
See https://github.com/benbusby/whoogle-search/issues/281#issuecomment-819554065
