### ISSUE TITLE
Unknown Bug Prevents all searching

### ISSUE THREAD

**Issue by Skibud** [benbusby/whoogle-search#388]
When ever I try to search on my instance, I get this error and im just unable to use the search engine. 

<img width="1440" alt="Screenshot 2021-08-18 at 09 59 12" src="https://user-images.githubusercontent.com/51403094/129860782-2e9760fe-9944-4f9d-b7c2-045192024978.png">

**Comment by Albonycal** [comment]
That's google captha my friend..
Looks like it's detecting this traffic as "weird"

**Comment by Skibud** [comment]
> That's google captha my friend..
> Looks like it's detecting this traffic as "weird"

Hmmm, is it the subject that could be the issue or the amount of requests per day. Considering this is a public instance I think it could be the latter.

**Comment by alefvanoon** [comment]
> Edit: would shutting it down for a couple days mby get google off my back?

Maybe!
But I suggest using a VPN or change your IP in any way.(on server side)
