### ISSUE TITLE
[QUESTION] Disable autocompletion

### ISSUE THREAD

**Issue by VerstreuteSeele** [benbusby/whoogle-search#390]
As the title suggests. i dont know if this is already in there and I skipped past it because im dumb and/or blind but if not im sure theres a way to disable that, right?

**Comment by Darkempire78** [comment]
The autocomplete is done by your browser, not by Whoogle if I'm not mistaken

**Comment by VerstreuteSeele** [comment]
doubt since 
1. autocomplete is a feature on the page
2. autocomplete files in the project exist
3. other search engines dont auto-complete

**Comment by alefvanoon** [comment]
> As the title suggests. i dont know if this is already in there and I skipped past it because im dumb and/or blind but if not im sure theres a way to disable that, right?

You can disable it from html files.

**Comment by VerstreuteSeele** [comment]
thanks
