### ISSUE TITLE
[QUESTION] <No https + remove port number from url>

### ISSUE THREAD

**Issue by brackhap** [benbusby/whoogle-search#392]
I'v installed whoogle docker container using cyberpanel, I have 2 questions:

1- How to enable https for my whoogle domain? I've issued the SSL certificate using cyberpanel but it's not working!
2- How to remove the port number from the URL of my whoogle instance?

**Comment by alefvanoon** [comment]
> I'v installed whoogle docker container using cyberpanel, I have 2 questions:
> 
> 1- How to enable https for my whoogle domain? I've issued the SSL certificate using cyberpanel but it's not working!
> 2- How to remove the port number from the URL of my whoogle instance?

You need to use NGINX!

**Comment by benbusby** [comment]
You need to use a reverse proxy (such as nginx like @alefvanoon mentioned).
