### ISSUE TITLE
[BUG] Can't add Whoogle as a default search engine on Firefox PC

### ISSUE THREAD

**Issue by ssokhey** [benbusby/whoogle-search#394]
**Describe the bug**

I am not able to add whoogle as my search engine on Firefox browser. 
Followed all the steps mentioned for containers. Tried with troubleshoot mode as well. No success.

All I get is:

Firefox could not download the search plugin from: `http://<IP>:5000/opensearch.xml`

**To Reproduce**
I deployed using manual mode, to be precise *F) Manual* on Readme.md.
 
**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [describe setup]

I have deployed it on Bahnof VPS.

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

Just pulled the repo from Github and did the setup today.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser FIREFOX
 - Version 91.0.1

**Additional context**
I am just serving as of now on http and accessing using floating IP provided by Banhof VPS with port 5000.
Yes, I have set this env variable: **WHOOGLE_CONFIG_GET_ONLY=1**
 
Service file:

```
[Unit]
Description=Whoogle

[Service]
# Basic auth configuration, uncomment to enable
#Environment=WHOOGLE_USER=<username>
#Environment=WHOOGLE_PASS=<password>
# Proxy configuration, uncomment to enable
#Environment=WHOOGLE_PROXY_USER=<proxy username>
#Environment=WHOOGLE_PROXY_PASS=<proxy password>
#Environment=WHOOGLE_PROXY_TYPE=<proxy type (http|https|proxy4|proxy5)
#Environment=WHOOGLE_PROXY_LOC=<proxy host/ip>
# Site alternative configurations, uncomment to enable
# Note: If not set, the feature will still be available
# with default values. 
#Environment=WHOOGLE_ALT_TW=nitter.net
#Environment=WHOOGLE_ALT_YT=invidious.snopyta.org
#Environment=WHOOGLE_ALT_IG=bibliogram.art/u
#Environment=WHOOGLE_ALT_RD=libredd.it
#Environment=WHOOGLE_ALT_TL=lingva.ml
# Load values from dotenv only
Environment=WHOOGLE_DOTENV=1
Type=simple
User=root
WorkingDirectory=/home/ubuntu/apps/whoogle-search
ExecStart=/home/ubuntu/apps/venv/bin/python3 -um app --host 0.0.0.0 --port 5000
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
SyslogIdentifier=whoogle

[Install]
WantedBy=multi-user.target
```

**Comment by VerstreuteSeele** [comment]
I sadly cant help with your issue but you can still change the title if you click on edit next to it so others know what your issue is

**Comment by ssokhey** [comment]
Guys, false alarm.

There is no bug.

I turned of HTTPS only mode on Firefox and it worked.
