### ISSUE TITLE
[QUESTION] Nginx Query -  Wrong nginx setup causing issues?

### ISSUE THREAD

**Issue by ssokhey** [benbusby/whoogle-search#396]
I have done my setup using manual method, everything worked via `http://IP:PORT` until I tried using nginx reverse proxy.

If I go directly to `search.mydomain.com`, whoogle works without any issues.

When I right click on the mozilla address bar, add "Whoogle" as search engine, I can see Whoogle under search engines.

Now, I set it to default and try to search "Hello", it automatically gets redirected to `0.0.0.0:5000/search?q=Hello` and I end up getting `Firefox can’t establish a connection to the server at 0.0.0.0:5000.`

I am pretty sure, nginx config is causing issues as I am not well versed with nginx.

I am pasting my config below:

```
server {
    server_name search.mydomain.com;

   location / {
      proxy_pass http://0.0.0.0:5000;

   }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/search.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/search.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}



server {
    if ($host = search.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name search.mydomain.com;
    return 404; # managed by Certbot


}

```

Any help is highly appreciated.

**Comment by gripped** [comment]
Try 
```
location / {
      proxy_pass http://0.0.0.0:5000;
      proxy_set_header Host $host;
   }
```
Personally  I use http://127.0.0.1:5000 but doubt that makes any difference.
From my understanding if you don't set `proxy_set_header Host` then whatever is defined in `proxy_pass` will be returned. Which seems to be what is happening.

**Comment by ssokhey** [comment]
Hey,

It doesn't work, same issue again.

However, I got it working after using this [extension](https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/).

Nonetheless, I would like to solve this issue and validate my nginx config.

---

@gripped If possible, can you please share your nginx config so that I can actually compare it against mine?

Or anybody else, can you help validate/suggest how the nginx config should be? I couldn't find any guide for setting reverse proxy elsewhere.

Highly appreciate any help.

**Comment by gripped** [comment]
```
  server {
    server_name whoogle.mydomain.com;
	root /var/www/whoogle;
    access_log  /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log debug;
	index index.html index.htm;
	
	location / {
		proxy_pass http://127.0.0.1:5000/;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header Host $host;	# so invidious knows domain
		proxy_http_version 1.1;		# to keep alive
		proxy_set_header Connection "";	# to keep alive
	}


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/whoogle.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/whoogle.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
  server {
    if ($host = whoogle.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name whoogle.mydomain.com;
    listen 80;
    return 404; # managed by Certbot


}
```
You may guess from the comments it was adapted from my invidious .conf. Some parts may be unnecessary ? But it works so I left it alone.

**Comment by ratherDashing** [comment]
> this is working for me:
> 
> ```
>  location /whoogle/ {
>         rewrite /whoogle(.*) /$1 break;
>         proxy_pass http://localhost:5000;
>  }
> ```

this works for me as well, everything else was giving me a redirect loop.  thank you!
