### ISSUE TITLE
Add Safesearch options

### ISSUE THREAD

**Issue by katchy3132** [benbusby/whoogle-search#40]
**Describe the feature you'd like to see added**
Add the ability to set Safe Search options. An added bonus would be to force the option at the server level to hide it from the user

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
The UI and the required back end / config elements.
**Additional context**

![image](https://user-images.githubusercontent.com/3707138/81822886-5384a600-953c-11ea-9dfc-4800f036b392.png)

**Comment by benbusby** [comment]
Added in #71 -- there's now a home page config option to enable/disable safe search as needed. Thanks for the suggestion!
