### ISSUE TITLE
[BUG] DDG style bangs should support bang at the end

### ISSUE THREAD

**Issue by agg23** [benbusby/whoogle-search#404]
**Describe the bug**
DuckDuckGo allows the user to specify bangs at either the start or the end of a custom command, as long as the short form is used: `!g` or `g!`. It would be nice if we had the same functionality here.

**Comment by Albonycal** [comment]
Huh.. yea.. I tried to use that but it didn't work... This will be very useful

**Comment by dalf** [comment]
In searx, DDG bangs are implemented as a trie:
* https://github.com/searx/searx/blob/master/searx/data/external_bangs.json
* https://github.com/searx/searx/blob/master/searx/external_bang.py
* https://github.com/searx/searx/blob/master/searx_extra/update/update_external_bangs.py

Raw idea: it can be an external package, so different projects can use it.
