### ISSUE TITLE
[FEATURE] Support Setting Near City through Environment Variables

### ISSUE THREAD

**Issue by FlorianWendelborn** [benbusby/whoogle-search#406]
**Describe the feature you'd like to see added**
Near city doesn’t seem to be configurable through environment variables. I suppose there shouldn’t be an issue with also supporting this, right?

**Additional context**
I tried looking through both the readme and whoogle.env, but couldn’t find any indication that this is supported. I also checked the wiki expecting that there might be some more infos about the usages of the environment variables, but was unsuccessful in finding anything about how to configure the city.

**Comment by benbusby** [comment]
Sorry for the delay!

You actually can set the "near" city using `WHOOGLE_CONFIG_NEAR`, but it looks like I neglected to add this anywhere in the documentation. I'll work on adding it shortly.

**Comment by FlorianWendelborn** [comment]
Thanks
