### ISSUE TITLE
[BUG] Cloudflare CDN cannot be used

### ISSUE THREAD

**Issue by muzihuaner** [benbusby/whoogle-search#409]
Cloudflare CDN cannot be used, and ERR_CONNECTION_RESET is displayed when searching. Although the homepage can be opened, the search cannot be used

**Comment by alefvanoon** [comment]
I haven't any problem with Cloudflare CDN.

https://s.alefvanoon.xyz (using cloudflare)

How did you running whoogle?

**Comment by muzihuaner** [comment]
> I haven't any problem with Cloudflare CDN.
> 
> https://s.alefvanoon.xyz (using cloudflare)
> 
> How did you running whoogle?
> If you are using NGINX please send your config here.

I run it on Repl.it ,add Cloudflare CDN.,but,it not work，Don't know what the problem is

**Comment by alefvanoon** [comment]
> I run it on Repl.it ,add Cloudflare CDN.,but,it not work，Don't know what the problem is

Try changing your SSL/TLS mode to full.(also you can try other encryption)
![image](https://user-images.githubusercontent.com/53198048/132086311-14f460f8-d376-4ca7-94a2-29ef203da605.png)

**Comment by muzihuaner** [comment]
> > I run it on Repl.it ,add Cloudflare CDN.,but,it not work，Don't know what the problem is
> 
> Try changing your SSL/TLS mode to full.
> ![image](https://user-images.githubusercontent.com/53198048/132086311-14f460f8-d376-4ca7-94a2-29ef203da605.png)

ok，thanks
