### ISSUE TITLE
Select country and language

### ISSUE THREAD

**Issue by C42EFF4Lbb54dwg** [benbusby/whoogle-search#41]
**Describe the feature you'd like to see added**
an option to select the country and language

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
Not completely sure what will be required, but assuming both front and back end changes will be needed.

**Additional context**
quite basic.

**Comment by benbusby** [comment]
Language was added in #27, will need to look into setting country though

**Comment by C42EFF4Lbb54dwg** [comment]
> Language was added in #27, will need to look into setting country though

Thanks - how can the language option be set?

**Comment by benbusby** [comment]
In the latest master branch build, there’s a config setting on the main page to change language.

**Comment by benbusby** [comment]
I'm actually not seeing any search parameters that I can use to specify a country, aside from setting the "near" parameter to something relevant. That, plus the language config option, seems to be the best solution for this, but I'll keep an eye out and reopen if I come across something better.
