### ISSUE TITLE
[QUESTION] The README advertises "no JavaScript", but the code includes JavaScript

### ISSUE THREAD

**Issue by mariavillosa** [benbusby/whoogle-search#410]
According to the README: "No javascript". It reiterates this a few times throughout the README and elsewhere. And yet:

https://github.com/benbusby/whoogle-search/blob/68fdd554825f981a24ba3b3f1d728ec5ef260005/app/templates/display.html#L43-L45

https://github.com/benbusby/whoogle-search/blob/be3714f074c0807983148c6ffa51f1287e5f465d/app/templates/index.html#L20-L21

Perhaps we could make the promise true by removing this and changing the CSP JS policy to `none` instead of `self`.

ref:

https://github.com/benbusby/whoogle-search/blob/9f84a8ad832a130690f6a9524558522665e0c7b8/app/__init__.py#L76

Just wondering, am newbie, sorry if I'm mistaken!

**Comment by federicotorrielli** [comment]
The "No JavaScript" stands for "No Google JavaScript, No tracking JS code or else"

Cheers~

**Comment by alefvanoon** [comment]
> According to the README: "No javascript". It reiterates this a few times throughout the README and elsewhere. And yet:

Working fine without any client side JS.
Just remove script frome index.html

**Comment by benbusby** [comment]
The "no JavaScript" just means "no **external** JavaScript". There are still scripts used for things like providing search suggestions while the user is typing. That being said, JavaScript isn't used for any crucial features, and the project still works as expected with something like NoScript enabled. 

I'll add a note to the readme to clarify the meaning of that.
