### ISSUE TITLE
[QUESTION] Infinite scroll?

### ISSUE THREAD

**Issue by ser** [benbusby/whoogle-search#413]
Infinite scroll - is it possible to achieve it?

**Comment by alefvanoon** [comment]
Can you explain more?
You wanna delete the next page button and adding more result  button?
This is possible  on the client side, it creates problems and cramps, slows down the browser, and increases RAM consumption.(also need more JS code on server side)
Personally, I do not like this feature.

**Comment by ser** [comment]
Personally, I like this feature as I have 256G RAM. I do not suggest it must replace what we have now, it can be an option in configuration.

**Comment by alefvanoon** [comment]
This is a duplicate issue.
Please checkout #165 & close this.

**Comment by ser** [comment]
true, I searched for "infinite" before creating an issue, but not for "endless" :)

**Comment by Jieiku** [comment]
I am wanting this feature as well!
