### ISSUE TITLE
[QUESTION] How to add a background image?

### ISSUE THREAD

**Issue by muzihuaner** [benbusby/whoogle-search#415]
How to add a background image? I tested it in <body>, but it didn't work

**Comment by alefvanoon** [comment]
You need to edit index.html & add custom CSS.
Checkout https://www.w3docs.com/snippets/css/how-to-add-background-image.html .

**Comment by muzihuaner** [comment]
> You need to edit index.html & add custom CSS.
> Checkout https://www.w3docs.com/snippets/css/how-to-add-background-image.html .

it not work,  show    

Refused to load the image 'https://www.w3docs.com/uploads/media/default/0001/01/477719675fecaac0362957c214fb9aa56fca99b5.jpeg' because it violates the following Content Security Policy directive: "img-src 'self' data:".

quickso.eu.org/:1 Refused to load the imag

**Comment by DomainWarrior** [comment]
Hello Please try this code in your css 
<style>
.classname
{
background-image:url('{{ STATIC_URL }}change to the image you want and place in the correct static folder directory ');
background-repeat:no-repeat;
background-size:100%;
}
</style>

**Comment by muzihuaner** [comment]
> Hello Please try this code in your css
> 
> <style> .classname { background-image:url('{{ STATIC_URL }}change to the image you want and place in the correct static folder directory '); background-repeat:no-repeat; background-size:100%; } </style>

it show Refused to load the image 'static/img/bg.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by Albonycal** [comment]
Was this solved ?

**Comment by muzihuaner** [comment]
> Was this solved ?

yes，it only use .svg, but it can't use .png or .jpg
