### ISSUE TITLE
[FEATURE] <Autocomplete URL for browsers>

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#416]
Since whoogle has autocomplete functionality, what about adding an autocomplete URL for the browsers that support it?
`https://<instance>/auto?q=` something like this?
This is vivaldi and you can add a "suggest URL thing"
![image](https://user-images.githubusercontent.com/67057319/132117129-c9010bdf-1844-4ba4-9747-625569f5d5f4.png)

**Comment by alefvanoon** [comment]
Whoogle have this feature.

`https://<instance>/autocomplete?q=test`

**Comment by Albonycal** [comment]
Hmm... this ins't documented ?
