### ISSUE TITLE
[QUESTION] container won't start - "exec user process caused: operation not permitted"

### ISSUE THREAD

**Issue by auricgoldfinger007** [benbusby/whoogle-search#418]
I cloned the repo, running in the main branch. Tried 'docker-compose up -d' but get this error in the logs:

```
$ sudo docker-compose logs -f
Attaching to whoogle-search
whoogle-search    | standard_init_linux.go:228: exec user process caused: operation not permitted
whoogle-search    | standard_init_linux.go:228: exec user process caused: operation not permitted
whoogle-search    | standard_init_linux.go:228: exec user process caused: operation not permitted
whoogle-search    | standard_init_linux.go:228: exec user process caused: operation not permitted
whoogle-search    | standard_init_linux.go:228: exec user process caused: operation not permitted
```

In docker-compose.yml changed 'user' from '102' to '114' as my system has tor running outside the container, and debian-tor user id is 114.

If I run in the master branch, everything loads ok.

**Comment by benbusby** [comment]
I haven't been able to reproduce this one yet. The user ID for debian-tor within the container spun up by docker-compose should always be 102 no matter what, though. Did you shell into the container to check the user ID before changing it?
