### ISSUE TITLE
[FEATURE] In image search, provide link to image as well as image-source website

### ISSUE THREAD

**Issue by Nebukadneza** [benbusby/whoogle-search#419]
**Describe the feature you'd like to see added**
When searching for images, users usually try to achieve one of two goals:
* Find the source website for something they recognize visually
* Find a specific image to be viewed or downloaded / copied / used elsewhere

Currently, Whoogle links the image search results to the source website, and displays / proxies the result-thumbnail. There is no way to get the link to or display the original image without visiting the source website. In upstream google, there are 2 links: The text, which leads to the source website, and the image itself, which opens a sidebar. This sidebar displays the high-resolution (not thumbnailed) original image, with the original `src` set, so that things like rightclick⇒open in new tab or rightclick⇒copy/save image would work.

It would be great if whoogle also offered this workflow.

Thanks for the great project! ^_^

**Comment by benbusby** [comment]
Does the `View Full Size Images` config setting accomplish what you're asking? 

With that setting enabled, you can view the image source by clicking on the image, or view the full resolution image by clicking "View Full Image":

![image](https://user-images.githubusercontent.com/33362396/133516433-f1ee45cc-293b-4033-ad69-d920165f4c35.png)

Let me know if I'm misunderstanding your request!

**Comment by Nebukadneza** [comment]
Gosh, how did I overlook that setting? This is exactly the feature that I described, and work beautifully for me. Thank you so much!
