### ISSUE TITLE
Login page for Whoogle

### ISSUE THREAD

**Issue by Panja0** [benbusby/whoogle-search#43]
**Describe the feature you'd like to see added**
Login to Whoogle.

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
Probably both?

**Additional context**
Would it be possible to add a login page to Whoogle?
This way, when my Whoogle server is exposed to the internet it won't be hammered.
You will need to first login before you can use Whoogle.

**Comment by r0arkin** [comment]
You do have the option of using OAuth if you wanted to? That may be an option!

**Comment by Panja0** [comment]
Thanks for the quick reply!
I have to look into this... Do you have some more info on this maybe?

**Comment by r0arkin** [comment]
I use Keycloak in front of Traefik. What do you use as a reverse proxy?

**Comment by Panja0** [comment]
I'm running Whoogle in Docker.
Docker is running on my Synology which uses NGINX as reverse proxy.

**Comment by r0arkin** [comment]
Check this out: https://edhull.co.uk/blog/2018-06-06/keycloak-nginx — uses docker-compose.

**Comment by r0arkin** [comment]
Granted, adding a login page would be easier as a whole, but at least this will allow you to secure all of your containers. It supports 2FA as well which is a big plus.

**Comment by Panja0** [comment]
Thanks! I'll have a look later on. Looks promising. Just like Whoogle itself! :-D
Love it!

I'll leave my enhancement request open.

**Comment by benbusby** [comment]
I like the idea of this in principle, but (depending on implementation) it might go a bit against the philosophy of keeping this as minimal and lightweight as possible. I can see implementing some form of really basic authentication -- maybe even literally HTTP Basic Auth -- but I'm not sure I'd want to go so far as to create a login page, local user db, etc just for this. 

In any case it should definitely be an optional configuration setting to avoid any sort of delay between deployment and actually using the app. I'd even be open to it being set up as username/pw build args passed in the Dockerfile and then used by the Flask server to conditionally prompt for the basic auth dialog.

**Comment by Panja0** [comment]
Sounds good! Cheers
Keep up the good work! 😃

**Comment by benbusby** [comment]
Addressed in #51 (pending merge)
