### ISSUE TITLE
[QUESTION] does Whoogle access my location?

### ISSUE THREAD

**Issue by abishekvenkat** [benbusby/whoogle-search#432]
I was trying to order something online and made a search on Whoogle and all the suggestions had places near my actual location. Is this expected?

![image](https://user-images.githubusercontent.com/86376376/133803557-164b0e79-bef8-4700-9b36-5bcc317c57fe.png)

**Comment by benbusby** [comment]
Your actual location is only leaked if you're running Whoogle on your local machine, without any VPN or proxy enabled. If you want to hide your location, you can either 1) run the app on a virtual server via AWS, DigitalOcean, etc, or 2) configure a proxy or VPN to use with Whoogle. 

Let me know if you want me to elaborate on those options! But tl;dr -- yes, it's expected unless it's being hosted externally or configured to not use the device location.
