### ISSUE TITLE
[FEATURE] Add the ability to listen on UNIX sockets

### ISSUE THREAD

**Issue by jackyzy823** [benbusby/whoogle-search#436]
**Describe the feature you'd like to see added**
it would be very helpful that whoogle supports listening on UNIX sockets.

**Additional context**

`waitress` supports `unix_socket`. [link]( https://docs.pylonsproject.org/projects/waitress/en/latest/arguments.html)

However it may conflict with `listen` [link](https://github.com/Pylons/waitress/blob/4b6b5832f3a30d82dc8cb359cf04d2a8edf6712b/src/waitress/adjustments.py#L315) 

Thanks.

**Comment by jackyzy823** [comment]
Besides.

environment `HTTPS_ONLY` do not work since it is shadowed by args.https_only , 
https://github.com/benbusby/whoogle-search/blob/c41e0fc239840ad3839b05135f7307d8da35545f/app/routes.py#L430

**Comment by PrivacyDevel** [comment]
The permissions of the Unix socket seem to be too restrictive. Only the owner of the socket is able to connect to it, which prevents a reverse proxy from being able to connect to it if the reverse proxy is run as a different user. Which should pretty much always be the case.

**Comment by master-hax** [comment]
@PrivacyDevel i have put up a fix for the issue in https://github.com/benbusby/whoogle-search/pull/1103
