### ISSUE TITLE
Target new tab

### ISSUE THREAD

**Issue by mudbrrk** [benbusby/whoogle-search#44]
**Describe the feature you'd like to see added**
Is it possible to add a toggle to target a new tab for the links ie. target="_blank"?

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
This would be config and front-end.

**Additional context**
I keep losing my search tab when clicking links and then having to redo the search. Rinse and repeat.

**Comment by botnet88** [comment]
While you're waiting, here is a userscript that does what you want:
https://pastebin.com/raw/QiXp1Lsh
Just set the include rule to match your whoogle-search instance's URL.

**Comment by mudbrrk** [comment]
Thanks. Works a treat.

**Comment by benbusby** [comment]
Fixed in PR #49 (pending merge). Let me know if anyone wants to pull that branch and test it, otherwise will merge within the next 24 hours.
