### ISSUE TITLE
fly deployment does not work

### ISSUE THREAD

**Issue by eikaramba** [benbusby/whoogle-search#468]
fly is renamed to flyctl it seems.
also there is no image builder anymore

how can you deploy with fly currently?

**Comment by joonas-fi** [comment]
Just set up whoogle on Fly two weeks ago, worked for me.

**Comment by eikaramba** [comment]
as i said, the steps are not valid anymore. I did this now again

- clone repo //is this even needed? i mean i am just using an image for deployment right?
- flyctl apps create --org personal //set appname
- flyctl deploy -i benbusby/whoogle-search:latest -a YOURAPPNAME

But on the served domain it just returns PR_END_OF_FILE_ERROR and that it is not secure.

i'm sorry but i don't even know where to start.
the command flyctl logs -a whoogle-eikaramba outputs
```
2021-10-30T15:19:44.173 runner[fb25175a] lhr [info] Starting instance
2021-10-30T15:19:44.203 runner[fb25175a] lhr [info] Configuring virtual machine
2021-10-30T15:19:44.209 runner[fb25175a] lhr [info] Pulling container image
2021-10-30T15:19:45.728 runner[fb25175a] lhr [info] Unpacking image
2021-10-30T15:19:50.719 runner[fb25175a] lhr [info] Preparing kernel init
2021-10-30T15:19:51.173 runner[fb25175a] lhr [info] Configuring firecracker
2021-10-30T15:19:51.305 runner[fb25175a] lhr [info] Starting virtual machine
2021-10-30T15:19:51.449 app[fb25175a] lhr [info] Starting init (commit: 50ffe20)...
2021-10-30T15:19:51.471 app[fb25175a] lhr [info] Preparing to run: `/bin/sh -c misc/tor/start-tor.sh & ./run` as root
2021-10-30T15:19:51.487 app[fb25175a] lhr [info] 2021/10/30 15:19:51 listening on [fdaa:0:369b:a7b:2808:fb25:175a:2]:22 (DNS: [fdaa::3]:53)
2021-10-30T15:19:51.661 app[fb25175a] lhr [info] Starting tor daemon...done.
2021-10-30T15:19:52.476 app[fb25175a] lhr [info] Reaped child process with pid: 534, exit code: 0
2021-10-30T15:19:59.985 app[fb25175a] lhr [info] Serving on http://0.0.0.0:5000
wg connect fdaa:0:369b::3 lhr1.gateway.6pn.dev:51820 fdaa:0:369b:a7b:dc6:0:a:0 fdaa:0:369b::
```

would be nice to share how you did it @joonas-fi

**Comment by joonas-fi** [comment]
@eikaramba I don't remember everything that I did (I mucked around with SSL certificates & custom domain name), but the gist is that I deployed it from the official Docker image (no repo cloning needed).

All I have is this `fly.toml` which I deployed:

```yaml
app = "search-yourexamplename"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "benbusby/whoogle-search:0.5.4"

[env]
EXPOSE_PORT = "80"
WHOOGLE_CONFIG_GET_ONLY = "1"
WHOOGLE_CONFIG_COUNTRY = "countryFI"
WHOOGLE_CONFIG_LANGUAGE = "lang_en"
WHOOGLE_CONFIG_SEARCH_LANGUAGE = "lang_en"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
```

**Comment by eikaramba** [comment]
thanks, i did save your config(changed appname and increased image to 0.6.0) and just used

- flyctl apps create --org personal //set appname
- flyctl deploy

it is serving the app on port 80. unfortunately for the love of god i am not able to make it work in any browser (chrome,ff,edge). they all try to establish https and it fails.

test: https://whoogle-eikaramba.fly.dev (might not be online, as i will delete the project if it is not working soon)

**Comment by joonas-fi** [comment]
The URL works fine for me. Did you give it a chance to issue the SSL cert? Could've taken a while for Fly infrastructure to provision the certificate.

**Comment by eikaramba** [comment]
yes that must be it. thank you very much. i think we can solve it then. just create the fly.toml as:

```
app = "YOURAPP"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "benbusby/whoogle-search:0.6.0"

[env]
EXPOSE_PORT = "80"
WHOOGLE_CONFIG_GET_ONLY = "0"
WHOOGLE_CONFIG_COUNTRY = "countryDE"
WHOOGLE_CONFIG_LANGUAGE = "lang_de"
WHOOGLE_CONFIG_SEARCH_LANGUAGE = "lang_de"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
```

and do the above two commands. bam
