### ISSUE TITLE
Add official image to Docker Hub

### ISSUE THREAD

**Issue by acupajoe** [benbusby/whoogle-search#47]
**Describe the feature you'd like to see added**
It would be wonderful to be able to have this as a prebuilt image on dockerhub. Using their free build tools it should just be a matter of connecting the repo and being sure that tags are appropriately pushed.

Is this something y'all could add?

**Comment by benbusby** [comment]
It is [up on Docker Hub currently](https://hub.docker.com/r/benbusby/whoogle-search), and I just updated the readme to make that a bit more clear. Sorry that wasn't more evident!
