### ISSUE TITLE
[FEATURE] Reduce search bar font size on mobile

### ISSUE THREAD

**Issue by sqwwqw5** [benbusby/whoogle-search#477]
![F88A2610-0772-492C-91C2-E26EBA2364D9](https://user-images.githubusercontent.com/3581246/138140707-5e86d872-6733-4ee2-9971-627a60bc99f6.png)
Make the search box larger or make the texts inside the search box smaller would potentially solve the issue.

**Comment by lpnsk** [comment]
> 

Yes I have the same behavior on mobile (Firefox 95.1.0 on Android)
