### ISSUE TITLE
[BUG] CSP(Content Security Policy) block js running

### ISSUE THREAD

**Issue by JuenTingShie** [benbusby/whoogle-search#493]
**Describe the bug**
Hi! I'm hosting whoogle on replit.com, when using 0.6 version, the index and search result will comes with some bugs, like figure bellow

1. The main page
![圖片](https://user-images.githubusercontent.com/31978492/139004844-588c8950-987c-4690-8abe-6298a9474a94.png)
2. when search English content
![圖片](https://user-images.githubusercontent.com/31978492/139004883-0d1323ce-37b9-47c7-9025-d0b1c4a210d6.png)
3. when search Chinese content
![圖片](https://user-images.githubusercontent.com/31978492/139004937-2a0ea370-baee-4fe0-b5ee-d59dd03c09f5.png)

**To Reproduce**
1. Go to https://github.com/benbusby/whoogle-search
2. Press run on repl.it

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: repl.it

**Version of Whoogle Search**
- [x] Latest build from replit
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 93.0

I trace some possible bug reason, F12 developer tools show Content Security Policy blocked some js for running,
and says autocomplete.js is blocked

![圖片](https://user-images.githubusercontent.com/31978492/139005683-e685f6b3-26ad-4984-8532-5e25d8c45250.png)

![圖片](https://user-images.githubusercontent.com/31978492/139005490-adf35a6f-9f15-4db2-8c23-6f51f41610d6.png)

**Comment by nakoo** [comment]
Beside the bug, I believe that CSP should be applied by reverse proxy, not application itself. I always replace the CSP header by reverse proxy to add the modification. Reverse proxy do better jobs for handling this situation.

**Comment by benbusby** [comment]
@JuenTingShie apologies for the delay. The in-app CSP is now disabled by default, unless enabled via `WHOOGLE_CSP`, so your issue should be resolved. Please let me know if you continue to encounter problems or need any other help.
