### ISSUE TITLE
[BUG] Image page does not adhere to Dark Mode

### ISSUE THREAD

**Issue by r0arkin** [benbusby/whoogle-search#50]
When you search for something and you click on Images, Dark Mode does not adhere to that page. Also, it looks like the search bar text is white which would be true if Dark Mode was on for this page.

I'm running this in Docker on CentOS8. Everything else works great.

<img width="807" alt="Screen Shot 2020-05-15 at 11 51 24 AM" src="https://user-images.githubusercontent.com/46236585/82085889-85b01800-96a2-11ea-8138-3259b740d845.png">

**Comment by benbusby** [comment]
Everything is Dark Mode if you just close your eyes though, gonna mark this as `wontfix`.

Just kidding, will look into this soon.

**Comment by r0arkin** [comment]
> Everything is Dark Mode if you just close your eyes though, gonna mark this as `wontfix`.
> 
> 
> 
> Just kidding, will look into this soon. 

Haha! Thanks! 😎

**Comment by benbusby** [comment]
Fixed on master branch by afd5b9aa835e7f4d1e0e3cbd01bcaf3ccdf02af1 (direct commit since it was a minor change). Thanks for reporting!
