### ISSUE TITLE
[BUG] Results layout with NoJS enabled doesn't look great

### ISSUE THREAD

**Issue by gripped** [benbusby/whoogle-search#508]
**Describe the bug**
Pictures speak a thousand words. One result takes an entire page.

![old2](https://user-images.githubusercontent.com/3513053/139406232-c94080d6-7d86-41a3-ac3a-48092b863490.png)

imho no need for the `<br>`'s , no need for the `<hr>` and no need to display the link address.
Without
![new2](https://user-images.githubusercontent.com/3513053/139408631-a5fcfcb2-132d-4d0a-b21b-bf4b4e447938.png)
Still not quite right but I'll get to that.

**Comment by benbusby** [comment]
Yeah, I've been curious if anyone uses that feature as well. My inclination is to think that it is not used very often. I think it would probably get used a lot more if it was refactored to serve as a general website proxy feature that allowed users to open a result in Whoogle itself (using the same `/window` route), and conditionally enable/disable Javascript depending on user preference. I think there's actually an issue here for that somewhere, and wouldn't be too difficult to implement. Thoughts?

**Comment by drugal** [comment]
Two things to take from searx. [Morty proxy](https://github.com/asciimoo/morty) and [filtron](https://github.com/asciimoo/filtron)  . I think people would really like.
Morty is a web content sanitizer proxy.
Filtron protects against bots.
I used them as services outside of docker and everything went fine.

**Comment by gripped** [comment]
Morty is the the reason I just wanted to improve the look of the NoJS Layout. #276. 
I'm hacking Morty into the NoJS setting (because it's easy). Ideally Whoogle would be able to support a a range of HTML sanitizers. If not develop it's own ? But to be fair NoJS is a sanitizer as well.
Filtron I'm aware of, but don't know a lot about.
As always thanks Ben. Whoogle rocks ;)

**Comment by drugal** [comment]
Yeah, Whoogle rocks!!!
