### ISSUE TITLE
[BUG] 500 error with bangs.

### ISSUE THREAD

**Issue by ACodingGenie** [benbusby/whoogle-search#513]
**Describe the bug**
For some reason doing "!hd" bang causes a 500 internal server error. I was able to reproduce the issue with another two letter bang (not sure if its limited to just two letters) but don't remember what it was. Expected behavior if bang doesn't exist is just to search it as a term "!hd".

**To Reproduce**
1. Type in "!hd" into the browser or Whoogle's main page.
2. See the 500 internal server error message.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: ANY
 - Browser: ANY
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: ANY
 - OS: N/A
 - Browser: N/A

**Additional context**
![image](https://user-images.githubusercontent.com/68975831/139561652-37ae2b90-4a05-4270-ab25-b7e73978b6ad.png)

**Comment by benbusby** [comment]
Thanks for reporting! Fixed in https://github.com/benbusby/whoogle-search/commit/ddf951de35dabf1bfff65a1547caca1e41bd380c.
