### ISSUE TITLE
[BUG] CSS is completely broken

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#515]
To preface, this may be due to me switching from an virtualenv to `pdm`, or may be completely coincidental. But, for some reason, the logo is too big and there's no CSS applied.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/49244768/139599851-ea5f5390-dea2-4dd1-aff5-fe8917fe7fc7.png)

**Comment by benbusby** [comment]
It looks like maybe something you did broke the cache busting for the app. Can you try removing everything in `app/static/build/*` and re-running?

I've encountered this once before, and have been meaning to update the run script to clear out that directory before launch. I'll push an update shortly.

**Comment by DUOLabs333** [comment]
Yep, it's fixed now.
