### ISSUE TITLE
[BUG] code injection in results

### ISSUE THREAD

**Issue by fabi321** [benbusby/whoogle-search#518]
**Describe the bug**
I just spotted a code injection in snippets.
![Screenshot 2021-11-01 130845](https://user-images.githubusercontent.com/42294590/139669219-5a80a232-61a0-4d34-8c81-a96b8ffd5cc8.png)

**To Reproduce**
1. Whoogle `html selection list`
2. The snippet is the 3rd entry for me
[linked site](https://www.html.am/html-codes/forms/html-select-lists.cfm)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: clone from master and run locally

**Version of Whoogle Search**
- [x] Latest build commit c2ced230737572a286dcdc8cfd56ab83e60c990a
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox
 - 78.15.0esr
 - Language German.

The `Ähnliche Fragen` in the select indicates, that there should be similar questions below

**Comment by fabi321** [comment]
It also happens on regular results 
![Screenshot 2021-11-01 132236](https://user-images.githubusercontent.com/42294590/139670774-5661a1ae-6bf3-4b50-a41d-d985f487b0f6.png)

**Comment by gripped** [comment]
For what it's worth I can confirm.
Search term <textarea>
![tag](https://user-images.githubusercontent.com/3513053/139710760-25a3b6e2-f029-4192-a27c-142499251d2a.png)


Would it be possible to use something like https://pypi.org/project/bleach/ to escape all non whitelisted tags inside `<div class="BNeawe s3v9rd AP7Wnd">` ?
Whitelisting `a` `div` `span` `b` - (at first glance)
I've had a look but as per usual it's beyond my capabilities, and maybe I'm way off track ?
It's a shame there's not one specific use of `<div class="BNeawe s3v9rd AP7Wnd">` around each result. There always seems to be another three divs out/up?

**Comment by benbusby** [comment]
@gripped no need for all that, just needed to escape result contents before going through and bolding words from the original query.
