### ISSUE TITLE
[BUG] unhealthy on docker - though healthy and working

### ISSUE THREAD

**Issue by sutidor** [benbusby/whoogle-search#519]
**Describe the bug**

**To Reproduce**
1. Install whoogle container
2. see it being constantly unhealthy

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Additional context**
There is no publicly exposed port, whoogle is reverse proxied. Going into whoogle container terminal and `curl http://localhost:${EXPOSE_PORT}/healthz || exit 1` gives no return. curl -i and going to published url with browser gives me return code 200. How to fix?

**Comment by benbusby** [comment]
Hmmm, I'm not sure what the problem could be here. Could you run `docker inspect --format "{{json .State.Health }}" whoogle-search | jq` and share the results?

**Comment by sutidor** [comment]
dont know how to jq on ubuntu but here the `docker inspect --format "{{json .State.Health }}" whoogle-search`bit:
```{"Status":"unhealthy","FailingStreak":1714,"Log":[{"Start":"2021-11-08T10:37:29.387401171+01:00","End":"2021-11-08T10:37:29.454545693+01:00","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2021-11-08T10:42:29.457327157+01:00","End":"2021-11-08T10:42:29.524791178+01:00","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2021-11-08T10:47:29.527064049+01:00","End":"2021-11-08T10:47:29.5934602+01:00","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2021-11-08T10:52:29.595778319+01:00","End":"2021-11-08T10:52:29.683696621+01:00","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2021-11-08T10:57:29.686125891+01:00","End":"2021-11-08T10:57:29.762943074+01:00","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"}]}```

**Comment by benbusby** [comment]
Well that's odd...the Dockerfile uses `curl` and not `wget` for the healthcheck.

https://github.com/benbusby/whoogle-search/blob/3f40a6c485aa056d0ef5309d47966d4bcd1fd8a7/Dockerfile#L77-L78

Is it possible your Dockerfile is older than 0.6.0 due to changes that you've made locally? Either way somehow you've ended up with 0.6.0 code, but an old Dockerfile, which is strange.

**Comment by sutidor** [comment]
healthy!
I removed everything and started anew

**Comment by benbusby** [comment]
Awesome! Glad it's working now.
