### ISSUE TITLE
Option bar not showed if no language is selected in config

### ISSUE THREAD

**Issue by mada199122** [benbusby/whoogle-search#524]
**Describe the bug**
If no search language is selected in configuration before making a search no option bar is displayed 
I don't know the correct name but I'm referring to the bar where it is possibile to select the language and the time frame of the results. (see attachments)

Standard search on google.com always offer the possibility to show the bar.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Safari
 - Version 15.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOs 15.1
 - Browser Safari

**Additional context**
with language setting enabled (for example English)

![Screenshot 2021-11-05 at 08 37 27](https://user-images.githubusercontent.com/61902329/140474920-447d2587-79ef-4525-aabe-f07d120f37ab.jpg)

without language setting enabled

![Screenshot 2021-11-05 at 08 34 29](https://user-images.githubusercontent.com/61902329/140474568-7f042189-da58-4c2a-9e29-ba5d87bb14ba.jpg)

Normal google search

![Screenshot 2021-11-05 at 08 35 26](https://user-images.githubusercontent.com/61902329/140474787-d063aeb2-6bc5-4fa9-a691-f18448c806b2.jpg)

Example link:

https://www.google.com/search?q=outdoorgearlab&client=safari&source=hp&ei=qd6EYbTkAo2TwbkPxMW26Ac&iflsig=ALs-wAMAAAAAYYTsuUdvC1exBSjPiqp2YkG-uXx2CtvU&oq=outdoorge&gs_lcp=Cgdnd3Mtd2l6EAMYADIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgcIABCABBAKMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoLCC4QgAQQxwEQowI6BQguEIAEOgsILhCABBDHARDRAzoLCC4QgAQQxwEQrwE6DgguEIAEEMcBENEDEJMCOggIABCABBDJA1CPA1juF2C7H2gBcAB4AIABSYgB3ASSAQE5mAEAoAEBsAEA&sclient=gws-wiz

**Comment by 1uqtpfcn6hh8** [comment]
I have the exact same problem and the same configuration... I will  follow this tread for updates.

**Comment by benbusby** [comment]
This actually would be part of the feature request in #298, since that would involve fully replacing the Google returned search bar settings with one defined in the Whoogle header template itself. It's not really a bug with Whoogle, it's more of a limitation with how Google formats results for the no-JS version of their response page. 

Merging with #298.
