### ISSUE TITLE
[BUG] ERNO 98 in REPLIT Instance

### ISSUE THREAD

**Issue by vacom13** [benbusby/whoogle-search#531]
**Describe the bug**
This is an issue of the replit instance. At times it gives me an os error `[ERNO 98] Address already in use` when I go to rerun the instance after closing the browser tab once. The reason that I found for the same is that the file is still present in the process stack after the last run.

Once this happens, it shows whoogle in a browser tab even though replit doesn't show that it is actually still running. Any changes I would make to the code wont show up till I rerun the instance but this is where the issue is as replit just shows the following after I click on run.

![Bug whoogle](https://user-images.githubusercontent.com/69755265/141137835-330aaffe-2c64-4789-b02a-492b94f17b3b.jpg)

P.S. The whoogle instance that shows up in the browser is from the last runtime and therefore doesn't have any new modifications

**To Reproduce**
1. Fork a Replit instance
2. Click on run
3.  Stop running the instance and close the browser tab
4. Try rerunning the instance and see the error.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [describe setup] Replit Instance

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop:**
 -
![Bug whoogle](https://user-images.githubusercontent.com/69755265/141137740-9cd8508f-67cf-4cf0-bfff-82057df31e9f.jpg)
 OS: Windows 11 Build 22494
 - Browser: chrome
 - Version: Version 95.0.4638.69

**Smartphone:**
 - Device: N/A
 - OS:  N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
I suppose, this is an error related to replit. However a fix I found for the same would be to run `kill -9 $(ps -A | grep python | awk '{print $1}')` in the terminal before rerunning the instance. I was thinking that maybe we could just add this to the `.replit` file to automate the running of this command in the terminal thereby making sure that the service has stopped in process stack.
Refer to  `https://stackoverflow.com/questions/4465959/python-errno-98-address-already-in-use` for more context.

**Comment by Albonycal** [comment]
it's because the old one is still running 
do `killall -q python3` and then start whoogle again.. 
;)

**Comment by vacom13** [comment]
I get that part. I was thinking that maybe it could just be implemented it so that the command runs everytime the button is clicked, making sure the user doesn't have to maybe?

**Comment by benbusby** [comment]
Should probably target by port, i.e. `kill $(lsof -t -i:5000)` or something, rather than just a blanket kill command for `python`. Otherwise yeah sounds like a good idea. I'll try to add it soon, or someone else can if they want.
