### ISSUE TITLE
[BUG] Tor searches fail without message

### ISSUE THREAD

**Issue by thunderclap82** [benbusby/whoogle-search#532]
**Describe the bug**
I have Whoogle running in an Unraid container and the main GUI comes up fine, but whenever I search for something it gets stuck and never finds anything. I saw there was a recent update to the container so I did that but it didn't fix the problem.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [X] Version 0.6.0
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.31.91 (based on Chromium: 95.0.4638.69)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 15.1
 - Browser: Brave
 - Version: 1.31.91 (based on Chromium: 95.0.4638.69)

**Additional context**

**Comment by Coolykoen** [comment]
For me, it looks stuck aswell, and like you, i do see the main search bar and whoogle logo, but once i type in something and press enter, it gets stuck.... **or so i thought**, for me, after about a full 2 minutes it does come through sometimes... other times it times out and i get internal server error 500

**Comment by eddydc** [comment]
I don't get anything else than server 500 error. Restarting the container doesn't work either. This makes that whoogle doesn't work at all anymore.

**Comment by Coolykoen** [comment]
To be fair, there was a big google server problem hours ago, maybe that had to do something with it...

**Comment by thunderclap82** [comment]
> To be fair, there was a big google server problem hours ago, maybe that had to do something with it...

Google itself works, though. I’m wondering if they made a change to the API that breaks how Whoogle works?

**Comment by benbusby** [comment]
Not able to reproduce on Heroku, VPS, or local instances. Can you confirm if it's still happening for you? If it is, can you clarify the geographic region your instance is running in?

**Comment by thunderclap82** [comment]
> Not able to reproduce on Heroku, VPS, or local instances. Can you confirm if it's still happening for you? If it is, can you clarify the geographic region your instance is running in?

It still is happening but it's a little different now. It tries searching for a little over a minute and then the search box clears out and that's it. No results.

I'm in Illinois, US.

**Comment by eddydc** [comment]
It seems to work over here (Belgium, Europe). Whatever the reason might be, Whoogle shouldn't return an internal server error when something is going wrong on the Google side.

**Comment by benbusby** [comment]
Issue was privately determined to be caused by "Tor mode" in Whoogle. There's a failure with parsing the result when Google blocks the exit node from performing a search.
