### ISSUE TITLE
Host Whoogle on Fosshost

### ISSUE THREAD

**Issue by richmailYT** [benbusby/whoogle-search#533]
**Describe the feature you'd like to see added**
Fosshost is a free FOSS hosting platform with many more CPU cores then Heroku or Relp.
I suggest you apply for an application there to host Whoogle.

**Additional context**

**Comment by Albonycal** [comment]
afaik FOSSHost isn't for "personal" use?

**Comment by richmailYT** [comment]
> afaik FOSSHost isn't for "personal" use?

I ment a public instance. All the other ones are a bit slow

**Comment by Albonycal** [comment]
yea IK.. mine was hosted on a VPS, but not anymore (broke af )
it runs on replit now

**Comment by benbusby** [comment]
I don't think they would want to host Whoogle. They explicitly state that they don't host projects that promote "anonymous internet services" (which is vague, but could be used as a disqualifier for Whoogle), but I'll try to get in touch with them to clarify.

**Comment by richmailYT** [comment]
> I don't think they would want to host Whoogle. They explicitly state that they don't host projects that promote "anonymous internet services" (which is vague, but could be used as a disqualifier for Whoogle), but I'll try to get in touch with them to clarify.

I think they mean onion services. Tell me what they say when they get back to you

**Comment by benbusby** [comment]
@richmailYT they sound open to hosting it on their platform. I'm working with them now to get an instance set up.

**Comment by richmailYT** [comment]
@benbusby Great!

**Comment by dragstor** [comment]
I was going to write that you're very welcome to apply, but I just checked and found out that you already did and that your application was approved! ☺️ 

🎉

**Comment by Albonycal** [comment]
nicee
