### ISSUE TITLE
[FEATURE] Considering to use much secure session cookie.

### ISSUE THREAD

**Issue by nakoo** [benbusby/whoogle-search#539]
**Describe the feature you'd like to see added**
Whoogle should only use session cookie when HTTPS is enforced so that we can improve the security by adding `__host` (OR `__secure`) prefix and `Secure` flag. Current set-cookie header is not secure option.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

![mo1](https://user-images.githubusercontent.com/4975021/142615672-7f0d29ae-f294-4794-9564-76321226be9d.png)

![mo2](https://user-images.githubusercontent.com/4975021/142615692-36d81785-7c33-4910-b47c-6f140a3caadc.png)

(screenshots from Mozilla Observatory)

**Additional context**
Since Whoogle now use much better implemetation of disabled cookie situation (#480), now we can enforce HTTPS to use session cookie. I think it's good time to do so.

**Comment by benbusby** [comment]
Added -- these values are only set when the `HTTPS_ONLY` var is set though. Otherwise instances running in local networks w/o SSL wouldn't be able to use sessions anymore. 

Thanks for the suggestion!
