### ISSUE TITLE
[FEATURE] Another search parameter to set region

### ISSUE THREAD

**Issue by msoxzw** [benbusby/whoogle-search#544]
Current Whoogle uses `cr` to set search region:
https://github.com/benbusby/whoogle-search/blob/0c5578937eec7f23a8921439e0e7cde1ef669271/app/request.py#L123

However, I suggest that `gl` is a better search parameter to set search region. Please compare the following search results from Google:

https://www.google.com/search?q=yuyuyu
https://www.google.com/search?q=yuyuyu&gl=JP
https://www.google.com/search?q=yuyuyu&cr=countryJP

The result of "https://www.google.com/search?q=yuyuyu&gl=JP" is identical to the Google Japan. Because "Yahoo! Japan search" is based on Google search, the result of "Yahoo! Japan search" is nearly identical to the Google Japan, and hence, it is easy to verify the result from Google Japan by visiting "https://search.yahoo.co.jp/search?p=yuyuyu".

Furthermore, Whoogle instances from different regions may get varying search results if the search region parameter is set to empty, so it is better to set certain default region (e.g. US) to get uniform search results.

**Comment by benbusby** [comment]
Not necessarily a "bug" imo, but a good recommendation nonetheless. I had no idea about that search parameter! I'll try to implement this soon -- this would be a huge help for instances hosted outside of a user's country.

**Comment by benbusby** [comment]
Implemented now on `main`. Thanks again for pointing this out, that's super helpful.
