### ISSUE TITLE
Unable to deploy on render website

### ISSUE THREAD

**Issue by getredy** [benbusby/whoogle-search#55]
Deploy failed on [Render](https://render.com) with exit status 1.
please check the issue.

Here are the some last lines of deploy logs:

INFO[0098] ARG config_dir=/config
INFO[0098] RUN mkdir $config_dir
mkdir: cannot create directory ‘/config’: File exists
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
error: exit status 1

the earlier 5-6 days ago build code got deployed without any issues.

**Comment by benbusby** [comment]
Fixed as of 601923e07449befa12c7e527213062370817ae3c. Please try with the latest version of the app, and reopen if this didn't fix it for you. Thanks!
