### ISSUE TITLE
[BUG] Query decryption issue

### ISSUE THREAD

**Issue by FourPeaksAdmin** [benbusby/whoogle-search#553]
**Describe the bug**
When doing a whoogle search, the request comes up in search perfectly fine, but then when switching to images, the address gets messed up and enters from arbitrary search query

**To Reproduce**
1. Go to whoogle hosted address
2. Search something and return results
3. Switch to images tab
4. Get arbitrary result

**Deployment Method**
- [ x] Docker

**Version of Whoogle Search**
- [x ] Version [0.6.0]

"Docker Network Traffic Monitor" becomes "gAAAABhn...." when switching from ALL to Images

![image](https://user-images.githubusercontent.com/57915142/143085095-af2ec32f-9ea8-482e-8f7a-e732967b657e.png)

![image](https://user-images.githubusercontent.com/57915142/143085124-f4a9988f-7cf4-45e3-8abf-212657699cf6.png)

**Comment by benbusby** [comment]
It looks like your instance is failing to decrypt your search queries. The second string you're seeing is the encrypted contents of the search, but somehow your session key is being reset between actions.

<img width="963" alt="Screen Shot 2021-11-23 at 12 36 04 PM" src="https://user-images.githubusercontent.com/33362396/143092017-d5631787-82e1-4dd1-bc8c-b9b2d307fcdf.png">
<img width="952" alt="Screen Shot 2021-11-23 at 12 36 14 PM" src="https://user-images.githubusercontent.com/33362396/143092034-c4ff9932-a747-4d96-867a-ce5d097d60e7.png">

What browser are you using? Do you have any plugins enabled that block cookies? 

Also, are you pulling the `0.6.0` tag or the `latest` tag (which also shows "Version 0.6.0" on the home page)?

**Comment by benbusby** [comment]
Also, for future reference, it's usually best to blur out or crop out your actual search URL in screenshots unless you want other users using your instance.

That being said, I was able to navigate to your instance home page and perform the same steps (search something -> switch to other result tab) without any issues. I'm guessing this is an issue with how your browser is performing the search, since it looks like you're searching using your browser's URL bar to perform the search. I'm curious if somehow the session key is being reset that way. 

If you're not already, I'd recommend using the `latest` docker tag for now.

**Comment by FourPeaksAdmin** [comment]
> Also, for future reference, it's usually best to blur out or crop out your actual search URL in screenshots unless you want other users using your instance.
> 
> That being said, I was able to navigate to your instance home page and perform the same steps (search something -> switch to other result tab) without any issues. I'm guessing this is an issue with how your browser is performing the search, since it looks like you're searching using your browser's URL bar to perform the search. I'm curious if somehow the session key is being reset that way.
> 
> If you're not already, I'd recommend using the `latest` docker tag for now.


I am using the latest image pulled ```image: benbusby/whoogle-search:latest```

I also tried navigating to the search url and just doing a search from within there and like you, am not experiencing this issue.

This is the search query url I have baked into the custom search for the address bar
```https://search.fourpeakslandscape.com/search?lr=&safe=off&gbv=1&nfpr=1&q=%s```

As for showing my public instance, Im not concerned as I can just change the url in traefik and I can use the new URL, but thank you for the the reminder as I did technically space on that part lol.

**Comment by benbusby** [comment]
> Looks like it must be a glitch in the matrix because its not happening anymore in vivaldi right now. Must just be a random thing that happens. But, since its not happening currently, not much to go on so maybe just close the ticket?

Hmm. I'm curious why you would've encountered the issue in the first place, but I'll just close the issue in the meantime. My best guess is that something weird happened where either Vivaldi performed the search without a valid session (so using the app's default encryption key), but the next action you took (switching result tabs) had a valid session and was using a different key (and therefore unable to decrypt the query properly).

**Comment by accountForIssues** [comment]
@benbusby I can replicate this issue (latest docker version as of Feb 16).

If I right click search a word in Firefox (Android or Fedora Linux) or Chromium, the search page URL is `https://whoogle-instance/search?cookies_disabled=1` and when I click on next (page of results), the issue in OP appears.

The cookies are not disabled as I can see a cookie stored using Dev Tools. Also, the same cookie is used fine for subsequent searches.

Further, in the initial page of results, any images/resources don't appear so there is definitely an issue with decryption. 

![image](https://user-images.githubusercontent.com/52367365/154423438-01affd00-dc5f-4a24-a22f-6fa6f0c40c5c.png)

However, if I click on a different result tab such as images/videos, the search works properly. If I then go back and click next, the next page also works fine. So, switching result tabs lets Whoogle know of the local session so the subsequent requests are properly decrypted.

I noticed that switching result tabs perform a GET request with plain text query whereas going to the next page of results sends an encrypted query.

Can anything be done on Whoogle's side ? Like if Whoogle cannot detect a valid session (I assume that's what's happening in the initial request), then the `Next` page should also be requested using plain text GET.
