### ISSUE TITLE
[FEATURE] Farside integration

### ISSUE THREAD

**Issue by benbusby** [benbusby/whoogle-search#554]
**Describe the feature you'd like to see added**
[Farside](https://github.com/benbusby/farside) (https://farside.link) is a new project that facilitates "intelligent" redirecting between available (i.e. active, not rate-limited, etc) public instances for frontend alternatives such as Nitter, Bibliogram, and Whoogle. 

For Whoogle in particular, it would be useful to have a simple page appear if an instance is being blocked by Google (via captcha or otherwise) with a link for easily hopping to a different available instance via Farside. My initial thought is something like:

`https://farside.link/whoogle/search?q={query}&{config options}`

Obviously this means expanding on the current support for embedding config options as URL params, but that shouldn't be too hard. 

This (combined with 3c065191308c3acebf3cc0086c485da75e3a36aa) will allow users to not have to be tied to one particular public instance of Whoogle, and can quickly pick up where they left off on a new instance if their default instance is blocked. 

Additionally, this could allow users to manually set `https://farside.link/whoogle/search?q=%s` as their preferred search engine in order to always be directed to a randomized, working instance of Whoogle for every search. 

**Additional context**
This would require all public instances to update to a specific version before being included as instances in Farside. Currently all available instances are included as possible options for Farside to choose from, but that would need to change if updates are made to the available URL parameters.

**Comment by Albonycal** [comment]
> This (combined with 3c06519) will allow users to not have to be tied to one particular public instance of Whoogle, and can quickly pick up where they left off on a new instance if their default instance is blocked.

This would be awesome

**Comment by benbusby** [comment]
Right now it works just by providing a URL to use for redirecting (i.e. `farside.link/nitter/username`), which is useful for services like Whoogle that can replace Twitter/Instagram/etc links with Farside links instead. A browser extension could be useful, but imo the better option would just be integrating Farside links into an existing browser extension like Privacy Redirect. That way users can just set it to randomly pick an *available* Nitter/Libreddit/etc instance rather than picking a specific instance that may or may not work, or having a randomly chosen instance that also might not work.

**Comment by Albonycal** [comment]
yea, I have run into instances that do not work while using privacy redirect. 
that's why I run my own, some on my proxmox (at my home) and some on things like replit..
if you are interested https://monitor.albony.xyz/ 
this has some services that I host and their status ;)

**Comment by Albonycal** [comment]
https://github.com/SimonBrazell/privacy-redirect/issues/329
