### ISSUE TITLE
[BUG] Whoogle logo misaligned on smartphone

### ISSUE THREAD

**Issue by nakoo** [benbusby/whoogle-search#557]
**Describe the bug**

At latest version, Whoogle logo doesn't align the position in search page.

**To Reproduce**
1. Pull the latest verison
2. Update Whoogle instance
3. Search anything and check the logo position

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [not related]
 - Browser [not related]
 - Version [not related]

**Smartphone (please complete the following information):**
 - Device: [not related]
 - OS: [not related]
 - Browser [not related]
 - Version [not related]

**Additional context**

![whoogle](https://user-images.githubusercontent.com/4975021/143670562-1b49ff90-3fee-4167-bd1f-14a5a9db0deb.png)

**Comment by benbusby** [comment]
Why did you not fill out the `Smartphone` section of the bug report? It's clearly related since you're using a phone, and the pixel density of the device is what's causing the logo to be offcenter.

**Comment by benbusby** [comment]
It ended up being a simple fix, but please fill out the whole bug report next time.

**Comment by nakoo** [comment]
> It ended up being a simple fix, but please fill out the whole bug report next time.

Because it doesn’t mean to the specific OS. The logo position changes by screen width and that’s how CSS media query work. It happens all the time on Mobile and Desktop. Also, to better understand, I always give you screenshot when pushing the issue. Man, I’m helping you to fix the bug.

**Comment by nakoo** [comment]
I pulled and checked the latest version. You didn't fix it properly. Current commit makes another problem to fix this issue. You need to make logo wrapper and align that one instead of logo itself.

![not-fixed](https://user-images.githubusercontent.com/4975021/143774282-62b61957-d477-4eca-a597-41395b2811c6.png)

**Comment by nakoo** [comment]
I believe it's very simple fix, but if you need a help, I can do PR. Please let me know. I want to mention that I'm here to contribute your project.

**Comment by nakoo** [comment]
@benbusby I believe it's very simple fix, but if you need a help, I can do PR. Please let me know. I want to mention that I'm here to contribute your project.

**Comment by benbusby** [comment]
@nakoo should be fixed now via f73e4b9239e767ddd3e2a62de3acee4d09bb2545. If it isn't, feel free to open a PR -- I'm not a frontend/CSS expert, so I appreciate any help in that regard.
