### ISSUE TITLE
[QUESTION] How to use social media alternatives using url parameter

### ISSUE THREAD

**Issue by specter78** [benbusby/whoogle-search#559]
The official instance, by default, doesn't use social media alternatives.

Since I am using Cookie AutoDelete extension, if I change config, it won't persist. 

So is it possible to do this via url parameter?

**Comment by benbusby** [comment]
At the moment, no, but will be added within the next few days (if not sooner). The feature for including config options in the URL is mostly finished, just need to tweak a few things first.

**Comment by vlfldr** [comment]
You can add the urls of public instances you use to CAD's whitelist. Then the cookie will not be deleted and your settings should persist.

**Comment by benbusby** [comment]
@specter78 with the latest commit to `main`, you can now enable social media alternatives as a url param via (`alts=1`).

**Comment by specter78** [comment]
@benbusby I don’t think it’s working. I open `https://whoogle.fossho.st/?alts=1`, search for say `twitter`, it should show twitter alternatives, but that’s not happening. 

Am I missing something?

**Comment by specter78** [comment]
Also, how to specify country in url param?
