### ISSUE TITLE
[BUG] Even if `WHOOGLE_CONFIG_GET_ONLY` is 1, Whoogle picture requests are still POST.

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#561]
**Describe the bug**
Whoogle image requests are POST, even if you set it to be GET.

**To Reproduce**
1. Search up something
2. Go to `Images`
3. Search up something else while on `Images`
4. See request is `POST`

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Arch Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 88

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azukaar** [comment]
@benbusby I can still experience the issue in v0.7.2
 - set WHOOGLE_CONFIG_GET_ONLY to 1
 - in the configuration panel, the checkbox is not set
 - searches are not going throught get

**Comment by DUOLabs333** [comment]
Weird, it no longer happens to me. Try pulling from latest.

**Comment by azukaar** [comment]
v0.7.2 is latest right ? I have the docker tag latest and i tried to restart the container, let me know if you have another idea what I can try

**Comment by DUOLabs333** [comment]
No, latest means pulling from the latest commit.

**Comment by azukaar** [comment]
Yes that is my setup, the version number happened to be 0.7.2 but it's pulling from the latest commit tag, i just re-created it just in case something was wrong with docker but no I definitly have latest version

**Comment by azukaar** [comment]
Sure thing !

![image](https://user-images.githubusercontent.com/7872597/172676236-94657cdc-d20f-422a-acc6-de9d27863940.png)

**Comment by DUOLabs333** [comment]
How can you tell the image requests are POST?

**Comment by azukaar** [comment]
OK I just re-read the ticket, I didn't realise the ticket was specifically about pictures, sorry. In my case, the research, as in type in words in the textbox and go, uses POST request instead of GET (As in I dont have any ?q=... in the URL)

**Comment by DUOLabs333** [comment]
Can you show me your docker compose? If the checkbox is not set, that could be a configuration error, not a Whoogle error.

**Comment by azukaar** [comment]
I'm using Portainer so I set the ENV from a UI (see the screenshot above for environments variables I have set)
Notice that I have set other parameters, such as the country through those ENV, and they are all working except WHOOGLE_CONFIG_GET_ONLY

![image](https://user-images.githubusercontent.com/7872597/172686448-aea6aabc-0c87-4223-b928-def12662edd9.png)

**Comment by DUOLabs333** [comment]
Can you try with plain Docker? I'm just trying to narrow down the issue.

**Comment by azukaar** [comment]
The search is acting this way both from the search bar in FF, and from the input in the Whoogle UI
Also the checkbox is not ticked when I check the config
Is there way to see in Whoogle what config is coming from the server?

**Comment by DUOLabs333** [comment]
I don't know much about Docker, but if you can edit the code in the container temporarily, go to `config.py` and add `print(self.get_only)`, then look at the logs.

**Comment by azukaar** [comment]
OK i dont really want to start tinkering with the code and everything to be honest. What I did do though, is simply execute `env` in the docker container to show that the docker part is fine:

![image](https://user-images.githubusercontent.com/7872597/173342159-eb82e558-bc2a-40fc-b52f-1db509b97077.png)

So it is indeed Whoogle not picking it up

**Comment by benbusby** [comment]
@DUOLabs333 @azukaar yes, it should be changed `1` or `0` for true or false. Environment variables can't have boolean data types, so setting it to "true" or "false" is just evaluated as a string, which Whoogle would interpret as "true". Whoogle does include logic to at least evaluate `1` as true and `0` as false though, so that's the preferred way to enable/disable configuration fields.

**Comment by azukaar** [comment]
> yes, it should be changed 1 or 0 for true or false

It does work with 1  /  0 thanks

> Environment variables can't have boolean data types

No they can't but usually progams parse the environment variables properly and interpret the string into multiple formats. ENV variables ARE strings they can't be numbers either, they are always strings that will contain characters, numbers, boolean, etc... and get parsed by the program

**Comment by hmajid2301** [comment]
I experienced something similar in my `/etc/default/whoogle` config file, it was not picking up my `WHOOGLE_CONFIG_GET_ONLY=`1 until I added quotes around the `1` like so `WHOOGLE_CONFIG_GET_ONLY="1"`.

Just posting in case someone else comes across this bug.
