### ISSUE TITLE
[BUG] Search results seem to be under safe search despite turned off safe search (Only happen on Replit deployment)

### ISSUE THREAD

**Issue by beam2546** [benbusby/whoogle-search#563]
**Describe the bug**
When search for NSFW website (eg. Pornhub, XVideos, nhentai), search results will be very off-topic or even not appear at all despite turned off safe search. This seem to happen only on Replit deployment as I can't reproduce it on Heroku deployment.

**To Reproduce**
1. Deploy Whoogle on Replit
2. Search for any NSFW website
3. Search results will be very off-topic or not appear at all

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [describe setup]

Replit deployment with default setting

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox Developer Edition and Brave
 - Version
     - Firefox Developer Edition: 95.0b12
     - Brave: 1.32.113

**Comment by benbusby** [comment]
I'm not sure if there's anything I can do about this really. It's possible that the repl.it network is being handled differently by Google, although I'm not sure why that would be the case. Maybe some kind of agreement they have to filter certain types of search traffic coming from their network? 

If you need to deploy on repl.it in particular, I think the only resolution if you need to deploy on repl.it would be to enable a proxy to pass searches through a different machine first. There are some instructions in the README on which variables to set to enable a proxy. 

Sorry, I know that's probably a disappointing answer. Whoogle should run identically regardless of where it's deployed, but there's a lot of "magic" on Google's end that I don't/can't control.

**Comment by beam2546** [comment]
Don't worry. I understand that Google have lot of thing behind the scene that out of this project scope. I just write here to let you know that this issues exist. I already deploy it on fly.io instead and it work great!
