### ISSUE TITLE
Replit lsof command not found

### ISSUE THREAD

**Issue by JuenTingShie** [benbusby/whoogle-search#564]
**Describe the bug**
https://github.com/benbusby/whoogle-search/blob/7bea6349a00c7df51005ecba181d412fcdf4a3bd/.replit#L2

Well, this problem is there for a long days, but I just new this issue since now.

Seems like replit don't have **lsof** command, please see image below
![圖片](https://user-images.githubusercontent.com/31978492/145151176-caa37e06-1ef2-4182-847c-6a03cb05b0e4.png)

I know it's trying to kill exist app, but apparently it may not working?

but after this, whoogle still work thought, just don't know if this command is wrong or something.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: replit

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by DUOLabs333** [comment]
Can't you just ignore it?

**Comment by Albonycal** [comment]
that command isn't "required"
you can add `install_pkg lsof" to the top of .replit file if you don't want
to see that error

**Comment by JuenTingShie** [comment]
I'm not meant to pick little problems, just because this commit is "kill opening app before re-run", without **lsof** , in my opinion,it's not actually work, maybe just add install lsof before it will better.

So far, I do enjoy using whoogle, and I do want to contribute something, so I start from this kind problem.

**Comment by benbusby** [comment]
I don't use replit, so someone else would likely be a better candidate for fixing this.

@Albonycal have you tested if that works? If so, can you submit a PR? I can't find any official documentation from replit on how `install-pkg` works, just some old forum posts that I'd rather not trust.

**Comment by Albonycal** [comment]
K, so install_pkg is actually the intended way to install packages that
aren't installed by default..
it sort of "elevates" the privileges for apt
(replit instances don't have root access)
and yea it works
I will make a PR tomorrow :D
(it's 11:21pm here)

**Comment by Marcusgarveyy** [comment]
Can you teach me

**Comment by Albonycal** [comment]
add this to the starting of .replit`install-pkg lsof &&`

**Comment by Albonycal** [comment]
add this to the starting of .replit`install-pkg lsof &&`
