### ISSUE TITLE
Can I specify location?

### ISSUE THREAD

**Issue by rstefko** [benbusby/whoogle-search#565]
Normally Google detects location based on the IP address. It works most of the time even in Whoogle, but sometimes it starts giving results from another location. I am not talking about Country filter in search. But eg. when you search "2pm PST" it tells you what is the time in your location, which is currently wrong.

**Comment by benbusby** [comment]
I think the solution would be to set the `near` config value to a location in your timezone. Setting that field to various cities (Los Angeles, Denver, New York) seems to adjust how time results are returned at least. If that doesn't work for you, then I'm not sure any of the current search params would help, but I'd be willing to keep investigating.

**Comment by rstefko** [comment]
It helped with the search term. But in the search suggestions while typing search term, it still gives me some weird suggestions, it still thinks that I am somewhere in Taiwan or something like that.

![image](https://user-images.githubusercontent.com/4289079/145566041-42ecea6c-e4e5-45b2-ae24-04bc7e2eacb3.png)

**Comment by rstefko** [comment]
The VPS has IPv6, so Google probably was guessing the location based on IPv6. I have disable it and it looks OK now.
