### ISSUE TITLE
hello there

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [benbusby/whoogle-search#566]
guys recently i tried to use whoogle (in the 0.3.1 version) and a google captcha came out when that happened it wasn't displaying well so what can i do
![Captura de pantalla (3849)](https://user-images.githubusercontent.com/86683930/145438002-86d406fb-1d5a-4c9c-bdb3-7a858aa3f972.png)

**Comment by Albonycal** [comment]
were you the  one who tagged me on twitter ? 😅
you are getting the error because that instance doesn't work
try another instance

**Comment by benbusby** [comment]
Yeah, the `whoogle.sdf.org` instance hasn't been updated for a long time and seems to no longer be maintained. You can visit https://github.com/benbusby/whoogle-search#public-instances for a list of active public instances, or https://farside.link to see which ones are currently not blocked.
