### ISSUE TITLE
Whoogle not working (Unusual traffic error)

### ISSUE THREAD

**Issue by cinetube** [benbusby/whoogle-search#567]
Type out your question here. Please make sure that this is a topic that isn't already covered in the README.
![Screenshot 2021-12-09 230736](https://user-images.githubusercontent.com/23441775/145443105-5ff5d2e1-cd71-4ad5-8582-e5e4145c2d89.jpg)

Whoogle not working (Unusual traffic error). How can I solve this issue. 

This is the first time I am facing this issue.

**Comment by benbusby** [comment]
This is likely the same issue as #558, follow that issue for updates. It seems to potentially be caused by Google cracking down on residential Whoogle instances, and possibly triggered by searching for technical topics (such as "tor in docker").

**Comment by cinetube** [comment]
> This is likely the same issue as #558, follow that issue for updates. It seems to potentially be caused by Google cracking down on residential Whoogle instances, and possibly triggered by searching for technical topics (such as "tor in docker").

I searched with other topics too. I received similar result.
