### ISSUE TITLE
Instance has been ratelimited

### ISSUE THREAD

**Issue by cinetube** [benbusby/whoogle-search#568]
![Screenshot 2021-12-09 233819](https://user-images.githubusercontent.com/23441775/145447525-062c647d-5614-4c87-9778-0d0b6f4dd2b2.jpg)

How to resolve this issue?

**Comment by benbusby** [comment]
See my comment on your other issue.

**Comment by gaditano66** [comment]
I don't understand. It also happens to me but I can't find the solution or the comment on the other issue.
Is there a solution or it's only Google related and impossible to solve?
Thanks
