### ISSUE TITLE
[Question] About deployment 

### ISSUE THREAD

**Issue by eoopx** [benbusby/whoogle-search#57]
Is it possible to deploy this to https://vercel.com/pricing? if so hint me a short guide

https://github.com/benbusby/whoogle-search/issues/23

**Comment by benbusby** [comment]
Merged into #62, I'd rather not keep track of everyone's preferred deployment methods on an issue-by-issue basis.

**Comment by eoopx** [comment]
@benbusby how long takes to write guide for it then? if takes long then expect quick help.
