### ISSUE TITLE
[QUESTION] How to preserve settings?

### ISSUE THREAD

**Issue by emarcelcom** [benbusby/whoogle-search#578]
I run Whoogle in docker. Every Time I restart the web browser all settings are back to default. How to preserve **configuration** settings such as Set Country, Interface Language, Search Language, Open Links in New Tab, and so on ?

**Comment by xaabi6** [comment]
I'm not completely sure but in docker you will probably need to pass the environment variables every time you deploy the container, maybe you could use docker-compose, it makes this task easier.
