### ISSUE TITLE
[BUG] Wrong banner: Whoogle Search v0.7.0 || View on GitHub

### ISSUE THREAD

**Issue by emarcelcom** [benbusby/whoogle-search#579]
**Bug description**
Wrong footer: Whoogle Search v0.7.0 || View on GitHub
I guess the latest release is 0.6.0 
Docker image: benbusby/whoogle-search TAG: latest

**Comment by xaabi6** [comment]
Last release was v0.6.0 and since then there have been multiple changes, so technically the 0.7.0 banner is correct, I think that @benbusby just forgot to publish the release.

**Comment by benbusby** [comment]
Didn't forget, just bumped the version too soon (was still testing a few new features).

Just released 0.7.0 though.
