### ISSUE TITLE
[BUG] [Firefox] Can't add search engine

### ISSUE THREAD

**Issue by xLeon-python** [benbusby/whoogle-search#588]
**Describe the bug**
My Whoogle instance is running behind a nginx reverse proxy. When trying to add the search engine to Firefox, I get the following error:
`Firefox could not download the search plugin from: https://search.domain.xyz/opensearch.xml `
The file is reachable when searching for https://search.domain.xyz/opensearch.xml 
The search itself works perfectly.
Root URL is set to: https://search.domain.xyz/

**To Reproduce**
1. Go to root page
2. Click on the add button
![Screenshot from 2021-12-21 21-11-19](https://user-images.githubusercontent.com/53626026/146992520-55e84829-82d9-4163-a6a8-04c287d50ad7.png)
3. See error

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: Latest (95.0.1)

**Comment by DEvmIb** [comment]
same problem. seems to be an problem with the session redirect.

< HTTP/2 307
< date: Sat, 08 Jan 2022 10:39:50 GMT
< content-type: text/html; charset=utf-8
< content-length: 413
< location: http://whoogle/session/34ca0683-e14e-4670-8eed-280d6d28988e?follow=http%3A%2F%2Fwhoogle.lsf-group.de%2Fopensearch.xml
< server: waitress
< set-cookie: session=c5944a45-1277-47ac-aaab-db47685b2f3f; Expires=Sun, 08-Jan-2023 10:39:50 GMT; HttpOnly; Path=/; SameSite=Strict
< x-content-type-options: nosniff
< x-frame-options: DENY
< x-robots-tag: noindex, nofollow, noarchive, nosnippet, noimageindex, notranslate

**Comment by DEvmIb** [comment]
my solution until fix is to serv static file on nginx

`location /opensearch.xml { alias /data/opensearch_whoogle.xml; }`

**Comment by DUOLabs333** [comment]
Weird -- it works for me (though I'm on 88). Can you post your nginx config?

**Comment by xLeon-python** [comment]
I built the latest docker version but it does not work. I still get the same error when trying to add the search engine.

**Comment by anarkia47** [comment]
I currently also  have this issue.

Found this workaround, 

https://old.reddit.com/r/firefox/comments/1246l41/is_there_a_way_to_make_firefox_recognize_rlinks/jdy0eq7/?context=999
