### ISSUE TITLE
[FEATURE] Bangs without any search term should redirect to the homepage

### ISSUE THREAD

**Issue by lenicyl** [benbusby/whoogle-search#595]
Currently Whoogle bangs work this way  : 
`!yt <search term>` redirects to `https://www.youtube.com/results?search_query=<search term>`  which is nice 

However if you use the bang `!yt` without really adding any search terms it again redirects to `https://www.youtube.com/results?search_query=` which is somewhat annoying 

It would be nice if it were to be changed so that if a search term isnt used, it redirects to the homepage, which in the examples used above would mean `!yt` redirects to `https://youtube.com`

**Comment by Albonycal** [comment]
hmm maybe I could work on this 
@benbusby

**Comment by benbusby** [comment]
@Albonycal sure. You'd just need to modify `app/utils/bangs.py -> resolve_bang()` to make sure the URL replacement value isn't empty first. So something like (pseudocode-ish):

```py
def resolve_bang
    # ... rest of function ...
    bang_query = query.replace(operator if operator in split_query
                               else operator[1:] + operator[0], '').strip(), 1)
    if bang_query:
        return bangs_dict[operator]['url'].replace('{}', bang_query)
    return ''
```
