### ISSUE TITLE
Publish to dockerhub

### ISSUE THREAD

**Issue by FoxxMD** [benbusby/whoogle-search#6]
Please publish and tag a build of the docker image to [dockerhub](https://hub.docker.com/) so applications like unraid can take advantage of whoogle-search.

**Comment by spike-the-coder** [comment]
This would be great!

**Comment by BadCo-NZ** [comment]
Please also document the variables well so it is easy to template :)

**Comment by ilovepancakes95** [comment]
Yes, this would be great to have. This project looks well done, nice job! Can't wait to test it out.

**Comment by benbusby** [comment]
Done -- https://hub.docker.com/r/benbusby/whoogle-search

Feel free to reopen if I missed anything!
