### ISSUE TITLE
[QUESTION] Why is /config mounted while not using it?

### ISSUE THREAD

**Issue by Akruidenberg** [benbusby/whoogle-search#606]
I have a unnamed volume for the /config mount. However, because I'm using tmpfs, the volume is not used.  Every time i recreate the container, the volume is recreated. How to remove this volume permanently?

**Comment by benbusby** [comment]
You'd need to remove the following lines from the Dockerfile before recreating the container:

https://github.com/benbusby/whoogle-search/blob/31f4c00aee430117d96860bae361c6408b9e0c1f/Dockerfile#L20-L22

**Comment by simonmcnair** [comment]
Odd question but this happens in your uploaded docker image. is this a bug or a feature please ?  I would have expected, as you had defined tmpfs in the example dockercomposefile that no docker volumes would be created.
