### ISSUE TITLE
[FEATURE] Time-based results filter

### ISSUE THREAD

**Issue by baggachipz** [benbusby/whoogle-search#61]
This is such a great application and I'm loving every search with it. DuckDuckGo just wasn't doing it for me, and this does. The only feature I miss from Google is the ability to filter results based on time ([example image](https://i.imgur.com/42II5aR.png)). Would love this addition!

**Comment by benbusby** [comment]
Thanks for trying out Whoogle! This feature is already supported, documented here: https://github.com/benbusby/whoogle-search#usage

**Comment by baggachipz** [comment]
I'm stupid and don't read directions.
