### ISSUE TITLE
[FEATURE] No autocomplete request when autocomplete disabled

### ISSUE THREAD

**Issue by nakoo** [benbusby/whoogle-search#610]
**Describe the feature you'd like to see added**
A short description of the feature, and what it would accomplish.

`whoogle.env` supports changing visibility of autocomplete. But this feature makes sense by making no `/autocomplete` request. This could help reducing the server load.

**Additional context**

![2022-01-12_18-07](https://user-images.githubusercontent.com/4975021/149197211-39ba1d19-fb32-42bb-b352-5bc121b0bd25.png)

**Comment by Albonycal** [comment]
so `/autocomplete` should be disabled when the ENV variable is set to 0 ?

**Comment by nakoo** [comment]
> so `/autocomplete` should be disabled when the ENV variable is set to 0 ?

The current implementation is no. It still requests `/autocomplete` even though the results don't show up.

**Comment by DUOLabs333** [comment]
I can implement this -- it's not that hard. I just need to know @benbusby -- how are preferences exposed in the program (ex. `WHOOGLE_AUTOCOMPLETE`)?

**Comment by DUOLabs333** [comment]
#611 should fix this.
