### ISSUE TITLE
[BUG] Latest commit (ecb4277) completely breaks the docker-compose build

### ISSUE THREAD

**Issue by nakoo** [benbusby/whoogle-search#622]
**Describe the bug**

Latest commit ([ecb4277](https://github.com/benbusby/whoogle-search/commit/ecb4277e69f7522c1d814cc5b041e8137e8f6e18)) completely breaks the docker-compose build. 
Can you ***PLEASE*** test your code before submitting the PR?

I'm using the same `docker-compose.yml` templete with reverse proxy.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Additional context**

```bash
whoogle-search    | whoami: unknown uid 102
whoogle-search    | Jan 22 17:15:28.575 [notice] Tor 0.4.6.9 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1l, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.5.0 and Unknown N/A as libc.
whoogle-search    | Jan 22 17:15:28.578 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
whoogle-search    | Jan 22 17:15:28.671 [notice] Read configuration file "/etc/tor/torrc".
whoogle-search    | Jan 22 17:15:28.764 [notice] Opening Socks listener on 127.0.0.1:9050
whoogle-search    | Jan 22 17:15:28.765 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
whoogle-search    | Jan 22 17:15:28.765 [notice] Opening Control listener on 127.0.0.1:9051
whoogle-search    | Jan 22 17:15:28.765 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
whoogle-search    | Jan 22 17:15:28.766 [warn] /var/lib/tor is not owned by this group (root, 0) but by group <unknown> (102).  Are you running Tor as the wrong user?
whoogle-search    | Jan 22 17:15:28.778 [notice] Closing partially-constructed Socks listener connection (ready) on 127.0.0.1:9050
whoogle-search    | Jan 22 17:15:28.855 [notice] Closing partially-constructed Control listener connection (ready) on 127.0.0.1:9051
whoogle-search    | Jan 22 17:15:28.856 [warn] Failed to parse/validate config: Couldn't create private data directory "/var/lib/tor"
whoogle-search    | Jan 22 17:15:28.873 [err] Reading config failed--see warnings above.
whoogle-search    | Traceback (most recent call last):
whoogle-search    |   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
whoogle-search    |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
whoogle-search    |   File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
whoogle-search    |     return _get_module_details(pkg_main_name, error)
whoogle-search    |   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
whoogle-search    |     __import__(pkg_name)
whoogle-search    |   File "/whoogle/app/__init__.py", line 116, in <module>
whoogle-search    |     os.symlink(full_cb_path, build_path)
whoogle-search    | PermissionError: [Errno 13] Permission denied: '/whoogle/app/static/css/header.css' -> '/whoogle/app/static/build/header.3f278aa9.css'
whoogle-search exited with code 1
```

**Comment by nakoo** [comment]
We **really** need good CI/CD to prevent this kind of issue.

**Comment by Unrepentant-Atheist** [comment]
Yep, can cofirm. All I'm getting is 

    whoami: unknown uid 102
    Jan 22 20:38:51.149 [notice] Tor 0.4.6.9 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1l, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.5.0 and Unknown N/A as libc.
    Jan 22 20:38:51.149 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
    Jan 22 20:38:51.149 [notice] Read configuration file "/etc/tor/torrc".
    Jan 22 20:38:51.152 [notice] Opening Socks listener on 127.0.0.1:9050
    Jan 22 20:38:51.152 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
    Jan 22 20:38:51.152 [notice] Opening Control listener on 127.0.0.1:9051
    Jan 22 20:38:51.152 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
    Jan 22 20:38:51.152 [warn] /var/lib/tor is not owned by this group (root, 0) but by group <unknown> (102).  Are you running Tor as the wrong user?
    Jan 22 20:38:51.152 [notice] Closing partially-constructed Socks listener connection (ready) on 127.0.0.1:9050
    Jan 22 20:38:51.152 [notice] Closing partially-constructed Control listener connection (ready) on 127.0.0.1:9051
    Jan 22 20:38:51.153 [warn] Failed to parse/validate config: Couldn't create private data directory "/var/lib/tor"
    Jan 22 20:38:51.153 [err] Reading config failed--see warnings above.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/whoogle/app/__init__.py", line 116, in <module>
        os.symlink(full_cb_path, build_path)
    PermissionError: [Errno 13] Permission denied: '/whoogle/app/static/css/dark-theme.css' -> '/whoogle/app/static/build/dark-theme.2cfa92c2.css'
    whoami: unknown uid 102

**Comment by myogui** [comment]
I've commented out the `user: '102'` line and the `tmpfs` block in the docker-compose file and container starts now. But I don't know if causes other side effects.

**Comment by dr460nf1r3** [comment]
I fixed this by mapping the /config folder to a local dir and chowning to 927:927. For some reason these files were owned by root in the container.

**Comment by r0arkin** [comment]
I fixed this issue by changing `user=102` to `user=whoogle` and tmpfs uid/gid from 102 to 927.

Hope this helps!
