### ISSUE TITLE
[BUG] Cannot start service whoogle-search

### ISSUE THREAD

**Issue by alefvanoon** [benbusby/whoogle-search#625]
**Describe the bug**
ERROR: for whoogle-search  Cannot start service whoogle-search: unable to find user whoogle: no matching entries in passwd file
Deployed on Gnu/Linux with docker-compose
**To Reproduce**
sudo docker-compose up

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker-compose
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by benbusby** [comment]
Are you using an image tag other than `latest` in docker-compose? The recent changes to docker-compose use a new `whoogle` user (instead of root or debian-tor), but that user is only available in the `latest` docker tag. You could also try removing your previous whoogle image and rebuilding.

**Comment by alefvanoon** [comment]
Oh, thanks.
Fixed after removing old image with `docker image rm benbusby/whoogle-search:latest`
