### ISSUE TITLE
[QUESTION] How to update when deployed via Heroku Quick Deploy?

### ISSUE THREAD

**Issue by pred2k** [benbusby/whoogle-search#63]
It's awesome how easy (and cheap) it is to deploy it to heroku.  ❤️ 
And it works really great since a week.  
But now i saw nice changes like https-only and so on and i tried to find out how i update a heroku app.
Found https://blog.heroku.com/six-strategies-deploy-to-heroku where he says:
> Cons: Apps deployed via button do not auto-update when new commits are added to the GitHub repo from which it was deployed

Could someone help me here please?
Is heroku cli the way to go? Or can i link my github account to the app for automated updates?

**Comment by pred2k** [comment]
I've played around and it looks like following does a deployment of current **master** to my heroku deployment created via Heroku Quick Deploy:

```
git clone https://github.com/benbusby/whoogle-search.git
cd whoogle-search
heroku git:remote -a <name_of_my_heroku_app>
git push heroku
```

and future updates would be:
```
cd <path_to>/whoogle-search
git pull
git push heroku
```

**Comment by benbusby** [comment]
In the error from the second half of your comment, it seems like the only thing it's complaining about is the branch needing remote updates pulled in locally before pushing again (so all that would be needed is a `git pull` before re-running that push command for `v0.1.1`). I have a couple heroku instances running, I'll try to test out this method this week sometime and see what I run into.

**Comment by pred2k** [comment]
Updating to the latest releases works like charm.
Having heroku CLI setup in a repo-clone like i wrote above, this one simply deploys a new release tag:
```
cd <path_to>/whoogle-search
git pull
git push heroku v0.1.4:master
```
is the `README.md` a place for this update steps?
____

i'm now thinking about an automated deployment way for release tags of a heroku app.  
The Heroku github connection only allows automatic deployments on own repos (forks dont have automated sync) and branches only.
https://devcenter.heroku.com/articles/github-integration#automatic-deploys

Is anymore more experienced with the github/heroku connection that can give an hint on that?

**Comment by benbusby** [comment]
I added a wiki page with the contents of this discussion [here](https://github.com/benbusby/whoogle-search/wiki/Updating-a-Heroku-Quick-Deploy-Instance). I'll look into how Herolku handles automatic deployments and update the wiki if I find anything enlightening.
