### ISSUE TITLE
[BUG] Docker image with release version tag not published on time

### ISSUE THREAD

**Issue by FlipEnergy** [benbusby/whoogle-search#630]
**Describe the bug**
I request that a docker image is pushed to your Docker hub repository (benbusby/whoogle-search) with the release version tag upon each release. It seems the docker image with the tag with a semver matching the release doesn't exist until several days after the release is out on Github. I don't mean just this latest release, but I've noticed this for last couple releases as well.

Thanks for the good work!

**To Reproduce**
At the the time of this creation, 2 days after the release of 0.7.1, there is no image with the tag 0.7.1.  

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [multiple]
- [ ] Not sure

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by benbusby** [comment]
It should be fixed now -- I was missing a part of the CI workflow that should've been pushing new image tags to docker hub. In the meantime I manually pushed 0.7.1 (hopefully the last time I have to do that).
