### ISSUE TITLE
[QUESTION] Does ratelimiting ever expire?

### ISSUE THREAD

**Issue by nocturn9x** [benbusby/whoogle-search#633]
I was happily using my whoogle instance up until today, when I noticed it got ratelimited. Is there anything I can do beside using Tor (which is slow) or proxies (which kinda defeat the purpose of a more private google)? Does the ratelimit ever expire?

**Comment by benbusby** [comment]
It does expire, but there's no consistent amount of time that it takes to expire. I've seen ratelimiting stop after ~20-30 mins, or multiple hours or more. It seems dependent on how many people are using the Whoogle instance (more users seem to incur longer ratelimiting periods).
