### ISSUE TITLE
[BUG] `WHOOGLE_MINIMAL` removes search results

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#634]
**Describe the bug**
After some time, in some cases, a Whoogle search leads to an empty search page.

**To Reproduce**
1. Search (though it's unreliable)
2. See blank page

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: firefox

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/49244768/151896281-d4548366-6eb3-4843-9198-32c99e071e18.png)

**Comment by bruvv** [comment]
Log files are essential to debug this....

**Comment by DUOLabs333** [comment]
Whoogle doesn't output anything.

**Comment by glitsj16** [comment]
I've seen this too, on 0.7.1 and also on 0.7.0 (Arch Linux, same whoogle setup). Removing `WHOOGLE_MINIMAL=1` from whoogle.env (or setting `WHOOGLE_MINIMAL=0`) fixes this for me. Perhaps google changed something in those 'People also ask' cards that needs adjusting?

**Comment by benbusby** [comment]
Yep, looks like `WHOOGLE_MINIMAL` no longer works due to some behind the scenes changes to search result formatting.

**Comment by DUOLabs333** [comment]
Oh, foo -- I really liked `WHOOGLE_MINIMAL` too.

**Comment by DUOLabs333** [comment]
Also, side note -- `body {max-width: 100% !important; /* or whatever width you want */}` doesn't work anymore -- it's right aligned now.

**Comment by benbusby** [comment]
Yeah, likely related to the new result formatting that they're applying. I've noticed some styles are being forced as `!important`, which overrides styles that Whoogle applies (even with `!important`). I'm going to keep an eye on what gets changed in the next few days. Over the course of the day I've noticed that my prior 50/50 odds of getting their new result format have gone up to almost 100% new formatted results, so this might be a permanent change. I just pushed 9ba73331aad9311d839e23a4e90a0cb4546c9716, which should eliminate some of the weird white box-shadow elements I was seeing, which looked really bad for dark themes in particular.

**Comment by DUOLabs333** [comment]
I'm trying out a way to fix `MINIMAL` -- in `collapse_sections`, is there a way to remove a section? Just setting `result_children=[]` just causes a blank page.

**Comment by benbusby** [comment]
If the section is a BS4 element, then you can call `decompose()` on that element (i.e. `elem.decompose()`).

**Comment by DUOLabs333** [comment]
Are the elements in `result_children` strings -- I can't match strings inside of them.

**Comment by DUOLabs333** [comment]
I tried `decompose` -- however I got `AttributeError: ResultSet object has no attribute 'decompose'`

**Comment by DUOLabs333** [comment]
I got something that basically works -- it should work with both types of response bodies.

**Comment by DUOLabs333** [comment]
When you remove a section, a line is left behind -- it there a way to remove that?

![image](https://user-images.githubusercontent.com/49244768/152076842-94dc8a29-c06d-464f-9f5c-a6ea528c29f8.png)

**Comment by benbusby** [comment]
Hmm, I'm not sure really. I'm assuming it's leftover css, like a border being applied to an empty div (or something along those lines). Maybe for whatever section you're removing, it would be more accurate to remove its immediate parent element instead?

**Comment by DUOLabs333** [comment]
I removed the "Top stories" section, how would I remove the parent element?

**Comment by benbusby** [comment]
By calling `<elem>.parent.decompose()` instead of just `decompose()`, although I can't promise that's the solution, just a hunch.

**Comment by DUOLabs333** [comment]
Oh, I got it to work: I just called `result.decompose()`

**Comment by DUOLabs333** [comment]
I'll make a pull request soon.

**Comment by glitsj16** [comment]
Confirming #637 fixes `WHOOGLE_MINIMAL=1` here.

**Comment by servietos** [comment]
Hello thank you for that great application. However I'm on v0.9.1 and got an empty search result but only at 'All'. Images, Maps, Video and News deliver results. I'm using Whoogle as a docker container and re-installed it freshly with the same behavior.
May you've any idea, please?

![Image](https://github.com/user-attachments/assets/2f90b27e-a13a-4abb-b57e-d6bdd21fca62)

**Comment by bruvv** [comment]
@servietos https://github.com/benbusby/whoogle-search/issues/1211 please do not comment on closed issues if there are open issues.
