### ISSUE TITLE
[BUG] WHOOGLE_CONFIG_DISABLE not working

### ISSUE THREAD

**Issue by bruvv** [benbusby/whoogle-search#636]
**Describe the bug**
When using `WHOOGLE_CONFIG_DISABLE=1` or `0` it doesn't change anything it still is not showing the config change.

**To Reproduce**
1. Install this addon: https://github.com/alexbelgium/hassio-addons/tree/master/whoogle
2. Setup config
3. no config can be found

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Firefox on macos
 - Browser firefox
 - Version Latest

**Comment by benbusby** [comment]
Fixed -- thanks!
