### ISSUE TITLE
Autocomplete - would be nice [ 2nd edition ]

### ISSUE THREAD

**Issue by elvirmuslic** [benbusby/whoogle-search#64]
As mentioned by user @gripped  
The following API works really well in terms of autocomplete and I haven't found any limits to it YET.

https://github.com/asciimoo/searx/blob/master/searx/autocomplete.py

Might be worth a look ;) Doesn't look that complex but then I can't program.

Here would be an example of implementing the autocomplete.

```
    import requests, json
    URL="http://suggestqueries.google.com/complete/search?client=firefox&q=Hel Wor"
    headers = {'User-agent':'Mozilla/5.0'}
    response = requests.get(URL, headers=headers)
    result = json.loads(response.content.decode('utf-8'))
    print(result)
```
This is from Quora by: Michael Staniek _Thank you!_

There is no auth key or token, should work pretty well I will try to spam it for a little bit to see if there are limits.

**Comment by elvirmuslic** [comment]
I have run 1000 iterations ( _queries_ ) in **2 minutes and 43 seconds**.

Everything works perfectly, the API doesn't even throttle.  In my example I ran **~6 queries** a second.  

Here is the log,  https://pastebin.com/q5SNLxXV

**Comment by benbusby** [comment]
Wow, I’m kinda shocked. I expected there to at least require an API key, if not a monthly subscription or something. 

I’ll work on implementing this soon.

**Comment by elvirmuslic** [comment]
Yea mee too, there is the code in their github u can just copy paste.
