### ISSUE TITLE
Overwrite new styling changes included in search response

### ISSUE THREAD

**Issue by mada199122** [benbusby/whoogle-search#641]
**Describe the bug**
Since v0.7.1 || version no more separated tab in the result pages. I've attached a couple of screenshot to show the issue

**To Reproduce**
Search something using last versione

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: MacOS 12.2
 - Safari / Firefox
 - Last release

**Additional context**
Before
![photo_2022-02-04 09 12 31](https://user-images.githubusercontent.com/61902329/152494391-8527e844-9ae2-4509-a81a-d7d0f72f28d4.jpeg)

Now
![Screenshot 2022-02-04 at 09 13 54](https://user-images.githubusercontent.com/61902329/152494590-2ee7c4df-6fbd-448f-a535-48d5305b2283.jpg)

**Comment by DUOLabs333** [comment]
It's almost certainly because Google changed something on their end.

**Comment by benbusby** [comment]
Yep. They're in the middle of changing the default styles that are included in search responses. Once I'm confident they're done messing around with it, I'll revisit the styling and try to get it back to the old appearance.

**Comment by DUOLabs333** [comment]
This might be fixed with #535.
