### ISSUE TITLE
[BUG] Font changed with no interaction.

### ISSUE THREAD

**Issue by Adithya-Kalany** [benbusby/whoogle-search#644]
**Describe the bug**
I simply searched "bootstrap" and for some reason, it's font is changed. I host on repl.it and use a pinging service. No idea why it has changed and would like the old font back.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: [repl.it]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Librewolf]
 - Version [96.0.3-1 (64-bit)]

![image](https://user-images.githubusercontent.com/69103102/150988553-72253d18-725a-4902-8374-fa3b3c5dab84.png)

**Comment by Adithya-Kalany** [comment]
Hello! Sorry I could not post a reply.

**I opened a new issue so you could see it.**

Before it used to work after the day I posted the issue but it sprung up again!
I'll attach the stuff I get in Inspect
I also disabled all extensions and themes and yet the problem persists.
![image](https://user-images.githubusercontent.com/69103102/152683437-b51992de-7410-4b2c-a5f3-f044ef7adce1.png)

_Originally posted by @Adithya-Kalany in https://github.com/benbusby/whoogle-search/issues/624#issuecomment-1030833705_

**Comment by DUOLabs333** [comment]
This is weird -- the only thing I could think of that's causing this is `bolden_search_terms`. @Adithya-Kalany If you search other words, does the problem show up again?

**Comment by Adithya-Kalany** [comment]
IT FIXED ITSELF AGAIN! WHAT!!!!

**Comment by Adithya-Kalany** [comment]
I OFFICIALLY HAVE A CURSE
