### ISSUE TITLE
[BUG] docker-compose: default tmpfs size for /var/lib/tor to small

### ISSUE THREAD

**Issue by CyberJack** [benbusby/whoogle-search#648]
**Describe the bug**

After updating to version 0.7.1 and updating the docker-compose.yml file, I saw warning messages in the logs:

    [warn] Couldn't dump microdescriptor (wrote 0 out of 3532): No space left on device
    [warn] Couldn't write microdescriptor annotation: No space left on device
    [warn] Error writing to "/var/lib/tor/state": No space left on device
    [warn] Unable to write state to file "/var/lib/tor/state"; will try again later
    
Even after fully clearing all docker images, containers and volumes I still got these messages.

I increased the size from 10M to 100M to see how much data was going to be written to `/var/lib/tor` and at the moment (after a fresh start) it is 10.9MB. 

    $ df -h
    Filesystem                Size      Used Available Use% Mounted on
    overlay                 388.0G     83.4G    284.8G  23% /
    tmpfs                    64.0M         0     64.0M   0% /dev
    shm                      64.0M         0     64.0M   0% /dev/shm
    /dev/sda3                10.0M      1.6M      8.4M  16% /config
    tmpfs                    10.0M      1.6M      8.4M  16% /config
    /dev/sda3               388.0G     83.4G    284.8G  23% /etc/resolv.conf
    /dev/sda3               388.0G     83.4G    284.8G  23% /etc/hostname
    /dev/sda3               388.0G     83.4G    284.8G  23% /etc/hosts
    tmpfs                     1.0M         0      1.0M   0% /run/tor
    tmpfs                   100.0M     10.9M     89.1M  11% /var/lib/tor
    tmpfs                     7.8G         0      7.8G   0% /proc/acpi
    tmpfs                    64.0M         0     64.0M   0% /proc/kcore
    tmpfs                    64.0M         0     64.0M   0% /proc/keys
    tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
    tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
    tmpfs                     7.8G         0      7.8G   0% /proc/scsi
    tmpfs                     7.8G         0      7.8G   0% /sys/firmware

Updating the size in the `docker-compose.yml` file should fix this problem.

**To Reproduce**
1. Clone the repository
2. Run `docker compose up && docker compose logs -f` 
3. Check the logs for "No space left on device" messages

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from Docker (v0.7.1)
- [ ] Version [version number]
- [ ] Not sure

**Server (VPS):**
 - OS: Arch
 - Docker: 20.10.11
 - Docker Compose: 2.2.0

**Comment by Diechel** [comment]
Also got issues with default docker compose. Now set to 50MB and no error messages.
Seems to use around 11-12MB. Will lower setings according to max use.

![afbeelding](https://user-images.githubusercontent.com/6208866/158052890-2d32df9a-8441-4496-b01f-60e3dcaeca24.png)
