### ISSUE TITLE
[FEATURE] Don't crash when not connected to the internet

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#649]
**Describe the feature you'd like to see added**
The app should not crash if it can't connect to google.com/github.com

**Additional context**
Sometimes, as I restart whoogle often (testing new ideas), I don't have WiFi for 5 seconds, and if Whoogle can't connect to github.com, it crashes, forcing me to starting it again.

**Comment by DUOLabs333** [comment]
It happens here: `update = bsoup(get(app.config['RELEASES_URL']).text, 'html.parser')` in `routes.py`. I'm not sure what should happen on an error. Do show "Failed to retrieve info"?

**Comment by benbusby** [comment]
Fixed as part of a larger refactor that was needed for the latest release/update check.
