### ISSUE TITLE
[FEATURE] Add release version with commit details at home screen bottom

### ISSUE THREAD

**Issue by getredy** [benbusby/whoogle-search#65]
**Display version & commit number in bottom of home screen**
Please add the version number with commit number at the bottom of whoogle home screen. It tells user which version is deployed. Its similar what we seen on searx public instances.

For example see this attached image
![Screenshot_20200520-064726](https://user-images.githubusercontent.com/65450630/82394141-be9c1400-9a37-11ea-8bab-95fe70de285e.png)

**Comment by benbusby** [comment]
Just added in c51f1864194abc928135caaacccee0861bad57e4 -- thanks for the suggestion!

**Comment by getredy** [comment]
@benbusby changes are not reflected in latest build. Seems like build got failed.
https://github.com/benbusby/whoogle-search/commit/c51f1864194abc928135caaacccee0861bad57e4

**Comment by benbusby** [comment]
@getredy sorry about that, should be now.
