### ISSUE TITLE
[BUG] Rate limited after first install

### ISSUE THREAD

**Issue by d4rklynk** [benbusby/whoogle-search#652]
**Describe the bug**
I have rate limited right after I installed whoogle

**Deployment Method**
Whoogle on docker on a VPS, Cloudflare as DNS (proxied or not proxied, I have same issue)

**Version of Whoogle Search**
latest one (today at 11-02-2022)

**Additional context**
I use Whoogle with docker on a VPS, behind Nginx Proxy Manager, with Cloudflare as DNS server (but not proxied), every settings is default

**Comment by d4rklynk** [comment]
Ok thank you for your reply !

**Comment by Goelant** [comment]
I know this issue is closed, but as I'm having the same issue, I just bring the idea of maybe finding a turn-arround, maybe by setting up a new endpoint like this answer purpose : https://github.com/benbusby/whoogle-search/issues/211#issuecomment-898753235 ?

Have a great day 👋 !
