### ISSUE TITLE
[BUG] The first two results for 'google "must include" ' does not have its titles

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#656]
**Describe the bug**
If you search for `google "must include"` the first two results are missing its title

**To Reproduce**
1. Search for `google "must include"`

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/49244768/153675021-74b163fe-219b-44f1-977d-9eb2cb4f28e6.png)

**Comment by DUOLabs333** [comment]
This also happens with `mirror pixel screen to chrome`. This is probably because there are subheadings to both results in Google, and whoogle does not know how to deal with it.

**Comment by DUOLabs333** [comment]
It seems that whatever filtering is going on is a little too eager on the removing.

**Comment by DUOLabs333** [comment]
@benbusby Is there any place where titles can get deleted?

**Comment by benbusby** [comment]
No, there shouldn't be any parts of the filter that are partially removing contents from a result card. I'll look into it.
