### ISSUE TITLE
[BUG] Some search terms throw Internal Server Erro (500)

### ISSUE THREAD

**Issue by nocturn9x** [benbusby/whoogle-search#657]
**Describe the bug**
Same as #504, looks like a regression.

**To Reproduce**
See #504 

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.7.0
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser: Google Chrome Beta
 - Version: 98.0.4758.54 (Official Build) beta (64-bit)

**Comment by DUOLabs333** [comment]
Can reproduce, trying to fix.

**Comment by DUOLabs333** [comment]
Maybe the div name changed?

**Comment by DUOLabs333** [comment]
Actually, it seems that the formatting changed completely -- we may have to remake the function to not be dependent on hardcoded values.

**Comment by nocturn9x** [comment]
> Actually, it seems that the formatting changed completely -- we may have to remake the function to not be dependent on hardcoded values.

Woah, that was quick! Thanks for fixing it so fast, I use whoogle daily as my search engine and it's awesome to have this kind of support :)

**Comment by Albonycal** [comment]
> > Actually, it seems that the formatting changed completely -- we may have to remake the function to not be dependent on hardcoded values.
> 
> Woah, that was quick! Thanks for fixing it so fast, I use whoogle daily as my search engine and it's awesome to have this kind of support :)

OpenSource FTW

**Comment by nocturn9x** [comment]
> > > Actually, it seems that the formatting changed completely -- we may have to remake the function to not be dependent on hardcoded values.
> > 
> > 
> > Woah, that was quick! Thanks for fixing it so fast, I use whoogle daily as my search engine and it's awesome to have this kind of support :)
> 
> OpenSource FTW

Indeed

**Comment by nocturn9x** [comment]
Uhm, happening again with 0.7.1?

**Comment by DUOLabs333** [comment]
Try `latest`.

**Comment by nocturn9x** [comment]
Yeah I was using a cached version of latest. Whoops, my bad!
