### ISSUE TITLE
Can't create /config/sessions on install - most likely wrong/hardcoded UID:GID (927:927)

### ISSUE THREAD

**Issue by nicolaibob** [benbusby/whoogle-search#658]
Trying to install in docker environment on synology, but cant make it work until i change read/write access on the /config folder to "Everyone". Then i can see in bash, that the folders owner is a UID:GID 927:927, which is a user not on my system..

Searching for whoogle and 927 have lead me to to this site:  https://github.com/benbusby/whoogle-search/blob/main/Dockerfile.

Setting PGID and PUID as environmental variables doesnt seem to have any effect.

**Comment by benbusby** [comment]
The /config folder should be writable by all, but it looks like that gets skipped over in the Dockerfile if the directory already exists. I'll push a change shortly.
