### ISSUE TITLE
[FEATURE] ?country HTTP parameter

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#668]
I know the parameters were added for usage with farside, but I don't use the default session / config thing because it's not reliable, the configs resets on it's own sometimes.
It'd be nice to set different config options using parameters.
afaik currently these are available `safe, nojs, tor, get_only, block_url, accept_language, block, q, near, new_tab, url, alts, view_image, block_title` I'd like a `country=` parameter 
for. ex `country=IN`

**Comment by benbusby** [comment]
`country=` is already supported. The full list of valid url params (that are relevant to config settings) are in the `safe_keys` list in config.py:

https://github.com/benbusby/whoogle-search/blob/c3634a513528eb33e9caa6a2742d6024d399791c/app/models/config.py#L33-L43

**Comment by Albonycal** [comment]
hmm, oh wait yea my mistake
I was using `&?country` instead of `&country`
Thanks :sweat_smile:
