### ISSUE TITLE
[FEATURE] Ability to disable IPv6 or enable JS when Bot Check

### ISSUE THREAD

**Issue by lol7344** [benbusby/whoogle-search#67]
**Describe the feature you'd like to see added**

I am using a hosted VPS, which has both IPv4 and IPv6 enabled.
However, when I run whoogle-search, and try searching anything with it, I get a google spam-bot popup, saying that there's unusual traffic coming from my IP (and I see my VPS' IPv6 IP).
I am however unable to go past this screen, since Whoogle automatically disables JavaScript.

However, if I disable IPv6 system-wide, and restart whoogle, I can succesfully browse the web.

This is probably related to my own VPS hosting provider, doing nasty stuff with shared IPv6s, thus a feature to disable IPv6 (either via command line arg or via the "options" button in the homepage) would add a really nice touch, since not everyone has a working or usable (although enabled) IPv6 address.

Another solution, related to this case scenario, would be to detect if the current page is the spam bot check, and eventually enable the JS captcha script.

**Comment by benbusby** [comment]
Unfortunately, even if JS was enabled, the Google captcha check won't work due to their same host origin enforcement. Without a `*.google.com` host, the bot check throws an error with something along the lines of `invalid hostname for captcha: <your whoogle url>`. 

I'll look into `pycurl` options that would allow enforcing only IPv4 requests though, I like that idea!

**Comment by benbusby** [comment]
I still like this idea, but from a cursory glance it [doesn't seem like this is possible](https://github.com/psf/requests/issues/1691) (or at least not without a hacky solution) using the `requests` library, which replaced the `pycurl` implementation in the project some time ago. 

Closing for now, but happy to reopen if there's a clean solution for this that I'm overlooking.
