### ISSUE TITLE
xml.etree.ElementTree.fromstring is considered insecure. 

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#670]
https://docs.python.org/3/library/xml.etree.elementtree.html

https://github.com/benbusby/whoogle-search/blob/main/app/request.py#L233
![image](https://user-images.githubusercontent.com/67057319/155494728-a01843f5-a84d-417c-8c5e-a8e0e0c76b02.png)

**Comment by benbusby** [comment]
Thanks for pointing this out. XML parsing is now handled by [defusedxml](https://github.com/tiran/defusedxml).
