### ISSUE TITLE
Apply Config Var Change

### ISSUE THREAD

**Issue by gaia** [benbusby/whoogle-search#671]
not familiar with heroku, but supposedly a config var change would trigger the process to make it take effect, but `WHOOGLE_CONFIG_THEME=dark` did not. So I deleted the app, and re-deployed with this in place. Still no dark theme.

how can i check whether it IS in effect at least on the server side, and it is still white bc of something on the client side?

**Comment by benbusby** [comment]
Are you deploying from the command line or from the heroku quick deploy button in the readme? If the latter, you can write "dark" in the WHOOGLE_CONFIG_THEME input box before deploying. If you're deploying from the command line, you would set the field like so: `heroku config:set WHOOGLE_CONFIG_THEME=dark`. Sorry for the delay! Let me know if that works for you.
