### ISSUE TITLE
[QUESTION] Legality of hosting whoogle instance

### ISSUE THREAD

**Issue by NebulaBC** [benbusby/whoogle-search#673]
I have been considering hosting a whoogle instance (and a hastebin, but that's unrelated) on heroku. I am curious about the legality, since on my personal sites I have often skipped by a privacy policy, but whoogle seems to collect some data. Whoogle instances have no privacy policy linked, so I am curious what the deal is with that. Have there ever been any instances of a selfhosted application running into legal trouble? (or whoogle specifically) Should I be worried about hosting these services bringing me any legal problems in the future?

Also, how would I ever go about deleting user data if it was requested?

**Comment by Albonycal** [comment]
uh it's possible, there could be some legal troubles if a malicious actor uses your instance, but I am no legal expert.. I'll add a privacy policy to my instance :+1:  and no, whoogle doesn't store any data. 
I don't know about the public instances. If you don't trust them you can host your own

**Comment by NebulaBC** [comment]
I considered that, but also the requests to Google are encrypted, right? I am a bit in the dark over hosting all together. Hopefully there are no issues anyways (since for my case at least) heroku seems like more of the place to just term you before anything else

**Comment by Albonycal** [comment]
no? all uses TLS

**Comment by NebulaBC** [comment]
Yes, but my point is that the company you are hosting with can not see the info going back and forth between your server and google. And if you have a cert on your whoogle server they can see the data going into whoogle from the user. Correct?

**Comment by Albonycal** [comment]
nope, all they'll see if one IP connecting to this server,
also now I am hosting on my own server

**Comment by NebulaBC** [comment]
Thanks for clearing that up. Sorry I asked the same question a couple of times, I was just confused with how you were saying it.
