### ISSUE TITLE
[QUESTION] Whoogle reports my ip?

### ISSUE THREAD

**Issue by Insomniac86** [benbusby/whoogle-search#674]
Hi guys, just wanted to confirm...
I have Whoogle running via docker on a VPS and I'm not using tor.
If I browse the VPS whoogle instance from my local PC and search "what is my ip", the google result will display my client IP and not the VPS IP. I did not expect this behaviour. Can someone confirm if that seems right?

Cheers

**Comment by Albonycal** [comment]
yea it's a "feature" the IP isn't sent to google.
Its handled locally and nothing is stored
so yes it's normal

**Comment by Insomniac86** [comment]
> 

Thanks! I suspected it might be locally resolved but just wanted to make sure :)

Cheers!

**Comment by Albonycal** [comment]
you may close the issue then
😉
