### ISSUE TITLE
[QUESTION] How to get the suggestions URL right?

### ISSUE THREAD

**Issue by nocturn9x** [benbusby/whoogle-search#679]
I recently downloaded all of my data from Google Takeout and I noticed a peculiar field that Chrome doesn't show when adding/editing search engines, namely `suggestions_url` which in this case is set to `http://localhost:5000/autocomplete?q={searchTerms}`. Since chrome shows no way to change this field whatsoever I'm assuming it's something that's exchanged automatically between whoogle and chrome as part of the opensearch standard or w/e, but my question is how do I tell whoogle to use my instance URL instead of the localhost:port one? It's in a docker container behind nginx so obviuously that doesn't work

**Comment by jacr13** [comment]
You need simply to change the url in your configuration (under root url) and after add again whoogle to your browser.

**Comment by nocturn9x** [comment]
> You need simply to change the url in your configuration (under root url) and after add again whoogle to your browser.

I see, I'll try. Thanks!

**Comment by benbusby** [comment]
Assuming this was fixed, but feel free to reopen if not!
