### ISSUE TITLE
Fix docker repo at ReadMe.md line 136

### ISSUE THREAD

**Issue by esturniolo** [benbusby/whoogle-search#68]
`docker run --publish 5000:5000 --detach --name whoogle-search whoogle-search:latest ` doesn't work.

You should add the full image name `docker run --publish 5000:5000 --detach --name whoogle-search benbusby/whoogle-search:latest ` 

I couldn't do a PR.

**Comment by benbusby** [comment]
In the future you can do PRs by forking this repo, making the changes to your fork, and then requesting to merge your forked repo into the master branch of whoogle-search. 

That being said, I just pushed a fix for this. Thanks for bringing that to my attention!
