### ISSUE TITLE
[BUG] redirect loop on Firefox, leading to HTTP 500 error

### ISSUE THREAD

**Issue by dbx10** [benbusby/whoogle-search#681]
When using whoogle over HTTPS on Firefox, it sends notice that the page isn't redirecting properly, and when clicking try again it posts an HTTP 500 error.

- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 Firefox on windows, android 11 and ubuntu 21

Unsure if this is related, but it also spits dozens of these in the logs: 
```   PermissionError: [Errno 13] Permission denied: '/config/session/4bf70ff5478c354e79228f0e612394d0'
WARNING:root:Exception raised while handling cache file '/config/session/2029240f6d1128be89ddc32729463129'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cachelib/file.py", line 183, in get
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^```

**Comment by DUOLabs333** [comment]
Can you try updating?

**Comment by dbx10** [comment]
This was solved by removing the container and reinstalling it entirely.
