### ISSUE TITLE
[BUG] UAE Search Results (Docker)

### ISSUE THREAD

**Issue by andrewkliskey** [benbusby/whoogle-search#69]
When searching using the docker image, the results appear to be targeted towards the UAE. 

The weather results are correct and says the same location to that set in the configuration. The news along with other results appear to be the UAE versions.

Example 1:
1. Search "apple"
2. The first result is "https://www.apple.com/ae/"

Example 2:
1. Search "amazon"
2. The first result is "https://www.amazon.ae/"

This is running on a Hetzner VPS, located in Germany. With the location set within the config being in the UK.

This is using the latest docker image (although it also happened with previous ones).
Digest: 688ab5d1a265

**Comment by benbusby** [comment]
Just fixed in #71, there will now be a config option to set your preferred country from the home page. The latest build on docker hub should be updated shortly. Thanks for reporting!

**Comment by andrewkliskey** [comment]
Thanks for the quick fix, works perfectly now!
