### ISSUE TITLE
[QUESTION] Way to change underline and highlight color

### ISSUE THREAD

**Issue by WitherCubes** [benbusby/whoogle-search#690]
Is there any way to change the highlight color and the underline color from the default blue or is it a bug?

![image](https://user-images.githubusercontent.com/72592921/159304761-84d9dc80-15ae-46da-b76c-21942590f5a4.png)

![image](https://user-images.githubusercontent.com/72592921/159305063-f78c4034-b041-4347-9329-ac84d57de274.png)

**Comment by Albonycal** [comment]
that isn't the default blue... 
are you using a public instance

**Comment by WitherCubes** [comment]
No, I am using my self hosted instance.

**Comment by seth-js** [comment]
This CSS modifies the link underline colors:

> a {
>   color: #1a0dab;
> }
> 
> a:visited {
>   color: #4b11a8;
> }

This CSS controls the highlight color of result divs when focused:

> 
> #main > div:focus-within {
>   box-shadow: 0 0 6px 1px #2375e8;
> }

**Comment by Albonycal** [comment]
are you using a public instance?
