### ISSUE TITLE
[FEATURE] Add https://whoogle.lunar.icu/ to Public List

### ISSUE THREAD

**Issue by MaximilianGT500** [benbusby/whoogle-search#694]
Hello, can you add https://whoogle.lunar.icu/ to your Public List?

Thanks,
Maximilian

**Comment by benbusby** [comment]
Added. Thanks!

**Comment by MaximilianGT500** [comment]
Hi, the Server Location is in Germany. :)

**Comment by MaximilianGT500** [comment]
Ok thanks, yes its Cloudflare.
