### ISSUE TITLE
[FEATURE] config option to always display time filter :past hour day month year, etc....

### ISSUE THREAD

**Issue by Jieiku** [benbusby/whoogle-search#695]
On an older version of whoogle.... I think 0.4 or so. I could use the time selector without having to type :past

What I mean specifically is have an option so that we do not hide this item I have circled in red.

Whenever I search even if I do not include the keyword :past I want to see this box, so that I can click on it to filter the time.

![2022-03-23_18-15](https://user-images.githubusercontent.com/106644/159822641-e9233d16-cc3f-4230-a2ff-4ff1af7557fc.png)

**Comment by DragonHeart69** [comment]
+1
I want this back too. I use it regularly.

Grtz
DragonHeart69

**Comment by benbusby** [comment]
If you set your search language in the config menu, this box will reappear. That's all that 0.4 (or whichever release included this box by default) was doing -- Whoogle used to enforce a search language. 

It's an unfortunate limitation of how/when Google decides to include that menu in the results. The only other way to get it to reliably appear would be to always set the search time window to some high value (like "past 100 years") on the backend before the query is sent, which isn't a very elegant way to address it. 

Alternatively we could create a custom menu to appear in search results for filtering by time range within Whoogle itself and ignore the one provided by Google, but functionality wise it wouldn't be any different than that one and would be a much bigger undertaking than just setting search language in the Whoogle config.
