### ISSUE TITLE
[QUESTION] How do I run Whoogle behind Traefik?

### ISSUE THREAD

**Issue by blabberfondue** [benbusby/whoogle-search#70]
I am trying to get Whoogle behind the Traefik Reverse Proxy, but unable to do so. The certificate has already been issued successfully.

Here are the labels I've specified for Whoogle:

      - "traefik.enable=true"
      - "traefik.http.routers.search.tls=true"
      - "traefik.http.routers.search.rule=Host(`search.example.com`)"
      - "traefik.http.services.search.loadbalancer.server.port=5000"
      - "traefik.http.routers.search.service=search"
      - "traefik.http.routers.search.entrypoints=websecure"
      - "traefik.http.routers.search.tls.certresolver=myresolver"
      - "traefik.http.services.search.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.my-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.my-redirect.redirectscheme.permanent=true"

**Comment by xaabi6** [comment]
Hey there, I'm using it with Traefik and it works flawlessly. I would recommend you leave it like this and see if it works, then it's like including things back and see when it fails:

	  - "traefik.enable=true"
	  - "traefik.http.routers.search.rule=Host(`search.example.com`)"
	  - "traefik.http.routers.search.entrypoints=websecure"
	  - "traefik.http.routers.search.tls.certresolver=myresolver"

BTW, could you post here your Whoogle and Traefik docker-compose.yml files so I can help you better?

**Comment by blabberfondue** [comment]
I actually did try that initially, but it didn't work. Then I added the additional labels to see if that would help, but it didn't either.

Sure, here are the sections for Traefik and Whoogle from my Compose file. Thank you! :)

https://pastebin.com/Kzpk0H7g

**Comment by xaabi6** [comment]
I think that I know the problem, you need Whoogle to be in the same network as Traefik. Please try this pastebin code and see if it works: https://pastebin.com/vZxia12V

I have just added network and this label to your docker-compose:

	# Network to use
      - "traefik.docker.network=traefik_default"

**Comment by blabberfondue** [comment]
That worked, thank you! 👍 🥇
