### ISSUE TITLE
[QUESTION] How to disable single alternative service replacements

### ISSUE THREAD

**Issue by pred2k** [benbusby/whoogle-search#704]
Hi,
i've set the following env var's for the latest docker image:
```
WHOOGLE_CONFIG_ALTS=1
WHOOGLE_ALT_TW=nitter.mydomain.com
WHOOGLE_ALT_YT=invidious.kavin.rocks
WHOOGLE_ALT_IG=bibliogram.mydomain.com/u
WHOOGLE_ALT_RD=libreddit.mydomain.com
WHOOGLE_ALT_TL=translate.mydomain.com
WHOOGLE_CONFIG_DISABLE="1"
WHOOGLE_CONFIG_COUNTRY="countryDE"
WHOOGLE_CONFIG_LANGUAGE=""
```
A latest change on whoogle replaces wikipedia links automatillay with farside.link. I know thats a feature, but i dont like this replacement, because the wikiless page are not responsive and i now always get english wikipedia articles and not germans anymore.

I would like to disable **only** the wikipedia alt svc replacement.

When i set `WHOOGLE_ALT_WIKI=de.wikipedia.org` all wikipedia links are enforced to german sites. Searches for "Moore-Jackson Cemetery" will result to a link to an unavaliable de.wikipedia.org article. (https://de.wikipedia.org/wiki/Moore-Jackson_Cemetery)

When i set `WHOOGLE_ALT_WIKI=wikipedia.org` all wikipedia links are enforced to english. 😢 

`WHOOGLE_ALT_WIKI=""` breaks all wikipedia links.

**Comment by benbusby** [comment]
Hey @pred2k! I've actually been meaning to do this for a while. I'll push a fix shortly.

**Comment by benbusby** [comment]
This should be fixed now. If you set `WHOOGLE_ALT_WIKI` to an empty value, it will be skipped when filtering for site alternatives. Thanks for pointing this out!

**Comment by pred2k** [comment]
Awesome @benbusby, thank you!
