### ISSUE TITLE
[BUG] All instances are throwing HTTPS errors

### ISSUE THREAD

**Issue by KanadeTachibana2** [benbusby/whoogle-search#711]
**Describe the bug.**
i'm using Firefox with the setting "HTTPS-Only Mode" enabled, and all the Whoogle instances are throwing the exactly same error: "Secure Connection Not Available".

![sshot-2022-04-03-12-25-35](https://user-images.githubusercontent.com/85243826/161435843-2b0e6809-7e4f-4d8f-bfec-409347d0e6c4.png)

**To Reproduce.**
1. Force your browser to use HTTPS.
2. Go to any Whoogle instance.
3. See error.

**Deployment Method.**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: public instances.

**Version of Whoogle Search.**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version: 0.7.1
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Mozilla Firefox
 - Version: 98.0.2

**Additional context.**
.

**Comment by Albonycal** [comment]
Hmm.. unable to recreate this issue 
![image](https://user-images.githubusercontent.com/67057319/161436873-a7ea1f37-26d3-423e-a5fd-d9feb449b151.png)
![image](https://user-images.githubusercontent.com/67057319/161436881-dbb140c2-f2c9-4c61-a7bb-be2f8334af21.png)

**Comment by worthless244** [comment]
> Hmm.. unable to recreate this issue

I'm not crazy.

other people have reported the same issue: https://github.com/benbusby/whoogle-search/issues/602, https://github.com/benbusby/whoogle-search/issues/681, https://github.com/benbusby/whoogle-search/issues/709

when this error happens, the URL turns into: `https://<instance_name>/session/<randon_numbers>`... just like it happens in https://github.com/benbusby/whoogle-search/issues/602

**Comment by worthless244** [comment]
can anyone from the developer team please confirm or deny if they have come across this issue?

**Comment by FlorianWendelborn** [comment]
@KanadeTachibana2 can you try to start Firefox with a fresh/blank profile? You can learn how to create one here: <https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles>

If this fixes your issue, then it might be add-on or `about:config` related instead of caused by HTTPS-Only-Mode.
