### ISSUE TITLE
[QUESTION] <UI font is huge after setting HTTPS access with domain name >

### ISSUE THREAD

**Issue by ShlomiD83** [benbusby/whoogle-search#720]
Hi,
I'm running Whoogle on docker using raspberry pi 4.
when accessing via http everything works great, but after setting up HTTPS access with a domain name using Cloudflare & Nginx Reverse Proxy the UI font is huge & the page doesn't look good.
what am I doing wrong?
Please advise.

Thank you!
![image](https://user-images.githubusercontent.com/17053215/163045873-cf82c07a-6fe0-40ef-8838-3ac31219e3c2.png)

**Comment by nakoo** [comment]
It seems your reverse proxy setting doesn't properly handle the whoogle server. Please provide `nginx.conf` to check the problem.

**Comment by ShlomiD83** [comment]
forgot to close the issue, it was already resolved.
thank you.
