### ISSUE TITLE
[QUESTION] How do i run it on windows

### ISSUE THREAD

**Issue by eviontech** [benbusby/whoogle-search#722]
i am trying to deploy it on a windows machine please suggest a way because running python run gives syntax error

**Comment by eddik1970** [comment]
I have installed it via docker on windows, and it runs fine.

**Comment by benbusby** [comment]
Are you using an older version of Python? Presumably any of the manual install methods from [here] below should work for you, but I'm guessing there's a version issue with Python. I'd recommend installing it with Docker if you don't want to or can't update your Python version to >= 3.9.
