### ISSUE TITLE
[QUESTION] How to enable HTTPS

### ISSUE THREAD

**Issue by ASNosal** [benbusby/whoogle-search#725]
I have followed the directions in the readme, and acquired certificates for my domain with certbot. However, I cannot seem to get the whoogle server to pull the certs and serve https. It remains accessible through HTTP, but HTTPS always fails. I am using docker-compose to run the sever.

Is there something I need to change in the .env, or yml to call out where the certs should be located? What am I missing here?

**Comment by BluishHumility** [comment]
I've been stumped on the exact same issue. I was able to get the certbot certification set up just fine, but I can't figure out how to get the docker-compose to incorporate it into the Whoogle deployment. Whoogle has been working fine over HTTP, but HTTPS fails.

I can connect to the instance externally by IP address only because my DDNS service only supports HTTPS. I am hoping for a clue how to get it correctly configured so I can use the DDNS domain for Whoogle.

**Comment by nakoo** [comment]
If you want to use HTTPS, you must use reverse proxy like nginx.

**Comment by benbusby** [comment]
^ correct. If you want to serve your Whoogle instance over HTTPS, you'll need to use something like nginx to handle that for you. If you used certbot, it should look something like this:

```
server {
	server_name <your domain name>;
	location / {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header Host $host;
		proxy_pass http://localhost:5000;
	}

	listen 443 ssl; # managed by Certbot
	ssl_certificate /etc/letsencrypt/live/<your domain>/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/<your domain>/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
	if ($host = <your domain>) {
		return 301 https://$host$request_uri;
	} # managed by Certbot


	listen 80;
	server_name <your domain>;
	return 404; # managed by Certbot
}
```
Note that certbot actually handles a lot of these details for you if you tell it to. If you have your nginx server config defined (the above config without anything annotated with `# managed by Certbot`) then running something like `sudo certbot --nginx -d <your domain>` should fill out the rest for you.
