### ISSUE TITLE
Social media's redirections

### ISSUE THREAD

**Issue by Rrhyast** [benbusby/whoogle-search#727]
adding Alternative redirections for youtube, reddit, twitter, instagram &...

for example for youtube video links redirect to [invidius](https://invidious.io/) & [Youtube Piped](piped.kavin.rocks/)
reddit to libreddit & twitter to nitter and some like this stuff.

**Comment by Im-Kal** [comment]
farside.link

**Comment by benbusby** [comment]
Yes, the [farside](https://github.com/benbusby/farside) integration in Whoogle should be accomplishing what you're seeking. Let me know if you're talking about something else though.

**Comment by 0x09AF** [comment]
Incredible feature. Thanks for implementing this!
Now, is it possible to redirect only SOME specified URLs, for example, I want to redirect to LibReddit and Invidious, but go to real Twitter?
I tried uncommenting Reddit in the `whoogle.env` file, but it didn't redirect. When I uncomment the redirect option, it redirects to ALL supported redirects (Wikiless etc).
Could that be done in the future?
