### ISSUE TITLE
[FEATURE] Change between languages from results page

### ISSUE THREAD

**Issue by benbusby** [benbusby/whoogle-search#74]
**Describe the feature you'd like to see added**
Brought up in #73, where a user brought up needing the ability to switch between results languages from the results page instead of the home page. 
**Additional context**
The implementation should be similar to the built in Google UI for switching between a specified language and “all languages”.

**Comment by fabrizzioalco** [comment]
Hey, i would like to contribute to this issue.

**Comment by benbusby** [comment]
Hey @fabrizzioalco, just saw your message. I ended up spending a bit of time this morning fixing the issue since I've been getting a bunch of emails about it, so unfortunately (or fortunately I guess) this one already has a fix in the works. I appreciate the consideration though!

**Comment by benbusby** [comment]
Merged in with #86 (b2133edaa326a7b14a49a0506d2f76d1424efe8f)
