### ISSUE TITLE
Home Page footer text in Dark Mode

### ISSUE THREAD

**Issue by Backup700** [benbusby/whoogle-search#75]
When dark mode is ON, the footer of home page i.e version number & Github link looks weird.

**Comment by benbusby** [comment]
Fixed in d1f38cf9242e163febd0907c2080752459b7618a.

**Comment by Backup700** [comment]
@benbusby this issue again arises on home page footer in new commit 0.2.0 version.

**Comment by benbusby** [comment]
@Backup700 thanks for the heads up, just pushed a fix.
