### ISSUE TITLE
[BUG] Wrong serch result at second page of result of search

### ISSUE THREAD

**Issue by navhawk80** [benbusby/whoogle-search#754]
Hello. On firefox if I right click highlighted text and hit "Search Whoogle for ..." all goes well and I have a page with result of search but it adds '&cookies_disabled=1' into address bar 'https://<whogle.example.com>/search?cookies_disabled=1'. If I push the 'second page' at the bottom of the search page with resulf of search it will redirect to page 'https://<whogle.example.com>/search?q=gAAAAABiez8uMkjVi7T6kSFVm5WCBrWbP8IJDJfcjbUWK2WvI9FvL5K8J0rGCoiuAb7U0oK3sqVyzGqnn8yNq4-cqvLBV2xWIQ==&start=10' and 'no results were found for  gAAAAABiez8uMkjVi7T6kSFVm5WCBrWbP8IJDJfcjbUWK2WvI9FvL5K8J0rGCoiuAb7U0oK3sqVyzGqnn8yNq4-cqvLBV2xWIQ==&start=10' as an example.
I use docker latest at the moment version 0.7.2 on xpenology behind reverse proxy with Let'sencrypt sertificate. Problem came since 0.7.0 version.
![whoogle serach](https://user-images.githubusercontent.com/73139535/167774857-bcd7c32f-8e82-4f72-aab3-99c8f1b89f00.jpg)
Update: just checked in google chrome. The same issue.

**Comment by DUOLabs333** [comment]
Yeah, it seems to be an error with cryptography decrypting. If you go back to the first page and reload, it usually works.

**Comment by navhawk80** [comment]
For me it doesn't work. If I go to the first page and reload it will show me clean start page of whoogle. Continue to use 0.6.0 at the moment where all works well.

**Comment by DUOLabs333** [comment]
Just ancedotal --- once I pulled from git, I never had a problem.

**Comment by navhawk80** [comment]
> Just ancedotal --- once I pulled from git, I never had a problem.

Which version do you use? On latest 0.7.3 I still have this issue.

**Comment by DUOLabs333** [comment]
Interesting

**Comment by navhawk80** [comment]
The issue was solved when I added "GET Requests Only" into the docker container and re-add the search engine. https://github.com/benbusby/whoogle-search#using-with-firefox-containers Now all works well.
