### ISSUE TITLE
[BUG] No HTTPS on Firefox

### ISSUE THREAD

**Issue by askabaz22** [benbusby/whoogle-search#756]
**Describe the bug**
When I access Whoogle (Heroku instance) from Firefox (especially when I open it for the first time after a browser restart) it doesn't redirect to HTTPS, and I need to update the page a few time to get a HTTPS connection. I have problems both using the search bar (it's my default search engine), both accessing the website directly. How can I resolve this problem? 

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [0.7.1]
- [ ] Not sure

Screenshot:
![immagine](https://user-images.githubusercontent.com/81743377/168145672-4ced740a-104d-47cc-8a4b-61197228a3dc.png)

**Comment by benbusby** [comment]
Unfortunately this is a persistent problem with Heroku. Apps deployed through their service seem to have poor support for HTTPS (no automatic redirecting, bad certificates, etc). I'd recommend contacting their support and asking them about this. I've been hoping they would address it at some point, but this issue has been around with their service for years now.
