### ISSUE TITLE
Safe search always on.

### ISSUE THREAD

**Issue by ljbounty** [benbusby/whoogle-search#759]
I have deployed whoogle using rep.it as per the instructions. (b) The issue I am having is that the safe search is permanently on. I have tried to change it through whoogles configuration  but nothing changes.
Any ideas?

Thanks in advance.

**Comment by DUOLabs333** [comment]
Is there a way to test this (I don't know what safesearch blocks).

**Comment by ljbounty** [comment]
Hi,

Here is a link to the replit app.

https://whoogle-search.ljbounty.repl.co

Regardless of whether the safe search is ticked or not the results are filtered.  I have deployed the app through Heroku and the search does not filter results. Search for any adult content.
________________________________

**Comment by DUOLabs333** [comment]
Hmmm, can you try pulling from git?

**Comment by Albonycal** [comment]
^^

**Comment by ljbounty** [comment]
Everything was pulled from your git.
________________________________

**Comment by DUOLabs333** [comment]
Maybe replit itself is censoring?

**Comment by ljbounty** [comment]
You may have a point as I have successfully deployed using Heroku without any issues.
________________________________

**Comment by benbusby** [comment]
Closing, since this seems to just be a repl.it issue. Deployments on any other platform don't seem to have this problem.
