### ISSUE TITLE
[BUG] Images do not load

### ISSUE THREAD

**Issue by SangeloDev** [benbusby/whoogle-search#760]
**Describe the bug**
Images don't load when browsing. 
When opening Debug console, they point to ``localhost:port/element`` when behind NginX proxy.

**To Reproduce**
1. Use NginX as proxy and route domain.tld to localhost:port
2. Search anything
3. Click Images
4. See error (Images don't load)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from Docker: 0.7.2
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser: Firefox Development Edition
 - Version 101.0b5

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 pro
 - OS: EvolutionX ``Snow-v2-6.3.1-instantnoodlep / Android 12``
 - Browser Firefox Nightly
 - Version 102.0a1

**Additional context**
If there is any, I'll add it after an edit.

**Comment by DUOLabs333** [comment]
It seems that the image is not being routed through whoogle. This may be a result of f5d599e7.
