### ISSUE TITLE
[BUG] "_pickle.UnpicklingError: invalid load key" for pip installation

### ISSUE THREAD

**Issue by PrivacyDevel** [benbusby/whoogle-search#765]
**Describe the bug**
Whoogle Search displays "Internal Server Error" in the browser whenever I use it to make any search.
The home page gets displayed correctly and the problem seems to be specific to installations using pip.

The manual installation using git and venv is working however.

**Server OS**
Debian 11.3

**To Reproduce**
1. Search for anything using Whoogle Search
2. See "Internal Server Error" in client
3. Check logs to find Tracebacks

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [0.7.2]
- [ ] Not sure

**Client:**
The problem does not seem to be browser specific.
It happened with Firefox and curl for example.

**Traceback from logs**
```
May 21 19:55:12 debian whoogle[143677]: ERROR:app:Exception on /search [POST]
May 21 19:55:12 debian whoogle[143677]: Traceback (most recent call last):
May 21 19:55:12 debian whoogle[143677]:   File "/home/whoogle/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
May 21 19:55:12 debian whoogle[143677]:     response = self.full_dispatch_request()
May 21 19:55:12 debian whoogle[143677]:   File "/home/whoogle/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
May 21 19:55:12 debian whoogle[143677]:     rv = self.handle_user_exception(e)
May 21 19:55:12 debian whoogle[143677]:   File "/home/whoogle/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
May 21 19:55:12 debian whoogle[143677]:     rv = self.dispatch_request()
May 21 19:55:12 debian whoogle[143677]:   File "/home/whoogle/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
May 21 19:55:12 debian whoogle[143677]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
May 21 19:55:12 debian whoogle[143677]:   File "/home/whoogle/.local/lib/python3.9/site-packages/app/routes.py", line 79, in decorated
May 21 19:55:12 debian whoogle[143677]:     _ = pickle.load(session_file)
May 21 19:55:12 debian whoogle[143677]: _pickle.UnpicklingError: invalid load key, '\xa3'.
```

**Comment by benbusby** [comment]
Thanks for reporting, it should be fixed now. There should be a new pip version (0.7.3) available shortly.

**Comment by nobicycle** [comment]
Confirm solved. Thanks!
