### ISSUE TITLE
[QUESTION] Why does Whoogle randomize class names?

### ISSUE THREAD

**Issue by acoolstraw** [benbusby/whoogle-search#766]
This is a pain in the ass to style
![image](https://user-images.githubusercontent.com/45886986/169678068-1167b2fa-ca16-40d6-9041-1eec7e94cc5f.png)

**Comment by DUOLabs333** [comment]
Whoogle takes its HTML from Google, and Google randomizes its classes, probably to stop scrapers.

**Comment by acoolstraw** [comment]
Huh. How does Whoogle style those then?

**Comment by acoolstraw** [comment]
Interesting - currently `.ZINbbc` appears to be the class Google uses, and they have used it for at least a year, according to https://github.com/benbusby/whoogle-search/issues/274
