### ISSUE TITLE
How can i customize the footer part of image results

### ISSUE THREAD

**Issue by amirh-soleymani** [benbusby/whoogle-search#767]
i want to customize the footer of image result page, changing the links and titles (The section under pagination it has Sign in, Privacy, Terms, Location and other stuffs)
i can't find it's html code to change

**Comment by benbusby** [comment]
The footer content is part of the html returned by Google, and isn't something that Whoogle adds. You could add your own custom footer by adding content at the end of the `results.html` template, but this would be included across all result types (not just image results).
