### ISSUE TITLE
[QUESTION] Does Google know my local machine's IP when a make a query on Whoogle?

### ISSUE THREAD

**Issue by Gunther0042** [benbusby/whoogle-search#778]
I recently set up a self-hosted Whoogle instance. I noticed that if I searched for "what is my IP?" it returned the public IP of my local machine rather than the IP of the VPS the instance is hosted on. Is this intended behavior? If so, does it mean that Google knows my local machine's IP when a search on Whoogle?

**Comment by benbusby** [comment]
This is intended behavior, but Google does not see your local machine's IP. Your local IP is shown by Whoogle if it is available through either the `REMOTE_ADDR` or `HTTP_X_FORWARDED_FOR` header in the request. All requests sent to Google by Whoogle would only ever contain the IP of the VPS.

**Comment by Gunther0042** [comment]
Thank you for the response and for all your work on the project!
