### ISSUE TITLE
Add Wireguard support

### ISSUE THREAD

**Issue by brokoler** [benbusby/whoogle-search#783]
Since many VPN providers are removing SOCKS5 Proxy support, it would be great to add future proof VPN protocols to Whoogle.

Would it be possible to add Wireguard support in future?

Best regards

**Comment by DUOLabs333** [comment]
How do you envision such support looking like?

**Comment by ScriptedDeveloper** [comment]
You don't need Whoogle to implement this. It's easy enough to setup a docker image like [Gluetun](https://github.com/qdm12/gluetun) and bind the Whoogle container to it.

**Comment by benbusby** [comment]
I think this is a bit outside the scope of Whoogle and should be handled separately. In addition to the Gluetun solution mentioned above, it should also be simple enough to configure a wg client on the same machine as Whoogle and have all requests routed through accordingly.
