### ISSUE TITLE
[BUG] WHOOGLE_CONFIG_COUNTRY not changing country

### ISSUE THREAD

**Issue by jjakc-76** [benbusby/whoogle-search#784]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Set WHOOGLE_CONFIG_COUNTRY to countryUK
2. Recreate container
3. Go to homepage, the country is set, but when searching it's still the country where the instance is hosted (for me, Germany)
4. If you go back to the homepage and just click "Apply" then it works.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version latest

[Right after container is made](https://i.imgur.com/HoS0gHv.png)
[Search results without right after container is made](https://i.imgur.com/YSKrP3b.png)
[Search results after clicking "Apply"](https://i.imgur.com/vXN2Srj.png)

**Comment by benbusby** [comment]
The "country" prefix isn't needed and isn't recognized as a valid param when forwarding the search to Google. The correct setting for this would be just `WHOOGLE_CONFIG_COUNTRY=UK`. The template currently just checks to see if the any country value (`UK` in this case) matches any part of the config setting (`countryUK`), which incorrectly makes it seem like the config value is set up. I'll push a fix in a sec to clarify that.

**Comment by benbusby** [comment]
OK, should be updated on main/latest now.
