### ISSUE TITLE
[BUG] Internal Server Error: OverflowError: BINBYTES exceeds system's maximum size of 2147483647 bytes

### ISSUE THREAD

**Issue by dnwk** [benbusby/whoogle-search#793]
**Describe the bug**
Getting Internal Server error when searching. Log says BINBYTES exceeds system's max

OverflowError: BINBYTES exceeds system's maximum size of 2147483647 bytes

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc) v0.7.4 
- [ ] Version [version number]
- [ ] Not sure

**Additional context**
Jun 16 09:13:07 unificontroller whoogle[30879]: ERROR:app:Exception on /search [POST]
Jun 16 09:13:07 unificontroller whoogle[30879]: Traceback (most recent call last):
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
Jun 16 09:13:07 unificontroller whoogle[30879]:     response = self.full_dispatch_request()
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
Jun 16 09:13:07 unificontroller whoogle[30879]:     rv = self.handle_user_exception(e)
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
Jun 16 09:13:07 unificontroller whoogle[30879]:     reraise(exc_type, exc_value, tb)
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
Jun 16 09:13:07 unificontroller whoogle[30879]:     raise value
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
Jun 16 09:13:07 unificontroller whoogle[30879]:     rv = self.dispatch_request()
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
Jun 16 09:13:07 unificontroller whoogle[30879]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 16 09:13:07 unificontroller whoogle[30879]:   File "/usr/local/lib/python3.9/dist-packages/app/routes.py", line 79, in decorated
Jun 16 09:13:07 unificontroller whoogle[30879]:     _ = pickle.load(session_file)
Jun 16 09:13:07 unificontroller whoogle[30879]: OverflowError: BINBYTES exceeds system's maximum size of 2147483647 bytes

**Comment by benbusby** [comment]
Thanks for reporting. This should be fixed now, I'll try to release a new pip version soon. In the meantime you can use the [TestPyPi version](https://test.pypi.org/project/whoogle-search/0.7.4.dev1655401870/) of the package to validate the fix.

**Comment by dnwk** [comment]
With the TestPypi version, I am getting a different error

whoogle[32382]: ERROR:app:Exception on /search [POST]
Jun 16 11:49:46 unificontroller whoogle[32382]: Traceback (most recent call last):
Jun 16 11:49:46 unificontroller whoogle[32382]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
Jun 16 11:49:46 unificontroller whoogle[32382]:     response = self.full_dispatch_request()
Jun 16 11:49:46 unificontroller whoogle[32382]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
Jun 16 11:49:46 unificontroller whoogle[32382]:     rv = self.handle_user_exception(e)
Jun 16 11:49:46 unificontroller whoogle[32382]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
Jun 16 11:49:46 unificontroller whoogle[32382]:     rv = self.dispatch_request()
Jun 16 11:49:46 unificontroller whoogle[32382]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
Jun 16 11:49:46 unificontroller whoogle[32382]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jun 16 11:49:46 unificontroller whoogle[32382]:   File "/home/pi/.local/lib/python3.9/site-packages/app/routes.py", line 83, in decorated
Jun 16 11:49:46 unificontroller whoogle[32382]:     _ = pickle.load(session_file)
Jun 16 11:49:46 unificontroller whoogle[32382]: ValueError: could not convert string to float: '��d�#005��'
Jun 16 11:49:46 unificontroller whoogle[32382]: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by benbusby** [comment]
Super weird. I can't reproduce this at all, but it seems like some pip-installed versions of Whoogle write unrelated/non-session files to the session file directory, which Whoogle doesn't expect. I just broadened the exception handling to ignore these errors since it isn't a terribly important feature and I don't think it's worth investing much more time into it. 

This release has that modification, hopefully you stop seeing these errors now: https://test.pypi.org/project/whoogle-search/0.7.4.dev1655416022/

**Comment by dnwk** [comment]
Thanks. I'll try again later. I switched to Docker version, and it works well.
