### ISSUE TITLE
[BUG] opensearch.xml always using localhost

### ISSUE THREAD

**Issue by JohnCMoon** [benbusby/whoogle-search#8]
When using Docker behind an Nginx proxy and ran into an issue where "Adding Search Engine" with Firefox isn't working. The base URL in the opensearch.xml file ends up being "localhost:8888" instead of my host URL.

**To Reproduce**
1. In Firefox, navigate to a non-localhost instance of Whoogle
2. Click on the three dots in the URL -> Add Search Engine
3. Attempt to search in Firefox with the new Whoogle engine
4. See "unable to connect to localhost:8888"

**Expected behavior**
The browser search engine would use the actual URL of the instance (passed with the `--host` param).

**Workaround**
I worked around this issue by changing the `main_url` param in `routes.py` to use my custom domain:
`template = render_template('opensearch.xml', main_url='<MY_URL_HERE>')`

**Comment by benbusby** [comment]
Hey @JohnCMoon, thanks for bringing this to my attention. I just pushed an update that allows for configuration of a root URL using the config section on the main page of the app. Try setting that to your host URL and let me know if that ends up working for you.

Oh and you'll likely need to remove the existing search config for Whoogle search from your Firefox preferences before trying this again (in case you haven't done that already).

**Comment by benbusby** [comment]
Closing for now, as I believe this is fixed. Feel free to reopen if that isn't the case. Thanks!

**Comment by JohnCMoon** [comment]
Yep, this is fixed. Thank you!

**Comment by GyokuroT** [comment]
> 
> 
> Hey @JohnCMoon, thanks for bringing this to my attention. I just pushed an update that allows for configuration of a root URL using the config section on the main page of the app. Try setting that to your host URL and let me know if that ends up working for you.
> 
> Oh and you'll likely need to remove the existing search config for Whoogle search from your Firefox preferences before trying this again (in case you haven't done that already).

I also run Whoogle behind a reverse proxy. Does it have any adverse effects if some random internet user changes the root URL?

**Comment by JohnCMoon** [comment]
Hmm, yeah I suppose it would. Might want to keep this option server-side.
