### ISSUE TITLE
[BUG] wikipedia alternative does not work for different languages

### ISSUE THREAD

**Issue by erikderzweite** [benbusby/whoogle-search#805]
**Describe the bug**
If you use alternative to wikipedia it works for english language only. If you look for content in other languages not existing in English Wikipedia, then you land in the wikiless starting page upon clicking the link.

If you provide 

`WHOOGLE_ALT_WIKI=wikipedia.org
`
then all the wikipedia pages are opened in English Wikipedia regardless of the language of the original link. 

Is there any way to disable alt links for wikipedia only?

**To Reproduce**
1. Search for e.g. "Heinrich Heine"
2. Try to open wikipedia link starting with "de."
3. You land on English wikipedia page. 

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by benbusby** [comment]
If you set the alt to an empty value (in this case `WHOOGLE_ALT_WIKI=""` it will skip using wikiless and use the original wikipedia link instead.

**Comment by erikderzweite** [comment]
But it does not use the original link. Instead of e.g. https://de.wikipedia.org/wiki/Something it tries to open https://wikipedia.org/wiki/Something even if the page does not exist in English.

**Comment by erikderzweite** [comment]
You are awesome, thank you! Newest docker build works with alternative wikipedia and languages.
