### ISSUE TITLE
[QUESTION] changing WHOOGLE_ALT_YT=http://192.168.1.5:3000 still inserts https

### ISSUE THREAD

**Issue by orkowizard** [benbusby/whoogle-search#806]
The links are incorrectly resolved to:

`https://http//192.168.1.5:3000/watch?v=B3SMn-J5sPw`

I don't want "https" as my local server running invidious is at http://192.168.1.5:3000. Any ideas?

**Comment by orkowizard** [comment]
Getting a certificate is unnecessary since this is a locally run service, so it would be nice to read the http part correctly and not default to prepending https:// to all urls.

**Comment by orkowizard** [comment]
I would be willing to take this work on as a new "feature" , let me know.

**Comment by benbusby** [comment]
@orkowizard if you'd like to work on this, I think it'd be a fairly straightforward fix. The only function that would need changes is `get_site_alt` in `app/utils/results.py`, which could be updated to check if the value set for the alternative has a defined scheme (and if so, remove the scheme used for the targeted site).

**Comment by benbusby** [comment]
@orkowizard hope you don't mind, but I just pushed a fix since it was a relatively small change. Hopefully that works for you!

**Comment by orkowizard** [comment]
@benbusby Thanks, I actually had the dev environment and tests all setup and running as of yesterday, but hadn't actually done any implementation yet. Maybe the next feature request!

**Comment by orkowizard** [comment]
@benbusby The link works but the display still prepends www fyi: 

![image](https://user-images.githubusercontent.com/113277/179796687-66d01868-fa0e-474a-9be0-1fe093d9004f.png)
