### ISSUE TITLE
[BUG] Bad redirection with google services

### ISSUE THREAD

**Issue by jacr13** [benbusby/whoogle-search#81]
**Describe the bug**
When you search for a google service served as google.com/service the result link provided by google is 'href="/gmail/"'. When you try to click the search result the link redirects to the Whoogle home instead of the real service. 
A simple check to verify that the url starts with '/' should be enough to catch such results and redirect them to the real url google + service.

**To Reproduce**
1. Search for "gmail"
2. Click on the first link (google.com/gmail)
3. Redirects to Whoogle home instead of google.com/gmail

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- Github master

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox

**Comment by benbusby** [comment]
Fixed with 78939e7fb447eff2613200c448716870b9aa1c68
