### ISSUE TITLE
[QUESTION] apache2 proxy for subpath breaks layout

### ISSUE THREAD

**Issue by Sailing74** [benbusby/whoogle-search#812]
I am trying to use the path /search on my existing apache as a proxy for Whoogle:

`                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass /search http://whoogle.example:5000/
                ProxyPassReverse /search http://whoogle.example:5000/`

Config menu is always shown, Whoogle-logo stretches across the entire breadth of the page, etc. I suppose the config cannot be read in such instance.

Any idea how to get this working? I tried setting WHOOGLE_CONFIG_URL to https://www.example.com/search, but this didn't help.

**Comment by Hydranet** [comment]
I think you want to use this [variable](https://github.com/benbusby/whoogle-search#environment-variables) for a sub path/url, this worked for me.

WHOOGLE_URL_PREFIX | The URL prefix to use for the whoogle instance (i.e. "/whoogle")
