### ISSUE TITLE
Results filtration, is that possible?

### ISSUE THREAD

**Issue by prp-e** [benbusby/whoogle-search#815]
Hello.
I'm just curious if it is possible to filter results from certain websites, for both white listing or black listing. For example, just limiting the results to my website or searching everywhere except my website.
Also, I'm asking this in code level, not search tricks.
Thanks.

**Comment by DUOLabs333** [comment]
For blocking, you can do `WHOOGLE_CONFIG_BLOCK`. For white listing, you can use "site:www.example.com".

**Comment by benbusby** [comment]
Yes, with `WHOOGLE_CONFIG_BLOCK` you can block individual websites with a comma separated list of domains. To only search your website without using the search, that isn't something available with an environment variable or other setting, but you could modify the search code to only search your website. The file `request.py` would be the one to modify, which you could hardcode with the "site:<domain>" thing that @DUOLabs333 mentioned.
