### ISSUE TITLE
HTTP element not upgraded when Google Definition box is served

### ISSUE THREAD

**Issue by Matthius453** [benbusby/whoogle-search#82]
**Bug Description**
- When searching for a definition of a word for example, a Google definition box element at the top of the page is present. When this is served with Whoogle, the connection no longer becomes secure. Any other search term which provides similar types of boxes such as currency conversion doesn't present this issue.
Looking at the HTML, the only non-HTTPS Link is the audio source - so it could be this. 
![image](https://user-images.githubusercontent.com/21284075/83120519-13d7c580-a0c9-11ea-9ec2-743d0dc49cf4.png)

**Steps to reproduce the behavior:**
1. Type in 'coding definition' (for example) to Whoogle
2. Observe connection is no longer secure

**Deployment Method**
- Docker, accessed through reverse Nginx Proxy with a LetsEncrypt Certificate

**Version of Whoogle Search**
- Version 0.1.4

**Desktop and Mobile where the behavior is observed:**
 - Browser: Chrome, Brave, Edge - All are affected the same on PC and on Mobile

![image](https://user-images.githubusercontent.com/21284075/83119325-7a5be400-a0c7-11ea-9195-c203577f28cc.png)

**Comment by benbusby** [comment]
Implemented in #85 and will be available soon on the `beta` tag release on Docker Hub, with a full release once that has been thoroughly tested.
