### ISSUE TITLE
[BUG] 405 Method not allowed

### ISSUE THREAD

**Issue by sutidor** [benbusby/whoogle-search#821]
**Describe the bug**
When I enter any term in the address bar for the first time: 405 Method not allowed
When I enter this term or any other term AGAIN to the same address bar DIRECTLY AFTER, it will search normally.

Since I could not find any1 else with this issue I presume there is an issue in my config but it only happened in versions 0.7 onward (currently 0.7.4). Using firefox and reinstalled the search engine with current version. Behind nginx reverse proxy. Happens on smartphone, too.

**To Reproduce**
1. Go to address bar
2. search anything (405 Method not allowed)
3. search again
4. searches normally

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox 
 - Version 102

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tootbrute** [comment]
Just chiming in to say that I have this same problem but only on some of my machines. Information below.

Deployment Method
--> Docker
(running on Yunohost behind NGINX)

Version of Whoogle Search
--> Version 0.7.4

Desktop:

--> OS: Fedora 36 (no problems!)
    Browser Firefox
    Version 102

--> OS: Ubuntu 22
    Browser: Firefox (get this 405 error)
    Version: 103

--> OS: Ubuntu 22 (same system as above)
    Browser: Brave (no 405 error, but doesn't complete search, just shows a blank Whoogle page)
    Version: 1.41.100 Chromium: 103.0.5060.134 (Official build) (64-bit)

Smartphone (please complete the following information):

--> Device: Asus Zenfone Pro Max 2
    OS: LineageOS 18.1
    Browser Firefox (Currently can't add Whoogle search to Firefox "error connecting to Whoogle")
    Version 102.2.1

(same device as above) - works!
Browser: Bromite
Version 103.0.5060.140

**Comment by erikderzweite** [comment]
Deployment Method
--> Docker
(running on Yunohost behind NGINX)

Version of Whoogle Search
--> Version 0.7.4

--> OS: Ubuntu 18
Browser: Firefox (405 error second search works fine, after a longer pause 405 again)
Version: 103

--> OS: Ubuntu 18
Browser: Chromium (no 405, just whoogle landing page after putting a search term in address bar, second search works)
Version:  103.0.5060.134 snap

**Comment by benbusby** [comment]
@sutidor (or anyone else with this issue) can you give me a breakdown of the full request details sent to Whoogle when the 405 code is returned (i.e. which endpoint, what request type (POST vs GET), etc)? I'm wondering if there's an opensearch caching issue here. I haven't been able to reproduce on my end, so I'll have to debug this a bit blind.

**Comment by sutidor** [comment]
@benbusby from the opensearch.xml I assume it is a POST request. Additional context sent to the email provided  in your github (contact@) Thank you

**Comment by benbusby** [comment]
@sutidor could you (or anyone here) try out the latest changes on `main` or the `latest` Docker tag (once it's finished building -- should be out in the next ~15-30 mins)? I just pushed a fix for a different issue that I think might fix this issue as well, hopefully.

**Comment by tootbrute** [comment]
> @sutidor could you (or anyone here) try out the latest changes on `main` or the `latest` Docker tag (once it's finished building -- should be out in the next ~15-30 mins)? I just pushed a fix for a different issue that I think might fix this issue as well, hopefully.

On Fedora, Firefox and Brave it is now working for me using the latest image.

```
$ sudo docker images
REPOSITORY                     TAG       IMAGE ID       CREATED         SIZE
benbusby/whoogle-search        latest    31b9b63a5770   10 hours ago    108MB
```

**Comment by benbusby** [comment]
Thanks for clarifying. I'm going to assume this is fixed for everyone, but anyone can feel free to re-open if that's not the case for them.
