### ISSUE TITLE
Directed to Ebay instead of getting search results

### ISSUE THREAD

**Issue by itguy327** [benbusby/whoogle-search#830]
**Describe the bug**
Searching for below "Search for:" string automatically sends me to Ebay

**To Reproduce**
Open Search
Search for: [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 401 Unauthorized):

**Deployment Method**
Proxmox LXC (Debian 11)

**Version of Whoogle Search**
Latest

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by AlyoshaVasilieva** [comment]
I think it's seeing `E!`, activating the eBay bang, and trying to send you to an eBay search for the rest of the query
