### ISSUE TITLE
Setting whoogle as default search engine on iOS Firefox crashes app

### ISSUE THREAD

**Issue by alexw1982** [benbusby/whoogle-search#832]
See title. 

deleted and reinstalled app with no luck

Running latest iOS 15.6.1 (iPhone Xr) and latest Firefox Daylight 104.0 (15741).

Somehow this only happens on iPhones not iPads

**Comment by trancefam** [comment]
This is a bug related to Firefox mobile, not whoogle. I encountered the same problem and updating to the latest version of the FF app resolved it.

**Comment by alexw1982** [comment]
Can confirm the problem is fixed using latest FF mobile on iOS
