### ISSUE TITLE
[FEATURE] Render.com as an alternative to heroku.

### ISSUE THREAD

**Issue by AkumaX1** [benbusby/whoogle-search#833]
As we all know heroku is no longer a viable option for people who want to deploy whoogle for free just for personal use.

So i just tried render.com , it works flawlessly. Just while deploying choose python 3 and build command as " pip install -r requirements.txt " and start command as " ./run " .
Now go down to advance and add all the environmental variables you need , just deploy after that . 

ENJOY !!! 🎉

**Comment by SebastianTrautwein** [comment]
For everyone who wants to host their Whoogle instance anonymously: Don't bother! It's a bait and switch. They tell you "free" for the base service but after registration, when you want to deploy, they ask for your Credit Card details "for verification".

**Comment by AkumaX1** [comment]
> For everyone who wants to host their Whoogle instance anonymously: Don't bother! It's a bait and switch. They tell you "free" for the base service but after registration, when you want to deploy, they ask for your Credit Card details "for verification".

render.com actually is very similar to heroku . they gave you around 700 hrs each month with even custom domain support . no credit card needed. Its perfectly usable .

**Comment by trumad** [comment]
Thanks for those instructions @AkumaX1 . render.com does work, and it is definitely free without requiring a credit card. But it seems to take around 10 seconds to load pages, even when the "dyno", or whatever render.com calls it, is already up & running. It's super easy to set up, and definitely free, but unfortunately this won't be an adequate replacement for me.

**Comment by HashLiver** [comment]
![chrome_DPSpLZOT46](https://user-images.githubusercontent.com/42889797/194750708-5cc61ed1-d7cf-48a9-b515-33359e504af9.png)

Yep, It's work, but performance suck, sometimes it takes 2-5 seconds to response for a search keyword.

**Comment by hxvy0** [comment]
> Yep, It's work, but performance suck, sometimes it takes 2-5 seconds to response for a search keyword.

I use replit, but boosted repl. I bought for 1.5 dolars. And its so fast
