### ISSUE TITLE
[FEATURE] Search query correction

### ISSUE THREAD

**Issue by baduhai** [benbusby/whoogle-search#84]
**Describe the feature you'd like to see added**
It'd be nice if whoogle could display if google has corrected a typo on the search query, and give the option to search instead for what google considers a typo.

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
Front end and back end? Not sure

**Additional context**
This is what I mean: 
![Screenshot_20200529_123430](https://user-images.githubusercontent.com/31864305/83255672-c468c680-a1a8-11ea-9cdc-9c0f14a82854.png)

**Comment by benbusby** [comment]
Implemented in #85 and will be available soon on the `beta` tag release on Docker Hub, with a full release once that has been thoroughly tested.
