### ISSUE TITLE
[BUG] Translate Bug (PussTheCat.org Translate Box)

### ISSUE THREAD

**Issue by mon5termatt** [benbusby/whoogle-search#859]
**Describe the bug**
![image](https://user-images.githubusercontent.com/43628254/195712857-87689513-254f-495f-9826-eb558a3a3de8.png)

**To Reproduce**
Search for "Translate"

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [v0.7.4]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise LTSC]
 - Browser [Chrome]
 - Version [106.0.5249.119 (Official Build) (64-bit)]

Maybe trying to embed wrong url?
Service is still up @ https://simplytranslate.pussthecat.org/

**Comment by benbusby** [comment]
Fixed in https://github.com/benbusby/farside/commit/4875147321879e2a8a88949ac24fd7f4320666eb. Thanks!
