### ISSUE TITLE
Heroku has stopped offereing the free tier 

### ISSUE THREAD

**Issue by Albonycal** [benbusby/whoogle-search#862]
Heroku will stop  offering its free tier from November, so shouldn't it be removed from the readme?

https://blog.heroku.com/next-chapter

**Comment by files18** [comment]
Would be better if left for paid users . @Albonycal

**Comment by files18** [comment]
Would be better if left a note . Imao Will make a pull request updating public instances and fixing heroku maybe.

**Comment by files18** [comment]
@Albonycal  Maybe this would work : https://github.com/benbusby/whoogle-search/pull/864
