### ISSUE TITLE
[BUG] Autocompletions aren't in the configured locale

### ISSUE THREAD

**Issue by vijfhoek** [benbusby/whoogle-search#863]
**Describe the bug**
Autocompletions aren't in the configured locale

**To Reproduce**
1. Set Country to desired language in Configuration (in my case, Netherlands)
2. Type something in the search field ("test" works)
3. Get suggestions for the wrong country (in my case, Germany)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.7.4
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 106.0

**Comment by jacr13** [comment]
Should be fixed by #866.

If you whant to have suggestions based on the interface language, please select "Set Accept-Language: " in configuration.
