### ISSUE TITLE
[QUESTION] Can you add my istance?

### ISSUE THREAD

**Issue by hxvy0** [benbusby/whoogle-search#868]
Hi, I'm Enes from turkey. Can you add my istance.

Url: https://www.indexia.gq
Language: Multi-Choice
Cloudflare: Yes

**Comment by jacr13** [comment]
Hello, you should create a pull request that modifies the README with your instance.

**Comment by benbusby** [comment]
I took care of it since I was just updating the instance lists anyways. Thanks!
