### ISSUE TITLE
[BUG] https not available with --build-arg use_https=1

### ISSUE THREAD

**Issue by stx233** [benbusby/whoogle-search#87]
**Describe the bug**
Cannot access to https following the documentation regarding whoogle and docker

**To Reproduce**
git clone https://github.com/benbusby/whoogle-search.git
cd whoogle-search
docker build **--build-arg use_https=1** --tag whoogle-search:1.0 .
docker run --publish 5000:5000 --detach --name whoogle-search whoogle-search:1.0

Opening a firefox browser : 
https://host:5000 does not work
http://host:5000 is ok

**Deployment Method**
- [X ] Docker

**Version of Whoogle Search**
- [X ] Not sure

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser Firefox
 - Version last stable

**Comment by benbusby** [comment]
It looks like you're accessing your whoogle instance using the host address over HTTPS but without generating a certificate beforehand (which would also require a domain name). I'll update the README to clarify that, sorry for the confusion.

If you need HTTPS, you'd want to buy a domain name, make sure the domain points to your hosting setup, and generate a certificate with something like [LetsEncrypt](https://letsencrypt.org/getting-started/) to allow HTTPS access with Nginx/Apache/etc.

**Comment by benbusby** [comment]
README updated. Thanks for the report!

**Comment by stx233** [comment]
> It looks like you're accessing your whoogle instance using the host address over HTTPS but without generating a certificate beforehand (which would also require a domain name). I'll update the README to clarify that, sorry for the confusion.
> 
> If you need HTTPS, you'd want to buy a domain name, make sure the domain points to your hosting setup, and generate a certificate with something like [LetsEncrypt](https://letsencrypt.org/getting-started/) to allow HTTPS access with Nginx/Apache/etc.

Hi thank you for the update 

If I use self-signed certificate with mkcert for example on my host, are there any settings to add to the build in docker ?
