### ISSUE TITLE
Is a temporary problem?

### ISSUE THREAD

**Issue by banphi** [benbusby/whoogle-search#870]
Hi i'm deployng on portainer but i receive this demployment error:

> failed to deploy a stack: whoogle Pulling whoogle Error Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution 

There are some problems?

Thank you

**Comment by banphi** [comment]
> Hi i'm deployng on portainer but i receive this demployment error:
> 
> > failed to deploy a stack: whoogle Pulling whoogle Error Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
> 
> There are some problems?
> 
> Thank you

Sorry to everyone.
It was my fault.
I don't know how, but i mess with resolv.conf .
Thank anyway.

**Comment by Albonycal** [comment]
It's always DNS
