### ISSUE TITLE
whooglesearch.ml instance broken

### ISSUE THREAD

**Issue by boognish-rising** [benbusby/whoogle-search#874]
I looked around a bit and didn't notice any alternative options for reporting broken/down instances so I apologize if this is out of place but for several weeks now, https://www.whooglesearch.ml/ has been out of commission. Depending on which browser/device I visit the link from (I had it configured as my home page/NTP on _a lot_ of different browsers, otherwise I probably would've noticed it one time only prior to removing it from rotation, however since I haven't changed the configuration of all browsers that had it set as either the Home or New Tab Page, I am constantly reminded of the fact that it's down), what is displayed at that address varies and I don't recall if it was associated with that instance or if I'm mixing it up with any number of Invidious instances that operate on a revolving-door basis from "UP" to "DOWN" and back again but I want to say that on one or 2 occasions, I was met by something pretty shady looking that lead me to believe that this instance is a definite goner. Fortunately, there seems to be more stability/consistency with Whoogle instances but I suppose if I'm inclined to whine about it, it's time to stop putting it off and self-host my own instance already...

PS - just confirmed it was this instance that the shadiness had been witnessed. Visiting the url with Midori gives no indication what lurks just beyond but visiting with any number of Chromium browsers will get you the Privacy Warning Splash Page but if you then push past, you'll be greeted by what looks like a grand old time (see screenshot #3) Anyway, just FYI. Do with this info what you will (prob remove the instance from the list though 🤪️🤡️)

![Screenshot_23](https://user-images.githubusercontent.com/76668060/199178638-e3cde14b-893e-4f47-909c-18e7dfcf692c.png)

![Screenshot_24](https://user-images.githubusercontent.com/76668060/199179221-7d0093da-d843-451b-9ec7-acd1cc65fe43.png)

![Screenshot_25](https://user-images.githubusercontent.com/76668060/199179321-239f6270-6b60-494c-9c19-7e921932d385.png)

**Comment by benbusby** [comment]
Thank you for bringing this to my attention! The instance has been removed.

**Comment by boognish-rising** [comment]
Don't mention it. Thank YOU for Whoogle Search. I use the hell out of it.

If only there were more devs doing what you did (and continue to do) with Whoogle to the nearly endless number of other Google services, currently privacy conscious individuals wouldn't need to forgo so many creature comforts. For those that build of the rest of the world that isn't necessarily privacy conscious, the prospect of de-googling ones life is no easy task and it's enough to discourage even the most committed of privacy nerds... If Google services could be neutered of their inherent bad behaviors where users are concerned, i.e., tracking, data harvesting, etc etc, it would provide a much more palatable and frankly needed alternative to the more extreme approaches that exist to gain any amount of privacy while using smart devices and/or navigating the web.

Admittedly, I don't know if it's even possible to do what you did with Whoogle to other G services (Invidious, NewPipe and the slew of other privacy respecting alternatives that exist but aren't necessarily Google services alternatives seem to all support the notion that it's feasible) but I have to imagine it's possible with at least some of them. I'm clearly not a developer but as these types of opinions gain steam, I'm inclined to see what it would take to make the jump from enthusiast to n00b dev. Even if I was only able to bring one Whoogle-esque service into being, it'd totally be worth it.

**Comment by benbusby** [comment]
> If Google services could be neutered of their inherent bad behaviors where users are concerned, i.e., tracking, data harvesting, etc etc, it would provide a much more palatable and frankly needed alternative to the more extreme approaches that exist to gain any amount of privacy while using smart devices and/or navigating the web.

I definitely agree, but it's an unfortunate reality that they'll never give up that side of their business. They can pretty much print money with relatively little effort, so in a sense I "get it", although I don't agree with that approach obviously.

> I'm clearly not a developer but as these types of opinions gain steam, I'm inclined to see what it would take to make the jump from enthusiast to n00b dev. Even if I was only able to bring one Whoogle-esque service into being, it'd totally be worth it.

You should give it a try! You could even start with minor code contributions to the projects you've mentioned (Whoogle, Invidious, etc) and see what you like/don't like about development. Everyone starts somewhere, and the fact that you have a specific area of tech that you're enthusiastic about is a great start. As a side note, I didn't start programming until my early 20s (which at the time felt too old to pivot from musician -> programmer) but I made it work and am (mostly) happy I made the jump.
