### ISSUE TITLE
[BUG] Whoogle personal cloud docker instance suddenly showing arabic and right to left layout

### ISSUE THREAD

**Issue by Rochey** [benbusby/whoogle-search#877]
I setup an instance of whoogle on a ubuntu oracle cloud server last week. I used docker to get the latest version of whoogle and have been using it on my fedora laptop and my Pixel 6 phone. It's been working fine and the results have always been in English with the interface showing English too. Unfortunately about 1 or 2 hours ago I noticed I was getting search results in English but with the display showing right to left and the interface language showing in Arabic This happened on both my laptop and my phone. I actually thought someone had hacked my instance so deleted the docker instance and tried again but am still getting the issue.

**To Reproduce**
1. Go to 'my whoogle instance url' - I don't want to share the url as I want to keep it personal
2. Click on 'search box and enter search term then return'
3. See error = search results shown in English with right to left formatting and the interface (like NEXT) showing in Arabic

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]                            Fedora Silverblue on laptop and 
 - Browser [e.g. chrome, safari]    Firefox
 - Version [e.g. 22]                        105.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]                         Pixel 6
 - OS: [e.g. iOS8.1]                                 Android 13
 - Browser [e.g. stock browser, safari]    Bromite
 - Version [e.g. 22]                                  106

**Additional context**
I tired setting the additional env variables for language and I seem to have fixed the mobile version with these additional settings but the desktop version is still showing the issues.
added env:
   -e WHOOGLE_CONFIG_LANGUAGE=lang_en \
   -e WHOOGLE_CONFIG_SEARCH_LANGUAGE=lang_en \

docker command:
docker run --restart=always --publish 5000:5000 --detach --name whoogle-search \
   -e WHOOGLE_CONFIG_URL=https://xxx.xxx.xx\
   -e WHOOGLE_CONFIG_THEME=system \
   -e WHOOGLE_CONFIG_DISABLE=1\
   -e WHOOGLE_CONFIG_ALTS=1 \
   -e WHOOGLE_ALT_TW=xxx.xxx.xxx \
   -e WHOOGLE_ALT_YT=xxx.xxx.xxx \
   -e WHOOGLE_ALT_RD=xxx.xxx.xxx \
   -e WHOOGLE_ALT_TL=xxx.xxx.xxx\
   -e WHOOGLE_ALT_WIKI=xxx.xxx.xxx \
   -e WHOOGLE_CONFIG_NEW_TAB=1 \
   -e WHOOGLE_RESULTS_PER_PAGE=30 \
   -e WHOOGLE_CONFIG_GET_ONLY=1 \
   -e WHOOGLE_CONFIG_LANGUAGE=lang_en \
   -e WHOOGLE_CONFIG_SEARCH_LANGUAGE=lang_en \
   benbusby/whoogle-search:latest

Happy to share my personal URL with support for help with troubleshooting. I just don't want to post it publicly.

**Comment by Rochey** [comment]
An update to this issue, If I set the docker container to the following:
docker run --restart=always --publish 5000:5000 --detach --name whoogle-search \
   -e WHOOGLE_CONFIG_URL=xxx.xxx.xxx \
   -e WHOOGLE_CONFIG_THEME=system \
   -e WHOOGLE_CONFIG_DISABLE=0 \
   -e WHOOGLE_CONFIG_ALTS=1 \
   -e WHOOGLE_ALT_TW=xxx.xxx.xxx \
   -e WHOOGLE_ALT_YT=xxx.xxx.xxx \
   -e WHOOGLE_ALT_RD=xxx.xxx.xxx  \
   -e WHOOGLE_ALT_TL=xxx.xxx.xxx  \
   -e WHOOGLE_ALT_WIKI=xxx.xxx.xxx  \
   -e WHOOGLE_CONFIG_NEW_TAB=1 \
   -e WHOOGLE_RESULTS_PER_PAGE=30 \
   -e WHOOGLE_CONFIG_GET_ONLY=1 \
   -e WHOOGLE_CONFIG_LANGUAGE=lang_en \
   benbusby/whoogle-search:latest

It seems to fix the issue on my Pixel 6, Android 13, Bromite browser. If I check the configuration settings it shows as "Interface Language: English" which I believe is due to env variable "WHOOGLE_CONFIG_LANGUAGE=lang_en" (Note at the bottom of the whoogle search page it says "Dubai" and I don't know why? My cloud instance is running from a Cardiff Data centre.

If I try from my Fedora Firefox browser I still see Right to Left text and Arabic writing and if I check the configuration settings it shows as "Interface Language: -----------".

Why is the Firefox browser not seeing the "WHOOGLE_CONFIG_LANGUAGE=lang_en" env variable????

**Comment by Rochey** [comment]
Another update to this issue and I think it could be closed if someone could answer my questions below.

I couldn't understand why my phone was working but my laptop with Firefox was showing right to left text so I decided to create a new Firefox profile and test and, would you believe it, it was working fine on the new profile. I went back to my original profile on the same laptop and the issue was still there. My assumption now is that adding "Whoogle" as my default search engine had somehow remembered the right to left text and Arabic writing. 

I've now used the following docker settings (see the last 3 env variables):
docker run --restart=always --publish 5000:5000 --detach --name whoogle-search \
   -e WHOOGLE_CONFIG_URL=https://onics.duckdns.org \
   -e WHOOGLE_CONFIG_THEME=system \
   -e WHOOGLE_CONFIG_DISABLE=0 \
   -e WHOOGLE_CONFIG_ALTS=1 \
   -e WHOOGLE_ALT_TW=nitter.tiekoetter.com \
   -e WHOOGLE_ALT_YT=invidious.tiekoetter.com \
   -e WHOOGLE_ALT_RD=libreddit.tiekoetter.com \
   -e WHOOGLE_ALT_TL=translate.tiekoetter.com \
   -e WHOOGLE_ALT_WIKI=wikiless.tiekoetter.com \
   -e WHOOGLE_CONFIG_NEW_TAB=1 \
   -e WHOOGLE_RESULTS_PER_PAGE=30 \
   -e WHOOGLE_CONFIG_GET_ONLY=1 \
   -e WHOOGLE_CONFIG_COUNTRY=UK \
   -e WHOOGLE_CONFIG_SEARCH_LANGUAGE=lang_en \
   -e WHOOGLE_CONFIG_LANGUAGE=lang_en \
   benbusby/whoogle-search:latest

I've deleted my old Firefox profile and am using my new Firefox profile and everything is working fine currently.

I'm not sure of the following and if anyone could answer these that would be great:
1. Why did I suddenly start getting Dubai as the location? after a week of English results? Google?
2. Does Firefox default search engine "remember" env variables when setting up Whoogle?

If anyone can help answer these questions for my sanity that would be great. 
I've added my docker setup to hopefully help others in the future.

**Comment by benbusby** [comment]
Hi, sorry for the delayed response.

1. By default, the results returned by Whoogle will reflect the location of where the instance is hosted. In this case, I guess it's possible that the server you were hosting on the Oracle Cloud Server was moved to a new location in Dubai. It looks like they do have servers located there, so it seems likely that's the case. For any server where you don't have a fixed hosting location, it's the right move to hardcode language/country values in Whoogle config vars, which from your last message it looks like you already did that. 
2. Firefox doesn't remember environment variables, but user configuration values that are set from the home page are stored in a cookie that can sometimes get reset after a while. But if you set config values through environment variables, those should stay the same no matter what, and Firefox won't be aware of them.

I'll close this for now, but feel free to reopen if you'd like further clarification.
