### ISSUE TITLE
[QUESTION] How to 'Set WHOOGLE_DOTENV=1' on local deployment

### ISSUE THREAD

**Issue by diogogmatos** [benbusby/whoogle-search#881]
Hey,
Sorry if this is a simple question, but I've been looking  e v e r y w h e r e  and I just can't seem to find out how to 'Set WHOOGLE_DOTENV=1' so I can use `whoogle.env` custom configuration. What do you mean by 'set'? How do you 'set' something? Should I add something to the `whoogle.service` file? Please clarify this for me :sweat_smile:  

Thank you <3

Ps. I want to set a configuration to solve a problem reported on #442

**Comment by benbusby** [comment]
Are you using systemd for your deployment? If so, you should be able to include the following line under the `[Service]` section of your file:

```
Environment=WHOOGLE_DOTENV=1
```

Let me know if that doesn't work for you though.
