### ISSUE TITLE
[QUESTION] How does local config get stored?

### ISSUE THREAD

**Issue by ForceConstant** [benbusby/whoogle-search#883]
I am a bit confused to the configuration that shows up on the bottom of the app. Does this just get stored as a cookie for that current session, or does that gets saved on the server side? If it is the former, does changes set on the server side set the defaults for these options for the sessions? 

Thanks.

**Comment by benbusby** [comment]
Pre 0.8.0, configuration was stored server side, but as of 0.8.0 this was refactored to store settings as a cookie. In both cases, the instance maintainer can set default config settings for their instance, but those are overridden by whatever the user modifies in the config panel.

**Comment by rihaq** [comment]
> Pre 0.8.0, configuration was stored server side, but as of 0.8.0 this was refactored to store settings as a cookie. In both cases, the instance maintainer can set default config settings for their instance, but those are overridden by whatever the user modifies in the config panel.

Doesn't work
