### ISSUE TITLE
[BUG] Performance issues because of lots of session files

### ISSUE THREAD

**Issue by PrivacyDevel** [benbusby/whoogle-search#886]
**Describe the bug**
Whoogle creates an excessive amount of session files in app/static/config/session.
Over time this leads to high cpu usage and very long loading times.
These sessions files should probably automatically get deleted after a certain period of time.

**To Reproduce**
1. Create a public Whoogle Search instance and leave it running for a long time
2. Experience very long loading times and high cpu usage

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.7.4
- [ ] Not sure

**Comment by benbusby** [comment]
I believe this is fixed in 32ad39d0e1529818289444d0352e1bf16beef400, which will be included in the next release. I'll push a new release this week that you can start using instead of 0.7.4.

**Comment by PrivacyDevel** [comment]
Ok, thank you! Btw. just a quick question, if you plan to push a new release, has the broken paging been fixed already? There has been an issue sometime after the 0.7.4 release that caused all result pages but the first one to break. Those pages showed no results anymore and the search query in the search box was replaces by some string base64 encoded looking string.

**Comment by benbusby** [comment]
@PrivacyDevel Yep, that should be fixed as well, by the same commit that I referenced. The previous library that was being used for session management was also erroneously regenerating user sessions prematurely, causing queries to not decrypt in between result pages (hence the encoded string you noticed).

**Comment by benbusby** [comment]
Just pushed 0.8.0, so I'm gonna close this now.
