### ISSUE TITLE
[BUG] Sponsored results on mobile

### ISSUE THREAD

**Issue by pred2k** [benbusby/whoogle-search#892]
**Describe the bug**
Sometimes i get sponsored results when i search on my whoogle instance on the phone.

**To Reproduce**
1. Do whoogle search for 'vserver'
4. See 'Gesponsert' results on Mobile only: 
### Mobile:
![Screenshot_20221128_095259_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/1071020/204236605-df9b29ce-0a9b-41e1-842b-b2f535db775d.jpg)

### Desktop:
![Bildschirmfoto 2022-11-28 um 09 53 16](https://user-images.githubusercontent.com/1071020/204236775-127780bd-a47c-4182-acf5-49e89656100c.png)

**Deployment Method**
- [x] Docker

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version **v0.8.0**

**Desktop:**
 - OS: MacOS 10.15.7
 - Browser Firefox
 - Version 105.0.3 (64-Bit)

**Smartphone:**
 - Device: Huawei
 - OS: Android
 - Browser Fennec F-Droid
 - Version 105.1.0

**Additional context**
Whoogle is hosted with Hetzner at german location 'DE Falkenstein fsn1' and has this env var config `WHOOGLE_CONFIG_COUNTRY="countryDE"`.

**Comment by benbusby** [comment]
Should be fixed now, thanks for reporting!
