### ISSUE TITLE
[BUG] Only first page works without cookies

### ISSUE THREAD

**Issue by PrivacyDevel** [benbusby/whoogle-search#895]
**Describe the bug**
There still seems to be an issue sometime after the 0.7.4 release (including 0.8.0) that causes all result pages but the first one to break when cookies are disabled. Those pages show no results anymore and the search query in the search box gets replaced by some base64 encoded looking string.

**To Reproduce**
1. Disable cookies in your browser
1. Go to https://search.dr460nf1r3.org/ (uses 0.8.0)
2. Search for something
3. Open second results page
4. See empty page and base64 encoded looking string

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.8.0
- [ ] Not sure

**Comment by benbusby** [comment]
Fixed in 0310f0f5421cb3984f947bb549866c1e0457ae5b -- this should be available on any instances that use the latest version of the code (such as the https://search.dr460nf1r3.org/ one) but I'll also be releasing an 0.8.1 update in a few days.
