### ISSUE TITLE
[BUG] Images/Videos not loading on Firefox but Works on Chrome

### ISSUE THREAD

**Issue by ssokhey** [benbusby/whoogle-search#896]
**Describe the bug**
Images/Videos not loading for me on Firefox

**To Reproduce**
1. Just search anything on Firefox
2. Firefox has UBlockOrigin Installed but I don't think it is causing any issues.

**Deployment Method**
- Docker

**Version of Whoogle Search**
- Just updated to latest before posting (i.e. 0.8.0)

**Desktop (please complete the following information):**
 - OS: PopOS 22.04  
 - Browser Firefox 107.0

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: GrapheneOS (Smartphone)
 - Browser: Mull 
 - Version Latest

**Additional context**
NA

Attaching images:

**Chrome**:

![Screenshot from 2022-12-03 12-34-31](https://user-images.githubusercontent.com/16058459/205430433-6de8c91a-8fe8-4742-8b80-9c9b203f8a43.png)

**Firefox**:

![Screenshot from 2022-12-03 12-35-54](https://user-images.githubusercontent.com/16058459/205430438-330f2e89-a191-4391-911f-b2c01d87ff5c.png)

**Also, uploading Firefox network tab screenshot if that helps:**

![GB](https://user-images.githubusercontent.com/16058459/205441451-8f9ff985-c4b0-42bc-9020-59c2752fe927.jpg)

**Comment by benbusby** [comment]
Should be fixed as of 0310f0f5421cb3984f947bb549866c1e0457ae5b. I'll push a version 0.8.1 with the fix later this week.

**Comment by ssokhey** [comment]
Hello @benbusby, Anything on this?

**Comment by benbusby** [comment]
@ssokhey v0.8.1 is being rolled out today, there should be a new docker tag in an hour or two.

**Comment by ssokhey** [comment]
Thanks @benbusby
