### ISSUE TITLE
[BUG] Query fails to decrypt on page navigation

### ISSUE THREAD

**Issue by Tarhyru** [benbusby/whoogle-search#90]
**Describe the bug**
Sometimes The switch will be garbled when searching for non-English

**To Reproduce**
1. configuration language:chinese(Simplified)
2. input such as "时间" -> there will be results
3. Turn the page or click another tab ->  The input box will become：
gAAAAABe6tLZJ_92Vc20a81fpWxCFjCSocJlYrh7jgTd32Lsi1BRV5C7_o1EmelIMnE5uxPRxcDutm3_RcRyHvHQVEyG_ykYMA==

And prompt me：
“找不到和您查询的“gAAAAABe6tNvojFZyx_oJql_hYUkEYeUzNjzQRmp95jNTrFAd4KmiGdLAv-OjqM4UVKoaHfdlaX-JGBxNVppnhLseFp5rLyVGg==”相符的内容或信息。”

Switching back will not restore，this look up base64，maybe there is a problem with the conversion？

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by benbusby** [comment]
Sorry for the late reply, I'm just now getting around to looking into this issue.

It's actually an issue for all languages, not just non-English languages. It looks like the fernet key regeneration after each query can sometimes be triggered prematurely, and so the query isn't able to be decrypted when navigating back from a result or navigating through pages in the results view.

I'll come back to this when I figure out a better solution.
