### ISSUE TITLE
[FEATURE] Time range of the search result

### ISSUE THREAD

**Issue by mada199122** [benbusby/whoogle-search#900]
**Describe the feature you'd like to see added**
In the Advanced Search bar please add the time filter as in the screenshot below.
Thanks in advance

![Screenshot 2022-12-06 at 14 47 13](https://user-images.githubusercontent.com/61902329/205929187-8fdfb3b8-a6e0-46b7-921b-3702f4c5d643.jpg)

**Comment by benbusby** [comment]
Added in #888
