### ISSUE TITLE
[FEATURE] Add an option to restrict outbound ports when using Tor routing

### ISSUE THREAD

**Issue by shimi-ke** [benbusby/whoogle-search#907]
When Whoogle is configured to route requests via Tor network, it uses basic torrc config.

For firewalls that restrict outbound connections there is a possibility to configure torrc to use only ports 80 and 443, which are rarely blocked. The easiest way how to achieve this goal is to use "FascistFirewall 1" config option in torrc. 

It would be great if a new environment variable would be added, that would set the above mentioned option in torrc config file.

There is another option which is a bit more complicated but more universal. Via "ReachableAdresses" config option it is possible to set outbound ports to be used for Tor routing. Actually, "FascistFirewall 1" is equivalent to "ReachableAddresses accept *:80" and "ReachableAddresses accept *:443".

Thanks for considering my feature request.

**Comment by benbusby** [comment]
I just pushed a change that allows setting `WHOOGLE_TOR_FF` to be set, and if so, enables the `FascistFirewall 1` setting. You have to have the correct permissions to edit the torrc file though. You didn't mention how you're running Whoogle, but as long as whatever user you're running Whoogle as has permissions to edit that file, it should work.

**Comment by shimi-ke** [comment]
Thank you for your effort.

First of all, I am running Whoogle as a Docker container using docker compose.

After setting WHOOGLE_TOR_FF to 1, "FascistFirewall 1" is appended at the end of torrc file. During the startup of the container I got _" * WARNING: tor is already starting"_ in the console of the VM where Docker is running. 

After the first search I got the error _"Tor was previously enabled, but the connection has been dropped. Please check your Tor configuration and try again.\n\nTor config is now disabled!"_ in my browser (Brave and Firefox). Whoogle then works but without Tor.

Previously, when I manually edited torrc file, Whoogle worked correctly via Tor network.

**Comment by benbusby** [comment]
> I am running Whoogle as a Docker container using docker compose.

Thanks, I'll test with that approach.

> After setting WHOOGLE_TOR_FF to 1, "FascistFirewall 1" is appended at the end of torrc file. During the startup of the container I got " * WARNING: tor is already starting" in the console of the VM where Docker is running.

I'll look into this and your other issue.
