### ISSUE TITLE
QUESTION: whom can I talk to about integrations / parterships?

### ISSUE THREAD

**Issue by serejandmyself** [benbusby/whoogle-search#91]
Hey! We are cyber_devs, the DAO that is building cyber, a decentralized google. It seems what we do goes in line, to an extent, to what you guys do. 

I would be interested to see if we can collaborate in any way.

Im not a huge fan of spamming links, however, here is a link to our /help page with further links to docs, code, etc

https://cyber.page/brain/help

**Comment by benbusby** [comment]
Hey @serejandmyself, thanks for reaching out. You can get in touch with me at `benbusby@protonmail.com` to talk more about collaborating and see what you had in mind.
