### ISSUE TITLE
www. in front of IP

### ISSUE THREAD

**Issue by Ian-Drunkenson** [benbusby/whoogle-search#913]
I have a local invodious device on 192.168.1.4:3000. I entered it at WHOOGLE_ALT_YT but when I call a YT vid Whoogle turns it to www.192.168.1.4:3000 and this of cource cant be found. What can I do?

**Comment by cazwacki** [comment]
Having the same issue for each of my locally hosted services other than nitter.

**Comment by benbusby** [comment]
Should be fixed now. You can use the `main` to access the fix, or the `latest` docker tag once it finishes building (~20 mins from now).
