### ISSUE TITLE
[QUESTION / FEATURE] Log rate limiting

### ISSUE THREAD

**Issue by gitterspec** [benbusby/whoogle-search#914]
Not sure if this is already possible, but it would be nice to be able to set Whoogle to report rate limiting to the console or a log.

This would be useful for those with access to dynamic IPs to automatically request a new IP or to automatically redirect search queries to a different app.

**Comment by benbusby** [comment]
Currently Whoogle returns a `503` error code if an instance gets rate limited (and only in that scenario), which should be loggable depending on how you're running your instance. Does that suit your needs or do you need something more? I don't mind adding something extra, just let me know what exactly would work best for you.

**Comment by gitterspec** [comment]
The 503 would work if it could be reported by Whoogle, as opposed to requiring a proxy sitting outside that. Are you saying this is is already implemented? I checked the console running Whoogle the last time I was rate limited and don't recall seeing a message. Thanks.

**Comment by benbusby** [comment]
Yes, the response code for the rate limiting page is a 503. I'm not able to manually force any of my personal instances into getting rate limited at the moment, and don't want to force any public ones to get rate limited to prove it, but the 503 response is in the code here:

https://github.com/benbusby/whoogle-search/blob/253ea62f8f2acc9a47dbbe327d0eadc6da1c19c9/app/routes.py#L328-L338

I'll close this for now, but reopen if you encounter the rate limiting issue and aren't actually getting the right error code.

**Comment by gitterspec** [comment]
I just tested and the server did not log rate limiting in the console. Indeed, the client gets a 503, but this feature request is about the server, since it would be the server that would change IPs automatically.

Can you please re-open?

**Comment by benbusby** [comment]
OK, rate limiting errors are now reported to the console. The reported error will look something like `ERROR:app:503 (CAPTCHA)`.

**Comment by gitterspec** [comment]
Thanks!
