### ISSUE TITLE
[BUG] WHOOGLE_CONFIG_COUNTRY not used in adaptable.io instance

### ISSUE THREAD

**Issue by askabaz22** [benbusby/whoogle-search#920]
**Describe the bug**
If I set the WHOOGLE_CONFIG_COUNTRY variable as "IT" or "CountryIT" it doesn't work, but when I used Heroku a few month ago it was working with "configIT". All the other variables (including WHOOGLE_CONFIG_LANGUAGE) work like a charm. 

Config in adaptable.io dashboard:
![immagine](https://user-images.githubusercontent.com/81743377/210179802-d3e5e226-1a10-46df-b256-539f1743b4ea.png)

What we have in Whoogle settings:
![immagine](https://user-images.githubusercontent.com/81743377/210179817-a0667716-413d-4cf2-90ab-bd7a12d4a2d4.png)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: adaptable.io deployment (similar to Heroku)

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [ ]
- [ ] Not sure

**Comment by askabaz22** [comment]
@benbusby Is there any way to set the country variable by hard-coding it? I think it can be a quick workaround for my forked instance.

**Comment by benbusby** [comment]
Sorry for the delay -- yes, you can change this line to match your preferred country value: https://github.com/benbusby/whoogle-search/blob/f7c4381ba626dfa76e4d6563db4d37cde5ee71a3/app/models/config.py#L26

Let me know if this still causes any problems and I can look further into possible incompatibility with adaptable.io
