### ISSUE TITLE
[QUESTION] New instance request

### ISSUE THREAD

**Issue by lnxredir** [benbusby/whoogle-search#933]
Hey, could you add my instance please?
URL: https:/wgl.frail.duckdns.org/
Onion: Optional
Country: Brazil
Cloudflare: no
Language: Multi-choice

If you need any additional information just let me know. Also, the instance results are all in portuguese but the UI is in english, but the option to change the language is there, I don't want to change the language or the location, I want to keep this instance as an entry/discovery point about this and many other front-ends/proxys to the Brazilian people.

**Comment by benbusby** [comment]
Added -- thank you!
