### ISSUE TITLE
[QUESTION] Replace Whoogle Farside link in "Instance limited" page

### ISSUE THREAD

**Issue by askabaz22** [benbusby/whoogle-search#938]
When self-hosting the service, is it possibile to replace the Whoogle farside link in the "instance limited" error page with a link to a particular Whoogle instance we prefer? Would be amazing to have direct redirect to another personal Whoogle instance as a back-up for the main one

**Comment by Moist-Cat** [comment]
The link is hard-coded [here](https://github.com/benbusby/whoogle-search/blob/main/app/routes.py#L336). So you can't configure it but I guess you can manually edit the file and add another URL.

**Comment by askabaz22** [comment]
> The link is hard-coded [here](https://github.com/benbusby/whoogle-search/blob/main/app/routes.py#L336). So you can't configure it but I guess you can manually edit the file and add another URL.

I've tried to add the URL of the instance in that line but it can't work because "/whoogle/" is added after the URL I set. How can I remove that line, so that it redirect correctly to my instance?

![Immagine 2023-01-28 164043](https://user-images.githubusercontent.com/81743377/215275781-1bde4c41-8acd-43da-9c70-fab121eb1eed.png)

**Comment by Moist-Cat** [comment]
> I've tried to add the URL of the instance in that line but it can't work because "/whoogle/" is added after the URL I set. How can I remove that line, so that it redirect correctly to my instance?

That's in [error.html](https://github.com/benbusby/whoogle-search/blob/main/app/templates/error.html#L27) . Remove "whoogle/" from the link.

**Comment by benbusby** [comment]
@askabaz22 The above suggestion should work for you, but let me know if you're still having issues.
