### ISSUE TITLE
[QUESTION] Address Bar Search Suggestions

### ISSUE THREAD

**Issue by zhdenny** [benbusby/whoogle-search#94]
When you type in the address bar, I'd like to see search suggestions appear.

In my browser settings (Vivaldi), you input a Search URL like "https://<your whoogle url>/search?q=%s"

but there is also a Suggest URL....for Google, this is the Suggest URL....and it lets you see Search Suggestions while you are typing in the Address Bar.
https://www.google.com/complete/search?client=chrome&q=%s

Does Whoogle have something like this?

**Comment by benbusby** [comment]
Yes, it's `<whoogle url>/autocomplete?q=%s`

**Comment by Pootch** [comment]
Where do you set the autocompletion url? If I change the search engine in edge, I get an error when searching in the adress bar.
