### ISSUE TITLE
scribe bug

### ISSUE THREAD

**Issue by 0xspade** [benbusby/whoogle-search#947]
**To Reproduce**
1. social alternative should be set to True. (This is limited only for scribe the medium alternative).
2. In my case, search "medium 0xspade" or whoever medium you know.
3. click one of my blog post from medium.
4. You'll notice that the links are "0xspade.farside.link", my original medium link is "0xspade.medium.com"

Well `0xspade.farside.link` or anything like `<medium username>.farside.link` is not existing.

![whoogle - bug](https://user-images.githubusercontent.com/18681023/216306020-c61f22ba-9035-4519-84c5-896f40c451c3.png)

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by benbusby** [comment]
Should be fixed now, thanks for reporting!
