### ISSUE TITLE
Istance add

### ISSUE THREAD

**Issue by hxvy0** [benbusby/whoogle-search#948]
Im owner of Indexia.gq and i moved it to whoogle.hxvy0.gq. Still canada but its now only turkish. cloudflare yes.

**Comment by hxvy0** [comment]
proof of ownership of indexia;
![resim](https://user-images.githubusercontent.com/85783692/216604550-ff5f78a3-b998-496b-8ec3-f712c59d0733.png)
![resim](https://user-images.githubusercontent.com/85783692/216604848-c5e50502-d294-404f-9c75-4211c69eaa98.png)

**Comment by benbusby** [comment]
Updated, thanks!
