### ISSUE TITLE
[QUESTION] Doesn't load on older browsers?

### ISSUE THREAD

**Issue by bb8700c** [benbusby/whoogle-search#95]
Whoogle doesn't seem to load on older browsers, 
Just get a white screen on my blackberry q10's browser(based on an older webkit) and also IE8 for testing purposes. On the console of IE here's the error-
`SCRIPT1002: Syntax error
File: autocomplete.js, Line: 1, Column: 36
`
`
SCRIPT1002: Syntax error
File: controller.js, Line: 1, Column: 30
`

I get I'm using ancient stuff, so i'm not expecting it to be fixed but I figured i'd ask

**Comment by benbusby** [comment]
Yeah, looks like the ES6 features I'm using in the javascript aren't supported on older browsers. If you don't mind losing the autocomplete and UI level configuration features of Whoogle, you could maybe just remove the `autocomplete.js` and `controller.js` scripts from ever being loaded in `index.html` and `display.html`. The core search functionality doesn't rely on any javascript, so it should still work fine with the scripts removed, but there may be some UI weirdness. 

I'll close this issue for now, but I'll revisit this if I think of a better way to include support for older browsers.
