### ISSUE TITLE
[BUG] Instagram Redirect - Please Stop

### ISSUE THREAD

**Issue by gabeanelson** [benbusby/whoogle-search#955]
Biblogram no longer works. That said, I can’t figure out how to solely turn on access to Instagram via whoogle search. It always redirects to the farside link, which doesn’t work anymore. 

There is a configuration option to turn off all social media redirects, but Instagram is the only one that isn’t functional, which is why I’d like to be able to turn off that redirect.

**Comment by jacr13** [comment]
On the README I see  "The instagram.com alternative to use when site alternatives are enabled in the config. Set to "" to disable." aren't it what you are looking for?
The parameter is WHOOGLE_ALT_IG.

**Comment by gabeanelson** [comment]
Thanks for the suggestion. I've tried using "", but it doesn't disable the Instagram redirect. Instead, when I search for Instagram, it lists https://""/.

**Comment by benbusby** [comment]
> Thanks for the suggestion. I've tried using "", but it doesn't disable the Instagram redirect. Instead, when I search for Instagram, it lists https://""/.

That's odd. If I set `WHOOGLE_ALT_IG=""` or even just `WHOOGLE_ALT_IG=` (no value) then the Instagram redirect is disabled for me. It should just be set to an empty value, but it seems like the environment variable retains the double quotes in your case. 

Either way, I went ahead and removed Bibliogram redirects altogether. I was hoping that someone else would come along and make a suitable replacement, but it doesn't seem like that's happened/going to happen anytime soon.

**Comment by gabeanelson** [comment]
Thanks!!

**Comment by whaler-ragweed** [comment]
> That's odd. If I set `WHOOGLE_ALT_IG=""` or even just `WHOOGLE_ALT_IG=` (no value) then the Instagram redirect is disabled for me. It should just be set to an empty value, but it seems like the environment variable retains the double quotes in your case.

I just encounter the same issue. Turns out that in the docker compose file, it needs to be `WHOOGLE_ALT_XXX=` (no quotes) to work.
