### ISSUE TITLE
[BUG] Deploy fails on Replit

### ISSUE THREAD

**Issue by HashLiver** [benbusby/whoogle-search#963]
**Describe the bug**
![probrem](https://user-images.githubusercontent.com/42889797/220529152-362624eb-7c6d-49dc-a9f9-c079ab5c0cc5.png)

**To Reproduce**
Just click the "Made with Repit" button, language select "Python", then deploy fail.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by E-Baler** [comment]
Hello, same here run fails on Replit with this comment : 

No such file: main.py
repl process died unexpectedly: exit status 2

Any idea please ? Thanks !

**Comment by benbusby** [comment]
This should be fixed now.

**Comment by E-Baler** [comment]
@benbusby Thanks a lot !!!
