### ISSUE TITLE
[QUESTION] no tag 0.8.2 in ghcr.io

### ISSUE THREAD

**Issue by alexdelprete** [benbusby/whoogle-search#979]
Hi,

in the GH package repo after `0.8.1` there's only the `latest` tag, not `0.8.2`.

**Comment by pred2k** [comment]
My instance shows 'Update Available' in footer. But i daily pull `benbusby/whoogle-search:latest` and restart the container.

**Comment by eddydc** [comment]
Same issue here. Did a git pull, pip install and restarted the deamon. 
Still shows "Whoogle Search v0.8.1 || View on GitHub || Update Available"

**Comment by eddydc** [comment]
Any news on this? How to solve this when not using the docker version?

**Comment by benbusby** [comment]
Should be fixed now
