### ISSUE TITLE
[BUG] Search result units not matching country/language setting.

### ISSUE THREAD

**Issue by ilovepancakes95** [benbusby/whoogle-search#98]
**Describe the bug**
Data value units not matching typical units used in language/country.

**To Reproduce**
1. Language and Country set to English/United States.
2. Search "weather [insert city/state here]" or "bitcoin price".
3. View results. Weather shows up in degrees centigrade and bitcoin price shows up in Ugandan Shilling.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [X] Version 0.2.0
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
Running same search directly from Google on same machine running Whoogle does return the correct units (i.e. degrees Fahrenheit/United States Dollar).

**Comment by benbusby** [comment]
Just did some testing with this, and unfortunately it doesn't seem like this is something Whoogle can control directly. The pop up "card" that gets returned at the top of the results page for maps/weather/exchange price/etc all seem to ignore the country param that gets passed over during search. I was able to try the inverse of this -- using "regular" Google search and setting my country/language to be outside of the U.S., and I was still getting American units when I shouldn't. 

I'll look into it a bit more this week and see if I can find anything else.

**Comment by ilovepancakes95** [comment]
I thought maybe Google decides based on IP address "location" although the VPS Whoogle is running on is a US IP and an actual Google search from same machine returns correct units so I'm stumped. Also, where can we send you some money for a beer and pizza? Thanks for your constant dedication to this project. 😃

**Comment by benbusby** [comment]
> I thought maybe Google decides based on IP address "location" although the VPS Whoogle is running on is a US IP and an actual Google search from same machine returns correct units so I'm stumped.

That's odd...hmmm. Well, I'm in the middle of moving over a lot of my sites to new servers in new locations, so I'll continue to keep an eye out for why this could be happening. I've migrated my Whoogle instance a lot over the last few months and haven't encountered it, but maybe I've just been lucky. 

> Also, where can we send you some money for a beer and pizza? Thanks for your constant dedication to this project. 😃

My pleasure! I wish I could dedicate a bit more time to it, but my free time is a bit scarce atm with work, other projects, plus moving. I have a [paypal donation page](https://paypal.me/benjaminbusby) set up, but let me know if there's a different way you'd prefer. Either way I greatly appreciate it.

**Comment by ilovepancakes95** [comment]
> That's odd...hmmm. Well, I'm in the middle of moving over a lot of my sites to new servers in new locations, so I'll continue to keep an eye out for why this could be happening. I've migrated my Whoogle instance a lot over the last few months and haven't encountered it, but maybe I've just been lucky.
>
If I search "bitcoin price usd" it does show result in USD. And probably unrelated but weather searches do only show current condition and temp, not the full forecast card that google searches show.
> My pleasure! I wish I could dedicate a bit more time to it, but my free time is a bit scarce atm with work, other projects, plus moving. I have a [paypal donation page](https://paypal.me/benjaminbusby) set up, but let me know if there's a different way you'd prefer. Either way I greatly appreciate it.
>
PayPal is fine, unless you would prefer crypto. Some beer and pizza headed your way soon.

**Comment by benbusby** [comment]
> PayPal is fine, unless you would prefer crypto. Some beer and pizza headed your way soon.

Nah just PayPal is fine with me for now. Thanks a bunch!

Will keep you posted if I find a solution for this, but still am having a hard time reproducing it on my newest infrastructure.

**Comment by ilovepancakes95** [comment]
> Will keep you posted if I find a solution for this, but still am having a hard time reproducing it on my newest infrastructure.

Ahh interesting, I thought it was doing same thing on your end just not obeying other countries. So you get American units when you search with cards no matter which country you have Whoogle set to? Very weird then I would randomly get Ugandan units and Celsius when searching.

On another, slightly related note, I don't get some cards at all, like typing a FedEx or USPS or UPS tracking number into Whoogle doesn't return the cool package tracking card and link to further info on the carrier's site. Let me know if you want a separate issue opened for that one.

**Comment by benbusby** [comment]
Hey again -- I still haven't been able to replicate this issue, so I'm going to close it for now. I'll keep an eye out for it though and let you know if that changes. 

I did finally get around to implementing basic support for detecting tracking numbers though, so not all bad news!

**Comment by ilovepancakes95** [comment]
> Hey again -- I still haven't been able to replicate this issue, so I'm going to close it for now. I'll keep an eye out for it though and let you know if that changes.
> 
> I did finally get around to implementing basic support for detecting tracking numbers though, so not all bad news!

Hello! Thanks for the follow-up. It actually has seemed to be working normally the past couple months. Not sure if it changed after update to latest release back then or something else happened to fix it, but I do get USD when searching "bitcoin" for example now, and temps in F when searching weather.

Awesome on package tracking, will check that out. Regarding weather, would be great to get the full interactive forecast "widget" that real google provides when searching "weather san francisco" for example.
