### ISSUE TITLE
[BUG] Preferences missing when added as default search engine

### ISSUE THREAD

**Issue by brokoler** [benbusby/whoogle-search#983]
**Describe the bug**
When adding Whoogle as a search engine in Firefox or Chromium based browsers, the preferences string is ignored.
This should work when "GET Requests only" is chosen.

In earlier versions the preferences string was saved in a GET URL format when the search engine was added.
Would be great if the preferences string could be added again.

What is happening:
`https://whoogle.hostux.net/search?q=test`

What I expect:
`https://whoogle.hostux.net/search?preferences=<PREFERENCES_KEY>&q=test`

**To Reproduce**
1. Go to Whoogle and enable "GET Requests only" in the settings, save them
2. Search for something on Whoogle
3. Add the search engine via right click in the address bar to firefox or set it in Chromium browsers (automatically added after searching)
4. Search Whoogle via the address bar of your browser
5. See that the search query now is https://whoogle.hostux.net/search?q=test and the preferences string is missing

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: Tested with multiple public instances (e.g. whoogle.hostux.net)

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.81
- [ ] Not sure

**Comment by jacr13** [comment]
Hello,

It was removed in this [commit](https://github.com/benbusby/whoogle-search/commit/f7c4381ba626dfa76e4d6563db4d37cde5ee71a3).

See the linked issue: #929
