### ISSUE TITLE
[BUG] No update to current version 0.8.2 with docker-compose

### ISSUE THREAD

**Issue by cpu2910** [benbusby/whoogle-search#985]
**Describe the bug**
I installed a fresh version with docker-compose as described here:
https://github.com/benbusby/whoogle-search#manual-docker
but it's 'only' v0.8.1, NOT v0.8.2

**To Reproduce**
1. git clone https://github.com/benbusby/whoogle-search.git
2. cd whoogle-search
3. docker-compose up -d
4. When accessing the search site, it says: Whoogle Search v0.8.1 || [View on GitHub](https://github.com/benbusby/whoogle-search) || Update Available

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Linux Mint 21]
 - Browser [Firefox]
 - Version [111]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nealhead** [comment]
Looks like the 'latest' tag is not updated

**Comment by benbusby** [comment]
Should be fixed now.

**Comment by cpu2910** [comment]
Yes, I can confirm this, v0.8.2 is running now.
Thank you for the quick response.
