### ISSUE TITLE
What do I need to do to make the process run in the background?

### ISSUE THREAD

**Issue by MuerteRoja** [benbusby/whoogle-search#986]
Hello, good afternoon, I have recently installed the Whoogle search engine following this video tutorial https://youtu.be/BuLREHRKyag however, when I close the Ubuntu app I can't access the whoogle search engine, does anyone know how I can run the process in the background even though I have closed the Ubuntu app?

The process I want to run in the background: cd whoogle-search 
./run
Before I forgot to mention it, the operating system I use is Windows 11 Pro

![Captura de pantalla 2023-04-14 182617](https://user-images.githubusercontent.com/126993006/232115089-636a0b09-69ea-4959-87a0-0d08faf19746.png)
![Captura de pantalla 2023-04-14 130356](https://user-images.githubusercontent.com/126993006/232115099-0f3f2bb0-7a2c-4ced-80eb-9d19cde6e16a.png)
![Captura de pantalla 2023-04-14 182636](https://user-images.githubusercontent.com/126993006/232115102-7772dbbe-519a-4b15-9aa0-7208caf083b2.png)

**Comment by benbusby** [comment]
Hi, sorry for the late reply! In this case, it sounds like you have to keep Ubuntu/WSL open in the background for the Whoogle to continue running (see: https://askubuntu.com/questions/1435938/is-it-possible-to-run-a-wsl-app-in-the-background). I don't use Windows personally, so I can't look into this any further on my end, unfortunately.
