### ISSUE TITLE
[BUG] Most relevant results not shown everytime

### ISSUE THREAD

**Issue by cs-nero** [benbusby/whoogle-search#990]
**Describe the bug**
I don't get the most relevant search results.
If I search for "Docker Hub", in Google, I get the following first result:
![grafik](https://user-images.githubusercontent.com/47950220/233087349-73191b78-82e1-4409-9814-138a94bb5502.png)

If I search the same in Whoogle, I don't get it:
![grafik](https://user-images.githubusercontent.com/47950220/233087600-fbfc5501-a592-47b6-9fb1-a248f906636e.png)

Same if you search for "Instagram" and many others.

**To Reproduce**
1. Go to Google and search for "Docker Hub" or "Instagram".
2. Go to Whoogle and search for "Docker Hub" or "Instagram".
3. Compare the results

**Deployment Method**
Docker

**Version of Whoogle Search**
Latest Docker Image (v0.8.2 on April 19 2023)

**Desktop (please complete the following information):**
Linux with Firefox

**Comment by benbusby** [comment]
This is an issue with how Google modifies results for non-US / non-English searches. Results are usually identical when searching on google.com vs an instance hosted on your local machine, but can be different when modifying Whoogle's language/country config or using an instance that is located in a different region than your own. 

Unfortunately there's not really a fix for this. Whoogle only modifies URL params when making the request, it doesn't have anything to do with what results you get (other than filtering out advertising content). You can try messing around with the language/country config -- sometimes setting "country" to "---" fixes these types of issues, but it depends on how the instance is hosted.
