### ISSUE TITLE
Environmental variables

### ISSUE THREAD

**Issue by CaptainFrosty** [benbusby/whoogle-search#991]
I am trying to add environmental variables to my container. I am using podman rather than docker if that matters. When I add an environmental file argument when I run it the application doesn't work. Then I tried using `podman run --env 'WHOOGLE*' whoogle-search` to add them from my system environment and that didn't work.

**Comment by CaptainFrosty** [comment]
```
Apr 27 20:54:49.944 [notice] Tor 0.4.6.9 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1t, Zlib 1.2.12, Liblzma 5.2.5, Libzstd 1.5.0 and Unknown N/A as libc.
Apr 27 20:54:49.946 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 27 20:54:49.947 [notice] Read configuration file "/etc/tor/torrc".
Apr 27 20:54:49.953 [notice] Opening Socks listener on 127.0.0.1:9050
Apr 27 20:54:49.954 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
Apr 27 20:54:49.954 [notice] Opening Control listener on 127.0.0.1:9051
Apr 27 20:54:49.954 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051
Apr 27 20:54:49.955 [warn] Fixing permissions on directory /var/lib/tor
^C
* Finished creating ddg bangs json
```

This is what happens when I try to run it with variables with either --env or --env-file. I am not even trying to use Tor.

**Comment by CaptainFrosty** [comment]
The content of whoogle.env is just:

```
❯ cat whoogle.env
WHOOGLE_CONFIG_DISABLE=""
WHOOGLE_CONFIG_THEME="dark"
```

**Comment by CaptainFrosty** [comment]
Well, I guess I'll try a regular install next if I can't get any assistance concerning getting environmental variables to containers without somehow activating Tor instead.

**Comment by CaptainFrosty** [comment]
To be clear it works with no variables passed.

**Comment by CaptainFrosty** [comment]
Or I could try installing real Docker I suppose. If I HAVE to. :grin:

**Comment by benbusby** [comment]
@CaptainFrosty feel free to reopen this if you're still having issues!
