### ISSUE TITLE
[QUESTION] How to redirect to self-hosted alternatives?

### ISSUE THREAD

**Issue by usersink** [benbusby/whoogle-search#992]
Is there any way to replace/update the farside.link alts so that they point to self-hosted services ie your _own_ instance of invidious, rather than publicly available ones?

**Comment by benbusby** [comment]
Under [this section of the README](https://github.com/benbusby/whoogle-search#environment-variables) are a set of `WHOOGLE_ALT_%s` environment variables that you can set to redirect to whatever instance you want.

**Comment by usersink** [comment]
Thanks for getting back to me, and for a great app! 

If I replace the farside link with ANY value, the container won't launch. I'm using Portainer and keep getting this error: 

"Failed to deploy a stack: Container whoogle Recreate Error response from daemon: invalid mount path: 'WHOOGLE_ALT_YT=example.com' mount path must be absolute"

I'm not sure what that means in the context of a link.

**Comment by benbusby** [comment]
That sounds like it might be an issue with the command used for launching the container, not the environment variable itself. Does your `WHOOGLE_ALT_YT=example.com` come after a `--mount` or `--volume` flag by chance? It seems like as the command is being parsed, it's looking for a mount location, and is finding an environment variable instead.

**Comment by usersink** [comment]
Translation: I hadn't uncommented the environment line :hangs-head-in-shame:

Thank you sooo much for taking the time, and for your patience!

**Comment by benbusby** [comment]
No problem!
